import { randomUUID } from 'node:crypto';
const fail=message=>{throw Object.assign(new Error(message),{status:400});};
const first=r=>r?.results?.[0]||null;
const keyOk=k=>typeof k==='string'&&k.trim().length>=8&&k.trim().length<=100;
const codeExpr=prefix=>`'${prefix}-'||strftime('%Y%m%d','now')||'-'||printf('%03d',COALESCE((SELECT max(CAST(substr(${prefix==='TI'?'trade_in_code':'inspection_code'},-3) AS INTEGER)) FROM ${prefix==='TI'?'trade_ins':'trade_in_inspections'} WHERE ${prefix==='TI'?'trade_in_code':'inspection_code'} LIKE '${prefix}-'||strftime('%Y%m%d','now')||'-%'),0)+1)`;

export async function createTradeIn(db,{p_data:d,p_actor:actor,p_idempotency_key:key}){
  const brand=String(d?.brand||'').trim(),model=String(d?.model||'').trim();
  if(!brand||brand.length>100||!model||model.length>200||!actor||!keyOk(key))fail('Thông tin trade-in không hợp lệ');
  const id=randomUUID(), customer=d.customer_id?Number(d.customer_id):null, order=d.order_id?Number(d.order_id):null;
  const b=await db.batch([
    db.prepare(`SELECT CASE WHEN EXISTS(SELECT 1 FROM trade_ins WHERE idempotency_key=?) THEN 1
      WHEN (? IS NULL OR EXISTS(SELECT 1 FROM customers WHERE id=?)) AND (? IS NULL OR EXISTS(SELECT 1 FROM orders WHERE id=?))
      THEN 1 ELSE json('invalid trade-in references') END`).bind(key,customer,customer,order,order),
    db.prepare(`INSERT INTO trade_ins(id,trade_in_code,customer_id,order_id,brand,model,serial,cpu,gpu,ram,ssd,status,reported_condition,notes,idempotency_key,created_by)
      SELECT ?,${codeExpr('TI')},?,?,?,?,?,?,?,?,?,'DRAFT',?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM trade_ins WHERE idempotency_key=?)`)
      .bind(id,customer,order,brand,model,String(d.serial||'').trim()||null,String(d.cpu||'')||null,String(d.gpu||'')||null,String(d.ram||'')||null,String(d.ssd||'')||null,String(d.reported_condition||'').slice(0,2000),String(d.notes||'').slice(0,2000),key,actor,key),
    db.prepare(`INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) SELECT 'TRADE_IN',id,'CREATE',json_object('event','TRADE_IN_CREATED','code',trade_in_code),? FROM trade_ins WHERE id=?`).bind(actor,id),
    db.prepare('SELECT * FROM trade_ins WHERE idempotency_key=?').bind(key)]);
  return first(b.at(-1));
}
export async function startTradeInInspection(db,{p_id:id,p_user_id:user,p_mainboard_status:board='UNKNOWN',p_findings:findings,p_actor:actor,p_idempotency_key:key}){
  if(!id||!['ORIGINAL','OFFICIAL_REPLACED','REPAIRED','UNKNOWN'].includes(board)||!actor||!keyOk(key))fail('Thông tin inspection không hợp lệ');
  const existing=await db.prepare("SELECT * FROM trade_in_inspections WHERE trade_in_id=? AND status='IN_PROGRESS'").bind(id).first();if(existing)return existing;
  const inspection=randomUUID();const b=await db.batch([
    db.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM trade_ins WHERE id=? AND status IN ('DRAFT','INSPECTING')) THEN 1 ELSE json('trade-in cannot be inspected') END").bind(id),
    db.prepare(`INSERT INTO trade_in_inspections(id,trade_in_id,status,mainboard_status,findings,inspected_by) VALUES(?,?,'IN_PROGRESS',?,?,?)`).bind(inspection,id,board,String(findings||'').slice(0,5000),user||null),
    db.prepare("UPDATE trade_ins SET status='INSPECTING',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?").bind(id),
    db.prepare(`INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('TRADE_IN_INSPECTION',?,'CREATE',json_object('event','TRADE_IN_INSPECTION_STARTED','trade_in_id',?,'idempotency_key',?),?)`).bind(inspection,id,key,actor),
    db.prepare('SELECT * FROM trade_in_inspections WHERE id=?').bind(inspection)]);return first(b.at(-1));
}
export async function completeTradeInInspection(db,{p_id:id,p_mainboard_status:board,p_findings:findings,p_checks:checks,p_actor:actor,p_idempotency_key:key}){
  if(!id||!['ORIGINAL','OFFICIAL_REPLACED','REPAIRED','UNKNOWN'].includes(board)||!Array.isArray(checks)||!checks.length||checks.some(x=>!String(x.check_key||'').trim()||!['PASS','FAIL','WARNING','NOT_TESTED'].includes(x.result))||!actor||!keyOk(key))fail('Kết quả inspection không hợp lệ');
  const current=await db.prepare('SELECT * FROM trade_in_inspections WHERE id=?').bind(id).first();if(!current)fail('Không tìm thấy inspection');if(current.status==='COMPLETED')return current;
  const stmts=[db.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM trade_in_inspections WHERE id=? AND status='IN_PROGRESS') THEN 1 ELSE json('inspection not active') END").bind(id)];
  for(const x of checks)stmts.push(db.prepare('INSERT INTO trade_in_check_items(inspection_id,check_key,result,notes) VALUES(?,?,?,?)').bind(id,String(x.check_key).trim().toUpperCase().slice(0,60),x.result,String(x.notes||'').slice(0,1000)));
  stmts.push(db.prepare("UPDATE trade_in_inspections SET status='COMPLETED',mainboard_status=?,findings=?,completed_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?").bind(board,String(findings||'').slice(0,5000),id),db.prepare("UPDATE trade_ins SET status='QUOTED',updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?").bind(current.trade_in_id),db.prepare(`INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('TRADE_IN_INSPECTION',?,'UPDATE',json_object('event','TRADE_IN_INSPECTION_COMPLETED','idempotency_key',?),?)`).bind(id,key,actor),db.prepare('SELECT * FROM trade_in_inspections WHERE id=?').bind(id));
  return first((await db.batch(stmts)).at(-1));
}
export async function acceptTradeIn(db,{p_id:id,p_order_id:order,p_estimated:estimated,p_agreed:agreed,p_actor:actor}){
  if(!id||!Number.isFinite(agreed)||agreed<=0||!actor)fail('Thông tin chấp nhận trade-in không hợp lệ');const b=await db.batch([
    db.prepare(`SELECT CASE WHEN EXISTS(SELECT 1 FROM trade_ins WHERE id=? AND status IN ('QUOTED','INSPECTING')) AND EXISTS(SELECT 1 FROM orders WHERE id=? AND order_status NOT IN ('cancelled','returned') AND debt_amount*1000000>=?) THEN 1 ELSE json('trade-in cannot be accepted') END`).bind(id,order,agreed),
    db.prepare("UPDATE orders SET trade_in_credit_vnd=trade_in_credit_vnd+?,debt_amount=debt_amount-?/1000000,trade_in_laptop_id=NULL,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?").bind(agreed,agreed,order),
    db.prepare("UPDATE trade_ins SET status='ACCEPTED',order_id=?,estimated_value_vnd=?,agreed_value_vnd=?,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?").bind(order,estimated,agreed,id),
    db.prepare(`INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('TRADE_IN',?,'UPDATE',json_object('event','TRADE_IN_ACCEPTED','order_id',?,'credit_vnd',?),?)`).bind(id,order,agreed,actor),db.prepare('SELECT * FROM trade_ins WHERE id=?').bind(id)]);return first(b.at(-1));
}
export async function rejectTradeIn(db,{p_id:id,p_reason:reason,p_actor:actor}){if(!id||!String(reason||'').trim()||!actor)fail('Lý do từ chối là bắt buộc');const b=await db.batch([db.prepare("SELECT CASE WHEN EXISTS(SELECT 1 FROM trade_ins WHERE id=? AND status IN ('DRAFT','INSPECTING','QUOTED')) THEN 1 ELSE json('trade-in cannot be rejected') END").bind(id),db.prepare("UPDATE trade_ins SET status='REJECTED',notes=substr(COALESCE(notes,'')||char(10)||'Từ chối: '||?,1,2000),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?").bind(String(reason).trim(),id),db.prepare(`INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('TRADE_IN',?,'UPDATE',json_object('event','TRADE_IN_REJECTED','reason',?),?)`).bind(id,String(reason).slice(0,500),actor),db.prepare('SELECT * FROM trade_ins WHERE id=?').bind(id)]);return first(b.at(-1));}
export async function receiveTradeIn(db,{p_id:id,p_actor:actor,p_idempotency_key:key}){if(!id||!actor||!keyOk(key))fail('Thông tin nhận trade-in không hợp lệ');const cur=await db.prepare('SELECT * FROM trade_ins WHERE id=?').bind(id).first();if(!cur)fail('Không tìm thấy trade-in');if(['RECEIVED','CONVERTED_TO_INVENTORY'].includes(cur.status))return cur;if(cur.status!=='ACCEPTED')fail('Chỉ trade-in ACCEPTED được nhận');const b=await db.batch([db.prepare("UPDATE trade_ins SET status='RECEIVED',received_at=strftime('%Y-%m-%dT%H:%M:%fZ','now'),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?").bind(id),db.prepare(`INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('TRADE_IN',?,'UPDATE',json_object('event','TRADE_IN_RECEIVED','idempotency_key',?),?)`).bind(id,key,actor),db.prepare('SELECT * FROM trade_ins WHERE id=?').bind(id)]);return first(b.at(-1));}
export async function convertTradeInToInventory(db,{p_id:id,p_data:data,p_actor:actor,p_idempotency_key:key}){if(!id||!actor||!keyOk(key))fail('Thông tin chuyển kho không hợp lệ');const t=await db.prepare('SELECT * FROM trade_ins WHERE id=?').bind(id).first();if(!t)fail('Không tìm thấy trade-in');if(t.inventory_laptop_id)return db.prepare('SELECT * FROM laptops WHERE id=?').bind(t.inventory_laptop_id).first();if(t.status!=='RECEIVED'||t.agreed_value_vnd<=0)fail('Trade-in chưa được nhận hợp lệ');const costId=randomUUID();const b=await db.batch([db.prepare(`INSERT INTO laptops(serial,name,category,status,location,is_active,source_type,source_reference_id,received_at,warehouse_date,created_by) VALUES(?,?,?,'waiting_qc',?,1,'TRADE_IN',?,strftime('%Y-%m-%dT%H:%M:%fZ','now'),date('now'),?)`).bind(t.serial||`TI-${id.slice(0,8)}`,`${t.brand} ${t.model}`.trim(),data?.category||'TRADE_IN',data?.location||'store',id,actor),db.prepare(`INSERT INTO laptop_cost_components(id,laptop_id,cost_type,amount_vnd,source_type,source_id,description,created_by) VALUES(?,last_insert_rowid(),'TRADE_IN_ACQUISITION',?,'TRADE_IN',?,?,?)`).bind(costId,t.agreed_value_vnd,id,`Thu cũ đổi mới ${t.trade_in_code}`,actor),db.prepare("UPDATE trade_ins SET status='CONVERTED_TO_INVENTORY',inventory_laptop_id=(SELECT laptop_id FROM laptop_cost_components WHERE id=?),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE id=?").bind(costId,id),db.prepare('SELECT l.* FROM laptops l JOIN trade_ins t ON t.inventory_laptop_id=l.id WHERE t.id=?').bind(id)]);return first(b.at(-1));}
