-- CitiLap Admin: security and schema reconciliation
-- Run once in Supabase SQL Editor. This migration does not delete business data.

BEGIN;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS amount_paid NUMERIC DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS debt_amount NUMERIC DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_info TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_address TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS reservation_expires_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
  changes JSONB,
  user_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
CREATE INDEX IF NOT EXISTS activity_logs_entity_created_at_idx
  ON activity_logs (entity_type, entity_id, created_at DESC);

-- The application treats these status values as an active reservation. Advisory
-- locking makes simultaneous requests for the same laptop serialize safely.
CREATE OR REPLACE FUNCTION public.prevent_laptop_double_reservation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.laptop_id IS NULL OR NEW.is_active IS NOT TRUE THEN
    RETURN NEW;
  END IF;

  IF COALESCE(NEW.payment_status, '') <> 'refunded'
     AND NEW.order_status NOT IN ('cancelled', 'returned')
     AND (
       NEW.order_status IN ('prepared', 'shipping', 'done')
       OR (
         (NEW.order_status = 'deposited' OR NEW.payment_status = 'deposited')
         AND (NEW.reservation_expires_at IS NULL OR NEW.reservation_expires_at > CURRENT_TIMESTAMP)
       )
     ) THEN
    PERFORM pg_advisory_xact_lock(NEW.laptop_id);
    IF EXISTS (
      SELECT 1
      FROM orders existing_order
      WHERE existing_order.laptop_id = NEW.laptop_id
        AND existing_order.id IS DISTINCT FROM NEW.id
        AND existing_order.is_active IS TRUE
        AND COALESCE(existing_order.payment_status, '') <> 'refunded'
        AND existing_order.order_status NOT IN ('cancelled', 'returned')
        AND (
          existing_order.order_status IN ('prepared', 'shipping', 'done')
          OR (
            (existing_order.order_status = 'deposited' OR existing_order.payment_status = 'deposited')
            AND (existing_order.reservation_expires_at IS NULL OR existing_order.reservation_expires_at > CURRENT_TIMESTAMP)
          )
        )
    ) THEN
      RAISE EXCEPTION 'Laptop % is already reserved by another active order', NEW.laptop_id
        USING ERRCODE = '23505';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS prevent_laptop_double_reservation_trigger ON orders;
CREATE TRIGGER prevent_laptop_double_reservation_trigger
  BEFORE INSERT OR UPDATE OF laptop_id, order_status, payment_status, is_active ON orders
  FOR EACH ROW EXECUTE FUNCTION public.prevent_laptop_double_reservation();

-- Only the authenticated user can read their own profile in the browser. All
-- operational reads/writes are performed through authorized server handlers.
DROP POLICY IF EXISTS "Cho phép đọc user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "Chỉ ADMIN được cập nhật user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "Chỉ ADMIN được xóa user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "Chỉ ADMIN được tạo user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "User chỉ đọc profile của chính mình" ON user_profiles;
CREATE POLICY "User chỉ đọc profile của chính mình"
  ON user_profiles FOR SELECT USING (id = auth.uid());

DROP POLICY IF EXISTS "Cho phép đọc settings" ON app_settings;
DROP POLICY IF EXISTS "Cho phép ghi settings" ON app_settings;
DROP POLICY IF EXISTS "Cho phép cập nhật settings" ON app_settings;
DROP POLICY IF EXISTS "Cho phép đọc options" ON app_options;
DROP POLICY IF EXISTS "Cho phép ghi options" ON app_options;
DROP POLICY IF EXISTS "Cho phép cập nhật options" ON app_options;
DROP POLICY IF EXISTS "Cho phép xóa options" ON app_options;
DROP POLICY IF EXISTS "Cho phép đọc khách hàng" ON customers;
DROP POLICY IF EXISTS "Cho phép ghi khách hàng" ON customers;
DROP POLICY IF EXISTS "Cho phép cập nhật khách hàng" ON customers;
DROP POLICY IF EXISTS "Cho phép đọc laptops" ON laptops;
DROP POLICY IF EXISTS "Cho phép ghi laptops" ON laptops;
DROP POLICY IF EXISTS "Cho phép cập nhật laptops" ON laptops;
DROP POLICY IF EXISTS "Cho phép đọc orders" ON orders;
DROP POLICY IF EXISTS "Cho phép ghi orders" ON orders;
DROP POLICY IF EXISTS "Cho phép cập nhật orders" ON orders;
DROP POLICY IF EXISTS "Cho phép đọc bảo hành" ON warranty_cases;
DROP POLICY IF EXISTS "Cho phép ghi bảo hành" ON warranty_cases;
DROP POLICY IF EXISTS "Cho phép cập nhật bảo hành" ON warranty_cases;
DROP POLICY IF EXISTS "Cho phép đọc lịch sử kho" ON stock_movements;
DROP POLICY IF EXISTS "Cho phép ghi lịch sử kho" ON stock_movements;

ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON SCHEMA public FROM anon, authenticated;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON user_profiles TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO service_role;

COMMIT;
