-- Phase 2 — Logistics only: shipments and receiving. No QC workflow.
BEGIN;

ALTER TABLE public.laptops ADD COLUMN IF NOT EXISTS purchase_item_id bigint;
CREATE UNIQUE INDEX IF NOT EXISTS laptops_purchase_item_unique ON public.laptops(purchase_item_id) WHERE purchase_item_id IS NOT NULL;
DO $$ BEGIN
  IF NOT EXISTS(SELECT 1 FROM pg_constraint WHERE conname='laptops_purchase_item_fk') THEN
    ALTER TABLE public.laptops ADD CONSTRAINT laptops_purchase_item_fk FOREIGN KEY(purchase_item_id) REFERENCES public.purchase_items(id) ON DELETE RESTRICT;
  END IF;
END $$;

ALTER TABLE public.stock_movements ADD COLUMN IF NOT EXISTS reference_type text;
ALTER TABLE public.stock_movements ADD COLUMN IF NOT EXISTS reference_id text;

CREATE TABLE IF NOT EXISTS public.shipments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipment_code text NOT NULL UNIQUE,
  origin_location text NOT NULL CHECK(length(btrim(origin_location)) BETWEEN 1 AND 160),
  destination_location text NOT NULL CHECK(length(btrim(destination_location)) BETWEEN 1 AND 160),
  carrier text NOT NULL DEFAULT '',
  tracking_number text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','READY','IN_TRANSIT','AT_CHINA_WAREHOUSE','IN_TRANSIT_VN','PARTIALLY_RECEIVED','RECEIVED','DELAYED','CANCELLED')),
  shipped_at timestamptz,
  expected_arrival_at timestamptz,
  received_at timestamptz,
  shipping_cost_rmb numeric(14,2) NOT NULL DEFAULT 0 CHECK(shipping_cost_rmb>=0),
  shipping_cost_vnd numeric(18,2) NOT NULL DEFAULT 0 CHECK(shipping_cost_vnd>=0),
  notes text NOT NULL DEFAULT '',
  idempotency_key text UNIQUE,
  created_by text NOT NULL,
  updated_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);

CREATE TABLE IF NOT EXISTS public.shipment_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipment_id bigint NOT NULL REFERENCES public.shipments(id) ON DELETE CASCADE,
  purchase_item_id bigint NOT NULL REFERENCES public.purchase_items(id) ON DELETE RESTRICT,
  laptop_id bigint REFERENCES public.laptops(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'ASSIGNED' CHECK(status IN ('ASSIGNED','IN_TRANSIT','RECEIVED','CANCELLED')),
  received_at timestamptz,
  notes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
  UNIQUE(shipment_id,purchase_item_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS shipment_items_active_purchase_unique ON public.shipment_items(purchase_item_id) WHERE status<>'CANCELLED';
CREATE INDEX IF NOT EXISTS shipments_tracking_idx ON public.shipments(lower(tracking_number)) WHERE btrim(tracking_number)<>'';
CREATE INDEX IF NOT EXISTS shipment_items_shipment_idx ON public.shipment_items(shipment_id,status,id);

CREATE TABLE IF NOT EXISTS public.receiving_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipment_id bigint NOT NULL REFERENCES public.shipments(id) ON DELETE RESTRICT,
  received_by text NOT NULL,
  received_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
  expected_quantity integer NOT NULL CHECK(expected_quantity>=0),
  received_quantity integer NOT NULL CHECK(received_quantity>=0 AND received_quantity<=expected_quantity),
  notes text NOT NULL DEFAULT '',
  idempotency_key text NOT NULL UNIQUE CHECK(length(btrim(idempotency_key)) BETWEEN 8 AND 100),
  created_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);

CREATE TABLE IF NOT EXISTS public.receiving_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receiving_session_id bigint NOT NULL REFERENCES public.receiving_sessions(id) ON DELETE CASCADE,
  shipment_item_id bigint NOT NULL REFERENCES public.shipment_items(id) ON DELETE RESTRICT,
  purchase_item_id bigint NOT NULL REFERENCES public.purchase_items(id) ON DELETE RESTRICT,
  laptop_id bigint REFERENCES public.laptops(id) ON DELETE RESTRICT,
  expected_serial text,
  actual_serial text,
  expected_model text NOT NULL,
  actual_model text NOT NULL,
  physical_condition text NOT NULL DEFAULT '',
  charger_present boolean,
  result text NOT NULL CHECK(result IN ('RECEIVED','MISSING')),
  created_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
  UNIQUE(receiving_session_id,purchase_item_id)
);

CREATE TABLE IF NOT EXISTS public.receiving_exceptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  receiving_session_id bigint NOT NULL REFERENCES public.receiving_sessions(id) ON DELETE CASCADE,
  shipment_id bigint NOT NULL REFERENCES public.shipments(id) ON DELETE RESTRICT,
  purchase_item_id bigint REFERENCES public.purchase_items(id) ON DELETE RESTRICT,
  type text NOT NULL CHECK(type IN ('MISSING_ITEM','WRONG_SERIAL','WRONG_MODEL','DAMAGED_PACKAGE','MISSING_CHARGER','UNEXPECTED_ITEM','OTHER')),
  expected_value text NOT NULL DEFAULT '',
  actual_value text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','RESOLVED','IGNORED')),
  resolved_by text,
  resolved_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
CREATE INDEX IF NOT EXISTS receiving_sessions_shipment_idx ON public.receiving_sessions(shipment_id,received_at,id);
CREATE INDEX IF NOT EXISTS receiving_exceptions_shipment_idx ON public.receiving_exceptions(shipment_id,status,id);

DROP VIEW IF EXISTS public.shipment_summaries;
CREATE VIEW public.shipment_summaries AS
SELECT s.*,coalesce(x.quantity,0)::bigint quantity,coalesce(x.received_quantity,0)::bigint received_quantity,
  coalesce(x.purchase_batch_count,0)::bigint purchase_batch_count
FROM shipments s LEFT JOIN (
  SELECT si.shipment_id,count(*) FILTER(WHERE si.status<>'CANCELLED') quantity,count(*) FILTER(WHERE si.status='RECEIVED') received_quantity,
    count(DISTINCT pi.purchase_batch_id) purchase_batch_count
  FROM shipment_items si JOIN purchase_items pi ON pi.id=si.purchase_item_id GROUP BY si.shipment_id
) x ON x.shipment_id=s.id;

CREATE OR REPLACE FUNCTION public.next_shipment_code(p_date date DEFAULT current_date)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE prefix text:='SH-'||to_char(p_date,'YYYYMMDD')||'-'; n integer;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(prefix));
  SELECT coalesce(max(right(shipment_code,3)::integer),0)+1 INTO n FROM shipments WHERE shipment_code LIKE prefix||'%';
  RETURN prefix||lpad(n::text,3,'0');
END $$;

CREATE OR REPLACE FUNCTION public.create_shipment(p_shipment jsonb,p_purchase_item_ids jsonb,p_actor text,p_idempotency_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE s shipments%ROWTYPE; item_id bigint; requested_count integer;
BEGIN
  SELECT * INTO s FROM shipments WHERE idempotency_key=p_idempotency_key;
  IF FOUND THEN RETURN to_jsonb(s); END IF;
  IF length(btrim(coalesce(p_idempotency_key,''))) NOT BETWEEN 8 AND 100 THEN RAISE EXCEPTION 'Idempotency key không hợp lệ'; END IF;
  IF jsonb_typeof(p_purchase_item_ids)<>'array' OR jsonb_array_length(p_purchase_item_ids)=0 OR jsonb_array_length(p_purchase_item_ids)>500 THEN RAISE EXCEPTION 'Shipment phải có từ 1 đến 500 sản phẩm'; END IF;
  SELECT count(DISTINCT value::bigint) INTO requested_count FROM jsonb_array_elements_text(p_purchase_item_ids);
  IF requested_count<>jsonb_array_length(p_purchase_item_ids) THEN RAISE EXCEPTION 'Danh sách sản phẩm bị trùng'; END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements_text(p_purchase_item_ids) j LEFT JOIN purchase_items pi ON pi.id=j.value::bigint LEFT JOIN purchase_batches pb ON pb.id=pi.purchase_batch_id WHERE pi.id IS NULL OR pi.status='CANCELLED' OR pb.status IN ('DRAFT','CANCELLED')) THEN RAISE EXCEPTION 'Sản phẩm chưa xác nhận hoặc không hợp lệ'; END IF;
  IF EXISTS(SELECT 1 FROM shipment_items si WHERE si.purchase_item_id IN(SELECT value::bigint FROM jsonb_array_elements_text(p_purchase_item_ids)) AND si.status<>'CANCELLED') THEN RAISE EXCEPTION 'Sản phẩm đang thuộc shipment khác'; END IF;
  INSERT INTO shipments(shipment_code,origin_location,destination_location,carrier,tracking_number,expected_arrival_at,shipping_cost_rmb,shipping_cost_vnd,notes,idempotency_key,created_by,updated_by)
  VALUES(next_shipment_code(),btrim(p_shipment->>'origin_location'),btrim(p_shipment->>'destination_location'),left(coalesce(p_shipment->>'carrier',''),160),left(coalesce(p_shipment->>'tracking_number',''),200),nullif(p_shipment->>'expected_arrival_at','')::timestamptz,coalesce((p_shipment->>'shipping_cost_rmb')::numeric,0),coalesce((p_shipment->>'shipping_cost_vnd')::numeric,0),left(coalesce(p_shipment->>'notes',''),3000),p_idempotency_key,p_actor,p_actor) RETURNING * INTO s;
  FOR item_id IN SELECT value::bigint FROM jsonb_array_elements_text(p_purchase_item_ids) LOOP INSERT INTO shipment_items(shipment_id,purchase_item_id) VALUES(s.id,item_id); END LOOP;
  INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('SHIPMENT',s.id::text,'CREATE',jsonb_build_object('shipment_code',s.shipment_code,'item_count',requested_count),p_actor);
  RETURN to_jsonb(s);
EXCEPTION WHEN unique_violation THEN
  SELECT * INTO s FROM shipments WHERE idempotency_key=p_idempotency_key;
  IF FOUND THEN RETURN to_jsonb(s); END IF; RAISE;
END $$;

CREATE OR REPLACE FUNCTION public.transition_shipment(p_shipment_id bigint,p_target text,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE s shipments%ROWTYPE;
BEGIN
  SELECT * INTO s FROM shipments WHERE id=p_shipment_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy shipment'; END IF;
  IF NOT ((s.status='DRAFT' AND p_target IN('READY','CANCELLED')) OR (s.status='READY' AND p_target IN('IN_TRANSIT','CANCELLED')) OR
    (s.status='IN_TRANSIT' AND p_target IN('AT_CHINA_WAREHOUSE','IN_TRANSIT_VN','DELAYED')) OR
    (s.status='AT_CHINA_WAREHOUSE' AND p_target IN('IN_TRANSIT_VN','DELAYED')) OR
    (s.status='DELAYED' AND p_target IN('IN_TRANSIT','AT_CHINA_WAREHOUSE','IN_TRANSIT_VN'))) THEN RAISE EXCEPTION 'Chuyển trạng thái shipment không hợp lệ'; END IF;
  IF p_target='CANCELLED' AND EXISTS(SELECT 1 FROM shipment_items WHERE shipment_id=s.id AND status='RECEIVED') THEN RAISE EXCEPTION 'Shipment đã nhận hàng, không thể hủy'; END IF;
  UPDATE shipments SET status=p_target,shipped_at=CASE WHEN p_target='IN_TRANSIT' THEN coalesce(shipped_at,timezone('utc',now())) ELSE shipped_at END,updated_by=p_actor WHERE id=s.id RETURNING * INTO s;
  UPDATE shipment_items SET status=CASE WHEN p_target='CANCELLED' THEN 'CANCELLED' WHEN p_target IN('IN_TRANSIT','AT_CHINA_WAREHOUSE','IN_TRANSIT_VN') THEN 'IN_TRANSIT' ELSE status END WHERE shipment_id=s.id AND status<>'RECEIVED';
  INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('SHIPMENT',s.id::text,'UPDATE',jsonb_build_object('status',p_target),p_actor);
  RETURN to_jsonb(s);
END $$;

CREATE OR REPLACE FUNCTION public.receive_shipment_items(p_shipment_id bigint,p_items jsonb,p_exceptions jsonb,p_notes text,p_actor text,p_idempotency_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE s shipments%ROWTYPE; session receiving_sessions%ROWTYPE; entry jsonb; extra jsonb; si shipment_items%ROWTYPE; pi purchase_items%ROWTYPE; pb purchase_batches%ROWTYPE; laptop laptops%ROWTYPE;
 expected_qty integer; received_now integer:=0; received_total integer; active_total integer; actual_serial text; actual_model text; is_received boolean;
BEGIN
  SELECT * INTO session FROM receiving_sessions WHERE idempotency_key=p_idempotency_key;
  IF FOUND THEN RETURN to_jsonb(session); END IF;
  IF length(btrim(coalesce(p_idempotency_key,''))) NOT BETWEEN 8 AND 100 THEN RAISE EXCEPTION 'Idempotency key không hợp lệ'; END IF;
  IF jsonb_typeof(p_items)<>'array' OR jsonb_array_length(p_items)=0 OR jsonb_array_length(p_items)>500 THEN RAISE EXCEPTION 'Danh sách nhận hàng không hợp lệ'; END IF;
  SELECT * INTO s FROM shipments WHERE id=p_shipment_id FOR UPDATE;
  IF NOT FOUND OR s.status NOT IN('IN_TRANSIT_VN','PARTIALLY_RECEIVED','DELAYED') THEN RAISE EXCEPTION 'Shipment chưa ở trạng thái có thể nhận tại Việt Nam'; END IF;
  expected_qty:=jsonb_array_length(p_items);
  INSERT INTO receiving_sessions(shipment_id,received_by,expected_quantity,received_quantity,notes,idempotency_key) VALUES(s.id,p_actor,expected_qty,0,left(coalesce(p_notes,''),3000),p_idempotency_key) RETURNING * INTO session;
  FOR entry IN SELECT value FROM jsonb_array_elements(p_items) LOOP
    SELECT * INTO si FROM shipment_items WHERE shipment_id=s.id AND purchase_item_id=(entry->>'purchase_item_id')::bigint FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Purchase item không thuộc shipment'; END IF;
    SELECT * INTO pi FROM purchase_items WHERE id=si.purchase_item_id FOR UPDATE;
    is_received:=coalesce((entry->>'received')::boolean,false);
    actual_serial:=nullif(btrim(coalesce(entry->>'actual_serial',pi.serial,'')),''); actual_model:=btrim(coalesce(nullif(entry->>'actual_model',''),pi.model));
    IF is_received THEN
      IF si.status='RECEIVED' THEN RAISE EXCEPTION 'Sản phẩm đã được nhận trước đó'; END IF;
      SELECT * INTO pb FROM purchase_batches WHERE id=pi.purchase_batch_id;
      IF actual_serial IS NOT NULL AND EXISTS(SELECT 1 FROM laptops WHERE lower(btrim(serial))=lower(actual_serial) AND id IS DISTINCT FROM pi.laptop_id) THEN RAISE EXCEPTION 'Serial đã tồn tại trong kho'; END IF;
      IF pi.laptop_id IS NULL THEN
        INSERT INTO laptops(serial,name,category,location,charger_status,status,price_rmb,exchange_rate,import_price_vnd,condition_note,is_locked,is_active,purchase_item_id,import_date,warehouse_date)
        VALUES(actual_serial,concat_ws(' ',nullif(pi.brand,''),pi.model),pi.model,s.destination_location,CASE WHEN (entry->>'charger_present')::boolean THEN 'Có sạc' ELSE 'Chưa xác nhận' END,'waiting_qc',pi.purchase_price_rmb,pb.exchange_rate,round(pi.purchase_price_rmb*pb.exchange_rate,2),left(coalesce(entry->>'physical_condition',''),2000),true,true,pi.id,current_date,current_date) RETURNING * INTO laptop;
        UPDATE purchase_items SET laptop_id=laptop.id,serial=coalesce(actual_serial,serial),status='RECEIVED' WHERE id=pi.id;
      ELSE SELECT * INTO laptop FROM laptops WHERE id=pi.laptop_id FOR UPDATE; UPDATE laptops SET serial=coalesce(actual_serial,serial),location=s.destination_location,status='waiting_qc',is_locked=true WHERE id=laptop.id RETURNING * INTO laptop; END IF;
      UPDATE shipment_items SET status='RECEIVED',received_at=timezone('utc',now()),laptop_id=laptop.id WHERE id=si.id;
      INSERT INTO receiving_items(receiving_session_id,shipment_item_id,purchase_item_id,laptop_id,expected_serial,actual_serial,expected_model,actual_model,physical_condition,charger_present,result)
      VALUES(session.id,si.id,pi.id,laptop.id,pi.serial,actual_serial,pi.model,actual_model,left(coalesce(entry->>'physical_condition',''),1000),(entry->>'charger_present')::boolean,'RECEIVED');
      INSERT INTO stock_movements(laptop_id,movement_type,from_location,to_location,note,performed_by,reference_type,reference_id) VALUES(laptop.id,'PURCHASE_RECEIVE','IN_TRANSIT_VN',s.destination_location,'Nhận từ shipment '||s.shipment_code,p_actor,'RECEIVING_SESSION',session.id::text);
      IF pi.serial IS NOT NULL AND actual_serial IS DISTINCT FROM pi.serial THEN INSERT INTO receiving_exceptions(receiving_session_id,shipment_id,purchase_item_id,type,expected_value,actual_value,description) VALUES(session.id,s.id,pi.id,'WRONG_SERIAL',pi.serial,coalesce(actual_serial,''),'Serial thực tế khác serial dự kiến'); END IF;
      IF lower(actual_model)<>lower(pi.model) THEN INSERT INTO receiving_exceptions(receiving_session_id,shipment_id,purchase_item_id,type,expected_value,actual_value,description) VALUES(session.id,s.id,pi.id,'WRONG_MODEL',pi.model,actual_model,'Model thực tế khác model dự kiến'); END IF;
      IF coalesce((entry->>'charger_present')::boolean,false)=false THEN INSERT INTO receiving_exceptions(receiving_session_id,shipment_id,purchase_item_id,type,description) VALUES(session.id,s.id,pi.id,'MISSING_CHARGER','Không có sạc khi nhận'); END IF;
      received_now:=received_now+1;
      INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('LAPTOP',laptop.id::text,'CREATE',jsonb_build_object('purchase_item_id',pi.id,'status','waiting_qc','location',s.destination_location),p_actor);
    ELSE
      INSERT INTO receiving_items(receiving_session_id,shipment_item_id,purchase_item_id,expected_serial,expected_model,actual_model,result) VALUES(session.id,si.id,pi.id,pi.serial,pi.model,pi.model,'MISSING');
      INSERT INTO receiving_exceptions(receiving_session_id,shipment_id,purchase_item_id,type,expected_value,description) VALUES(session.id,s.id,pi.id,'MISSING_ITEM',coalesce(pi.serial,pi.model),'Không tìm thấy sản phẩm trong lần nhận này');
    END IF;
  END LOOP;
  IF jsonb_typeof(coalesce(p_exceptions,'[]'::jsonb))='array' THEN FOR extra IN SELECT value FROM jsonb_array_elements(coalesce(p_exceptions,'[]'::jsonb)) LOOP
    INSERT INTO receiving_exceptions(receiving_session_id,shipment_id,purchase_item_id,type,expected_value,actual_value,description) VALUES(session.id,s.id,nullif(extra->>'purchase_item_id','')::bigint,extra->>'type',left(coalesce(extra->>'expected_value',''),500),left(coalesce(extra->>'actual_value',''),500),left(coalesce(extra->>'description',''),2000));
  END LOOP; END IF;
  UPDATE receiving_sessions SET received_quantity=received_now WHERE id=session.id RETURNING * INTO session;
  SELECT count(*) FILTER(WHERE status='RECEIVED'),count(*) FILTER(WHERE status<>'CANCELLED') INTO received_total,active_total FROM shipment_items WHERE shipment_id=s.id;
  UPDATE shipments SET status=CASE WHEN received_total=active_total THEN 'RECEIVED' ELSE 'PARTIALLY_RECEIVED' END,received_at=CASE WHEN received_total=active_total THEN timezone('utc',now()) ELSE received_at END,updated_by=p_actor WHERE id=s.id;
  UPDATE purchase_batches pb2 SET status=CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_items p2 WHERE p2.purchase_batch_id=pb2.id AND p2.status<>'RECEIVED' AND p2.status<>'CANCELLED') THEN 'RECEIVED' ELSE 'PARTIALLY_RECEIVED' END,updated_by=p_actor WHERE pb2.id IN(SELECT DISTINCT p3.purchase_batch_id FROM purchase_items p3 JOIN shipment_items sx ON sx.purchase_item_id=p3.id WHERE sx.shipment_id=s.id);
  INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('RECEIVING_SESSION',session.id::text,'CREATE',jsonb_build_object('shipment_id',s.id,'received_quantity',received_now,'expected_quantity',expected_qty),p_actor);
  RETURN to_jsonb(session);
EXCEPTION WHEN unique_violation THEN
  SELECT * INTO session FROM receiving_sessions WHERE idempotency_key=p_idempotency_key;
  IF FOUND THEN RETURN to_jsonb(session); END IF; RAISE;
END $$;

CREATE OR REPLACE FUNCTION public.resolve_receiving_exception(p_exception_id bigint,p_status text,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE e receiving_exceptions%ROWTYPE;
BEGIN
  IF p_status NOT IN('RESOLVED','IGNORED') THEN RAISE EXCEPTION 'Trạng thái xử lý không hợp lệ'; END IF;
  UPDATE receiving_exceptions SET status=p_status,resolved_by=p_actor,resolved_at=timezone('utc',now()) WHERE id=p_exception_id AND status='OPEN' RETURNING * INTO e;
  IF NOT FOUND THEN RAISE EXCEPTION 'Exception không tồn tại hoặc đã xử lý'; END IF;
  INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('RECEIVING_EXCEPTION',e.id::text,'UPDATE',jsonb_build_object('status',p_status),p_actor);
  RETURN to_jsonb(e);
END $$;

DROP TRIGGER IF EXISTS shipments_set_updated_at_trigger ON public.shipments;
CREATE TRIGGER shipments_set_updated_at_trigger BEFORE UPDATE ON public.shipments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS shipment_items_set_updated_at_trigger ON public.shipment_items;
CREATE TRIGGER shipment_items_set_updated_at_trigger BEFORE UPDATE ON public.shipment_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.shipments ENABLE ROW LEVEL SECURITY; ALTER TABLE public.shipment_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.receiving_sessions ENABLE ROW LEVEL SECURITY; ALTER TABLE public.receiving_items ENABLE ROW LEVEL SECURITY; ALTER TABLE public.receiving_exceptions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.shipments,public.shipment_items,public.receiving_sessions,public.receiving_items,public.receiving_exceptions,public.shipment_summaries FROM PUBLIC,anon,authenticated;
GRANT ALL ON public.shipments,public.shipment_items,public.receiving_sessions,public.receiving_items,public.receiving_exceptions TO service_role;
GRANT SELECT ON public.shipment_summaries TO service_role;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
REVOKE ALL ON FUNCTION public.next_shipment_code(date),public.create_shipment(jsonb,jsonb,text,text),public.transition_shipment(bigint,text,text),public.receive_shipment_items(bigint,jsonb,jsonb,text,text,text),public.resolve_receiving_exception(bigint,text,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_shipment(jsonb,jsonb,text,text),public.transition_shipment(bigint,text,text),public.receive_shipment_items(bigint,jsonb,jsonb,text,text,text),public.resolve_receiving_exception(bigint,text,text) TO service_role;
COMMIT;
