-- Phase 1 — Procurement. Additive only; run after 20260919_invoices_accessories.sql.
BEGIN;

CREATE TABLE IF NOT EXISTS public.suppliers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE CHECK (code ~ '^[A-Z0-9_-]{2,40}$'),
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 200),
  display_name text NOT NULL DEFAULT '',
  wechat_name text NOT NULL DEFAULT '',
  wechat_id text NOT NULL DEFAULT '',
  phone text NOT NULL DEFAULT '',
  country text NOT NULL DEFAULT 'Trung Quốc',
  province text NOT NULL DEFAULT '',
  city text NOT NULL DEFAULT '',
  address text NOT NULL DEFAULT '',
  bank_name text NOT NULL DEFAULT '',
  bank_account_name text NOT NULL DEFAULT '',
  bank_account_number text NOT NULL DEFAULT '',
  alipay_account text NOT NULL DEFAULT '',
  preferred_shipping_destination text NOT NULL DEFAULT 'OTHER'
    CHECK (preferred_shipping_destination IN ('YUNNAN','GUANGXI','OTHER')),
  notes text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.purchase_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_code text NOT NULL UNIQUE,
  supplier_id uuid NOT NULL REFERENCES public.suppliers(id) ON DELETE RESTRICT,
  purchase_date date NOT NULL,
  currency text NOT NULL DEFAULT 'CNY' CHECK (currency = 'CNY'),
  exchange_rate numeric(14,4) NOT NULL CHECK (exchange_rate > 0),
  subtotal_rmb numeric(14,2) NOT NULL DEFAULT 0 CHECK (subtotal_rmb >= 0),
  domestic_shipping_rmb numeric(14,2) NOT NULL DEFAULT 0 CHECK (domestic_shipping_rmb >= 0),
  other_cost_rmb numeric(14,2) NOT NULL DEFAULT 0 CHECK (other_cost_rmb >= 0),
  destination text NOT NULL DEFAULT 'OTHER' CHECK (destination IN ('YUNNAN','GUANGXI','OTHER')),
  status text NOT NULL DEFAULT 'DRAFT' CHECK (status IN (
    'DRAFT','CONFIRMED','PARTIALLY_PAID','PAID','IN_TRANSIT_CN','AT_CN_WAREHOUSE',
    'IN_TRANSIT_VN','RECEIVED','PARTIALLY_RECEIVED','CLOSED','CANCELLED'
  )),
  notes text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true,
  created_by text NOT NULL,
  updated_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.purchase_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_batch_id bigint NOT NULL REFERENCES public.purchase_batches(id) ON DELETE CASCADE,
  supplier_item_ref text NOT NULL DEFAULT '',
  brand text NOT NULL DEFAULT '',
  model text NOT NULL CHECK (length(btrim(model)) BETWEEN 1 AND 240),
  cpu text NOT NULL DEFAULT '', gpu text NOT NULL DEFAULT '', ram text NOT NULL DEFAULT '',
  ssd text NOT NULL DEFAULT '', screen text NOT NULL DEFAULT '',
  serial text, supplier_serial text,
  purchase_price_rmb numeric(14,2) NOT NULL CHECK (purchase_price_rmb >= 0),
  condition text NOT NULL DEFAULT '',
  notes text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'ORDERED' CHECK (status IN ('ORDERED','CONFIRMED','CANCELLED','RECEIVED')),
  laptop_id bigint UNIQUE REFERENCES public.laptops(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE UNIQUE INDEX IF NOT EXISTS purchase_items_serial_unique
  ON public.purchase_items(lower(serial)) WHERE serial IS NOT NULL AND btrim(serial) <> '';
CREATE INDEX IF NOT EXISTS purchase_batches_supplier_idx ON public.purchase_batches(supplier_id, purchase_date DESC);
CREATE INDEX IF NOT EXISTS purchase_items_batch_idx ON public.purchase_items(purchase_batch_id, id);

CREATE TABLE IF NOT EXISTS public.supplier_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id uuid NOT NULL REFERENCES public.suppliers(id) ON DELETE RESTRICT,
  purchase_batch_id bigint NOT NULL REFERENCES public.purchase_batches(id) ON DELETE RESTRICT,
  amount_rmb numeric(14,2) NOT NULL CHECK (amount_rmb > 0),
  amount_vnd numeric(18,2) NOT NULL CHECK (amount_vnd > 0),
  exchange_rate numeric(14,4) NOT NULL CHECK (exchange_rate > 0),
  payment_method text NOT NULL CHECK (payment_method IN ('WECHAT','ALIPAY','BANK_TRANSFER','CASH','OTHER')),
  reference text NOT NULL DEFAULT '',
  payment_date date NOT NULL,
  notes text NOT NULL DEFAULT '',
  recorded_by text NOT NULL,
  idempotency_key text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);
CREATE INDEX IF NOT EXISTS supplier_payments_batch_idx ON public.supplier_payments(purchase_batch_id, payment_date, id);

DROP VIEW IF EXISTS public.purchase_batch_summaries;
CREATE VIEW public.purchase_batch_summaries AS
SELECT b.*,
  (b.subtotal_rmb + b.domestic_shipping_rmb + b.other_cost_rmb)::numeric(14,2) AS total_rmb,
  coalesce(p.paid_rmb,0)::numeric(14,2) AS paid_rmb,
  greatest(b.subtotal_rmb + b.domestic_shipping_rmb + b.other_cost_rmb - coalesce(p.paid_rmb,0),0)::numeric(14,2) AS debt_rmb,
  coalesce(i.item_count,0)::bigint AS item_count,
  s.code AS supplier_code, s.name AS supplier_name
FROM public.purchase_batches b
JOIN public.suppliers s ON s.id=b.supplier_id
LEFT JOIN (SELECT purchase_batch_id,sum(amount_rmb) paid_rmb FROM public.supplier_payments GROUP BY purchase_batch_id) p ON p.purchase_batch_id=b.id
LEFT JOIN (SELECT purchase_batch_id,count(*) item_count FROM public.purchase_items WHERE status<>'CANCELLED' GROUP BY purchase_batch_id) i ON i.purchase_batch_id=b.id;

CREATE OR REPLACE FUNCTION public.next_purchase_batch_code(p_date date)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE prefix text := 'CN-' || to_char(p_date,'YYYYMMDD') || '-'; n integer;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(prefix));
  SELECT coalesce(max(right(batch_code,3)::integer),0)+1 INTO n FROM purchase_batches WHERE batch_code LIKE prefix || '%';
  RETURN prefix || lpad(n::text,3,'0');
END $$;

CREATE OR REPLACE FUNCTION public.create_purchase_batch(p_batch jsonb,p_items jsonb,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE b purchase_batches%ROWTYPE; item jsonb; computed_subtotal numeric := 0;
BEGIN
  IF jsonb_typeof(p_items)<>'array' OR jsonb_array_length(p_items)=0 OR jsonb_array_length(p_items)>200 THEN RAISE EXCEPTION 'Lô mua phải có từ 1 đến 200 sản phẩm'; END IF;
  IF NOT EXISTS(SELECT 1 FROM suppliers WHERE id=(p_batch->>'supplier_id')::uuid AND active) THEN RAISE EXCEPTION 'Nhà cung cấp không tồn tại hoặc đã ngừng sử dụng'; END IF;
  SELECT coalesce(sum((x->>'purchase_price_rmb')::numeric),0) INTO computed_subtotal FROM jsonb_array_elements(p_items) x;
  INSERT INTO purchase_batches(batch_code,supplier_id,purchase_date,exchange_rate,subtotal_rmb,domestic_shipping_rmb,other_cost_rmb,destination,notes,created_by,updated_by)
  VALUES(next_purchase_batch_code((p_batch->>'purchase_date')::date),(p_batch->>'supplier_id')::uuid,(p_batch->>'purchase_date')::date,
    (p_batch->>'exchange_rate')::numeric,computed_subtotal,coalesce((p_batch->>'domestic_shipping_rmb')::numeric,0),coalesce((p_batch->>'other_cost_rmb')::numeric,0),
    coalesce(nullif(p_batch->>'destination',''),'OTHER'),coalesce(p_batch->>'notes',''),p_actor,p_actor) RETURNING * INTO b;
  FOR item IN SELECT value FROM jsonb_array_elements(p_items) LOOP
    INSERT INTO purchase_items(purchase_batch_id,supplier_item_ref,brand,model,cpu,gpu,ram,ssd,screen,serial,supplier_serial,purchase_price_rmb,condition,notes)
    VALUES(b.id,coalesce(item->>'supplier_item_ref',''),coalesce(item->>'brand',''),btrim(item->>'model'),coalesce(item->>'cpu',''),coalesce(item->>'gpu',''),coalesce(item->>'ram',''),coalesce(item->>'ssd',''),coalesce(item->>'screen',''),nullif(btrim(item->>'serial'),''),nullif(btrim(item->>'supplier_serial'),''),(item->>'purchase_price_rmb')::numeric,coalesce(item->>'condition',''),coalesce(item->>'notes',''));
  END LOOP;
  RETURN to_jsonb(b);
END $$;

CREATE OR REPLACE FUNCTION public.update_purchase_draft(p_batch_id bigint,p_batch jsonb,p_items jsonb,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE b purchase_batches%ROWTYPE; item jsonb; computed_subtotal numeric := 0;
BEGIN
  SELECT * INTO b FROM purchase_batches WHERE id=p_batch_id FOR UPDATE;
  IF NOT FOUND OR b.status<>'DRAFT' THEN RAISE EXCEPTION 'Chỉ có thể sửa lô ở trạng thái nháp'; END IF;
  IF jsonb_typeof(p_items)<>'array' OR jsonb_array_length(p_items)=0 OR jsonb_array_length(p_items)>200 THEN RAISE EXCEPTION 'Lô mua phải có từ 1 đến 200 sản phẩm'; END IF;
  SELECT coalesce(sum((x->>'purchase_price_rmb')::numeric),0) INTO computed_subtotal FROM jsonb_array_elements(p_items) x;
  UPDATE purchase_batches SET supplier_id=(p_batch->>'supplier_id')::uuid,purchase_date=(p_batch->>'purchase_date')::date,exchange_rate=(p_batch->>'exchange_rate')::numeric,
    subtotal_rmb=computed_subtotal,domestic_shipping_rmb=coalesce((p_batch->>'domestic_shipping_rmb')::numeric,0),other_cost_rmb=coalesce((p_batch->>'other_cost_rmb')::numeric,0),
    destination=coalesce(nullif(p_batch->>'destination',''),'OTHER'),notes=coalesce(p_batch->>'notes',''),updated_by=p_actor WHERE id=p_batch_id RETURNING * INTO b;
  DELETE FROM purchase_items WHERE purchase_batch_id=p_batch_id;
  FOR item IN SELECT value FROM jsonb_array_elements(p_items) LOOP
    INSERT INTO purchase_items(purchase_batch_id,supplier_item_ref,brand,model,cpu,gpu,ram,ssd,screen,serial,supplier_serial,purchase_price_rmb,condition,notes)
    VALUES(b.id,coalesce(item->>'supplier_item_ref',''),coalesce(item->>'brand',''),btrim(item->>'model'),coalesce(item->>'cpu',''),coalesce(item->>'gpu',''),coalesce(item->>'ram',''),coalesce(item->>'ssd',''),coalesce(item->>'screen',''),nullif(btrim(item->>'serial'),''),nullif(btrim(item->>'supplier_serial'),''),(item->>'purchase_price_rmb')::numeric,coalesce(item->>'condition',''),coalesce(item->>'notes',''));
  END LOOP;
  RETURN to_jsonb(b);
END $$;

CREATE OR REPLACE FUNCTION public.transition_purchase_batch(p_batch_id bigint,p_target text,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE b purchase_batches%ROWTYPE;
BEGIN
  SELECT * INTO b FROM purchase_batches WHERE id=p_batch_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy lô mua'; END IF;
  IF NOT ((b.status='DRAFT' AND p_target IN ('CONFIRMED','CANCELLED')) OR (b.status='CONFIRMED' AND p_target='CANCELLED')) THEN RAISE EXCEPTION 'Chuyển trạng thái lô mua không hợp lệ'; END IF;
  IF p_target='CANCELLED' AND EXISTS(SELECT 1 FROM supplier_payments WHERE purchase_batch_id=b.id) THEN RAISE EXCEPTION 'Lô đã có thanh toán; cần lập giao dịch điều chỉnh thay vì hủy'; END IF;
  UPDATE purchase_batches SET status=p_target,active=(p_target<>'CANCELLED'),updated_by=p_actor WHERE id=b.id RETURNING * INTO b;
  IF p_target='CONFIRMED' THEN UPDATE purchase_items SET status='CONFIRMED' WHERE purchase_batch_id=b.id; END IF;
  IF p_target='CANCELLED' THEN UPDATE purchase_items SET status='CANCELLED' WHERE purchase_batch_id=b.id; END IF;
  RETURN to_jsonb(b);
END $$;

CREATE OR REPLACE FUNCTION public.record_supplier_payment(p_batch_id bigint,p_amount_rmb numeric,p_exchange_rate numeric,p_method text,p_reference text,p_date date,p_notes text,p_actor text,p_idempotency_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE b purchase_batches%ROWTYPE; paid numeric; total numeric; result supplier_payments%ROWTYPE;
BEGIN
  SELECT * INTO result FROM supplier_payments WHERE idempotency_key=p_idempotency_key;
  IF FOUND THEN RETURN to_jsonb(result); END IF;
  SELECT * INTO b FROM purchase_batches WHERE id=p_batch_id FOR UPDATE;
  IF NOT FOUND OR b.status IN ('DRAFT','CANCELLED','CLOSED') THEN RAISE EXCEPTION 'Lô chưa xác nhận hoặc không còn nhận thanh toán'; END IF;
  total := b.subtotal_rmb+b.domestic_shipping_rmb+b.other_cost_rmb;
  SELECT coalesce(sum(amount_rmb),0) INTO paid FROM supplier_payments WHERE purchase_batch_id=b.id;
  IF p_amount_rmb<=0 OR p_amount_rmb>total-paid THEN RAISE EXCEPTION 'Số tiền vượt công nợ còn lại'; END IF;
  INSERT INTO supplier_payments(supplier_id,purchase_batch_id,amount_rmb,amount_vnd,exchange_rate,payment_method,reference,payment_date,notes,recorded_by,idempotency_key)
  VALUES(b.supplier_id,b.id,p_amount_rmb,round(p_amount_rmb*p_exchange_rate,2),p_exchange_rate,p_method,coalesce(p_reference,''),p_date,coalesce(p_notes,''),p_actor,p_idempotency_key) RETURNING * INTO result;
  paid := paid+p_amount_rmb;
  UPDATE purchase_batches SET status=CASE WHEN paid>=total THEN 'PAID' ELSE 'PARTIALLY_PAID' END,updated_by=p_actor WHERE id=b.id;
  RETURN to_jsonb(result);
END $$;

DROP TRIGGER IF EXISTS suppliers_set_updated_at_trigger ON public.suppliers;
CREATE TRIGGER suppliers_set_updated_at_trigger BEFORE UPDATE ON public.suppliers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS purchase_batches_set_updated_at_trigger ON public.purchase_batches;
CREATE TRIGGER purchase_batches_set_updated_at_trigger BEFORE UPDATE ON public.purchase_batches FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS purchase_items_set_updated_at_trigger ON public.purchase_items;
CREATE TRIGGER purchase_items_set_updated_at_trigger BEFORE UPDATE ON public.purchase_items FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_payments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.suppliers,public.purchase_batches,public.purchase_items,public.supplier_payments FROM anon,authenticated;
REVOKE ALL ON public.purchase_batch_summaries FROM PUBLIC,anon,authenticated;
GRANT ALL ON public.suppliers,public.purchase_batches,public.purchase_items,public.supplier_payments TO service_role;
GRANT SELECT ON public.purchase_batch_summaries TO service_role;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
REVOKE ALL ON FUNCTION public.next_purchase_batch_code(date),public.create_purchase_batch(jsonb,jsonb,text),public.update_purchase_draft(bigint,jsonb,jsonb,text),public.transition_purchase_batch(bigint,text,text),public.record_supplier_payment(bigint,numeric,numeric,text,text,date,text,text,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_purchase_batch(jsonb,jsonb,text),public.update_purchase_draft(bigint,jsonb,jsonb,text),public.transition_purchase_batch(bigint,text,text),public.record_supplier_payment(bigint,numeric,numeric,text,text,date,text,text,text) TO service_role;
COMMIT;
