-- DEV ONLY: XÓA TRẮNG TOÀN BỘ CƠ SỞ DỮ LIỆU. KHÔNG CHẠY TRÊN DATABASE ĐANG CÓ DỮ LIỆU.
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO service_role;

-- CÀI ĐẶT MỞ RỘNG (EXTENSION) CHO UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================================
-- BẢNG: user_profiles (Quản lý User)
-- =========================================================================================
CREATE TABLE user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  role TEXT NOT NULL DEFAULT 'SALES',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc user_profiles" ON user_profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Chỉ ADMIN được cập nhật user_profiles" ON user_profiles FOR UPDATE USING (
  (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN'
);
CREATE POLICY "Chỉ ADMIN được xóa user_profiles" ON user_profiles FOR DELETE USING (
  (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN'
);
CREATE POLICY "Chỉ ADMIN được tạo user_profiles" ON user_profiles FOR INSERT WITH CHECK (
  (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN'
);

-- =========================================================================================
-- BẢNG: app_settings (Lưu cấu hình JSON)
-- =========================================================================================
CREATE TABLE app_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc settings" ON app_settings FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi settings" ON app_settings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật settings" ON app_settings FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: app_options (Danh mục cài đặt thả xuống)
-- =========================================================================================
CREATE TABLE app_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_key TEXT NOT NULL,
  option_key TEXT NOT NULL,
  label TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(group_key, option_key)
);
ALTER TABLE app_options ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc options" ON app_options FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi options" ON app_options FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật options" ON app_options FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép xóa options" ON app_options FOR DELETE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: customers (Khách hàng)
-- =========================================================================================
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc khách hàng" ON customers FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi khách hàng" ON customers FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật khách hàng" ON customers FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: laptops (Quản lý thiết bị/Sản phẩm)
-- =========================================================================================
CREATE TABLE laptops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial VARCHAR(100),
  name TEXT,
  category VARCHAR(100),
  import_date DATE,
  warehouse_date DATE,
  location VARCHAR(100),
  charger_status VARCHAR(100),
  status VARCHAR(100),
  price_rmb NUMERIC DEFAULT 0,
  shipping_rmb NUMERIC DEFAULT 0,
  exchange_rate NUMERIC DEFAULT 3550,
  import_price_vnd NUMERIC DEFAULT 0,
  tracking_code TEXT,
  customer_note TEXT,
  battery_health INTEGER DEFAULT 100,
  cycle_count INTEGER DEFAULT 0,
  warranty_supplier VARCHAR(100),
  is_locked BOOLEAN DEFAULT false,
  screen_status VARCHAR(100),
  camera_mic_status VARCHAR(100),
  mainboard_status VARCHAR(100),
  condition_note TEXT,
  seller VARCHAR(100),
  is_active BOOLEAN DEFAULT true,
  parts_history JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE laptops ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc laptops" ON laptops FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi laptops" ON laptops FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật laptops" ON laptops FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: orders (Quản lý Đơn hàng)
-- =========================================================================================
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_date DATE,
  sale_online VARCHAR(100),
  sale_offline VARCHAR(100),
  note TEXT,
  order_type VARCHAR(100),
  order_status VARCHAR(100),
  payment_status VARCHAR(100),
  payment_method VARCHAR(100),
  delivery_status VARCHAR(100),
  shipping_method VARCHAR(100),
  laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  sale_price NUMERIC DEFAULT 0,

  deposit_amount NUMERIC DEFAULT 0,
  deposit_note TEXT,
  cod_amount NUMERIC DEFAULT 0,
  amount_paid NUMERIC DEFAULT 0,
  debt_amount NUMERIC DEFAULT 0,
  credit_card_fee NUMERIC DEFAULT 0,
  profit_vnd NUMERIC DEFAULT 0,
  trade_in_laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  customer_info TEXT,
  customer_address TEXT,
  tracking_code TEXT,
  ship_date DATE,
  setup_note TEXT,
  warranty TEXT,
  gifts VARCHAR(100),
  laptop_locked BOOLEAN DEFAULT false,
  reservation_expires_at TIMESTAMP WITH TIME ZONE,
  cancel_reason TEXT,
  cancelled_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- PAYMENTS AND FINANCIAL RECORDS
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
  payment_type TEXT NOT NULL CHECK (payment_type IN ('deposit', 'balance', 'cod', 'refund', 'other')),
  amount NUMERIC NOT NULL CHECK (amount > 0),
  payment_method TEXT NOT NULL DEFAULT 'transfer_cash',
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  reference_code TEXT,
  note TEXT,
  recorded_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);
CREATE INDEX payments_order_date_idx ON payments (order_id, payment_date DESC, id DESC);
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

CREATE TABLE financial_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_type TEXT NOT NULL CHECK (record_type IN ('income', 'expense', 'refund', 'adjustment')),
  category TEXT NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  payment_id BIGINT REFERENCES payments(id) ON DELETE SET NULL,
  laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  occurred_on DATE NOT NULL DEFAULT CURRENT_DATE,
  payment_method TEXT,
  note TEXT,
  recorded_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);
CREATE INDEX financial_records_date_idx ON financial_records (occurred_on DESC, id DESC);
CREATE INDEX financial_records_order_idx ON financial_records (order_id, occurred_on DESC);
ALTER TABLE financial_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc orders" ON orders FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi orders" ON orders FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật orders" ON orders FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: warranty_cases (Bảo hành & Sửa chữa)
-- =========================================================================================
CREATE TABLE warranty_cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  reported_issue TEXT,
  status TEXT,
  received_date DATE,
  resolved_date DATE,
  repair_cost NUMERIC DEFAULT 0,
  parts_replaced TEXT,
  diagnosis TEXT,
  resolution TEXT,
  resolution_note TEXT,
  notes TEXT,
  customer_info TEXT,
  handled_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE warranty_cases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc bảo hành" ON warranty_cases FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi bảo hành" ON warranty_cases FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật bảo hành" ON warranty_cases FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: stock_movements (Lịch sử Kho)
-- =========================================================================================
CREATE TABLE stock_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  movement_type TEXT,
  from_location TEXT,
  to_location TEXT,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  warranty_case_id BIGINT REFERENCES warranty_cases(id) ON DELETE SET NULL,
  note TEXT,
  performed_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc lịch sử kho" ON stock_movements FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi lịch sử kho" ON stock_movements FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: activity_logs (Audit append-only)
-- =========================================================================================
CREATE TABLE activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
  changes JSONB,
  user_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
CREATE INDEX activity_logs_entity_created_at_idx ON activity_logs (entity_type, entity_id, created_at DESC);
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- =========================================================================================
-- RPC FUNCTIONS (Hàm bảo mật)
-- =========================================================================================

CREATE OR REPLACE FUNCTION deactivate_user(target_user_id UUID) RETURNS VOID AS $$
BEGIN
  IF (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN' THEN
    UPDATE user_profiles SET is_active = false WHERE id = target_user_id;
  ELSE
    RAISE EXCEPTION 'Access denied';
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION activate_user(target_user_id UUID) RETURNS VOID AS $$
BEGIN
  IF (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN' THEN
    UPDATE user_profiles SET is_active = true WHERE id = target_user_id;
  ELSE
    RAISE EXCEPTION 'Access denied';
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- =========================================================================================
-- CHÈN SEED DATA (Dữ liệu mẫu cho App Options)
-- =========================================================================================
INSERT INTO app_options (group_key, option_key, label, sort_order) VALUES
('laptopStatus', 'not_imported', 'Chưa nhập kho', 0),
('laptopStatus', 'available', 'Sẵn hàng (đã nhập kho)', 1),
('laptopStatus', 'deposited', 'Đã cọc (Giữ chỗ)', 2),
('laptopStatus', 'sold', 'Đã bán', 3),
('laptopStatus', 'returned_cn', 'Back lại TQ', 4),
('laptopStatus', 'repairing', 'Đang sửa chữa', 5),
('laptopStatus', 'skipped', 'Bỏ qua', 6),
('laptopLocation', 'store', 'CH', 0),
('laptopLocation', 'wh', 'KHO', 1),
('laptopLocation', 'wh_cn', 'KHO TQ', 2),
('laptopLocation', 'repair', 'Sửa chữa', 3),
('chargerStatus', 'with_charger', 'Có Sạc', 0),
('chargerStatus', 'no_charger', 'Không Sạc', 1),
('chargerStatus', 'shared_charger', 'Sạc Lô', 2),
('chargerStatus', 'unchecked', 'Chưa Check', 3),
('componentStatus', 'ok', 'OK', 0),
('componentStatus', 'error', 'Lỗi / Có vấn đề', 1),
('orderStatus', 'new', 'MỚI TẠO', 0),
('orderStatus', 'deposited', 'ĐÃ CỌC / GIỮ MÁY', 1),
('orderStatus', 'prepared', 'ĐÃ CHUẨN BỊ XONG', 2),
('orderStatus', 'shipping', 'ĐANG GIAO HÀNG', 3),
('orderStatus', 'done', 'HOÀN THÀNH', 4),
('orderStatus', 'returned', 'BACK MÁY', 5),
('orderStatus', 'cancelled', 'HỦY ĐƠN', 6),
('paymentStatus', 'unpaid', 'CHƯA THANH TOÁN', 0),
('paymentStatus', 'deposited', 'ĐÃ CỌC', 1),
('paymentStatus', 'cod', 'ĐANG CHỜ COD', 2),
('paymentStatus', 'paid', 'ĐÃ THANH TOÁN', 3),
('paymentStatus', 'refunded', 'ĐÃ HOÀN TIỀN', 4),
('deliveryStatus', 'preparing', 'ĐANG CHUẨN BỊ', 0),
('deliveryStatus', 'shipped', 'ĐÃ GỬI HÀNG', 1),
('deliveryStatus', 'delivered', 'ĐÃ GIAO HÀNG', 2),
('deliveryStatus', 'at_store', 'TẠI SHOP', 3),
('deliveryStatus', 'returned', 'HOÀN HÀNG', 4),
('orderType', 'retail', 'Bán lẻ (Retail)', 0),
('orderType', 'wholesale', 'Bán sỉ/Thợ (Wholesale)', 1),
('orderType', 'trade_in', 'Thu cũ đổi mới (Trade-in)', 2),
('paymentMethod', 'transfer_cash', 'Chuyển khoản / Tiền mặt', 0),
('paymentMethod', 'card', 'Quẹt thẻ (Tốn phí)', 1),
('paymentMethod', 'installment', 'Trả góp', 2),
('shippingMethod', 'viettelpost', 'ViettelPost', 0),
('shippingMethod', 'shopee_spx', 'Shopee SPX', 1),
('shippingMethod', 'direct_store', 'Trực tiếp Shop', 2),
('shippingMethod', 'hcm_agent', 'Nhờ HCM giao dịch', 3),
('shippingMethod', 'hai_an', 'Nhà xe Hải An', 4),
('shippingMethod', 'shared_car', 'Xe Ghép', 5),
('shippingMethod', 'direct_ship', 'Ship trực tiếp khách', 6),
('shippingMethod', 'bus', 'Xe khách', 7),
('giftOptions', 'basic_gift', 'quà cơ bản (balo + chuột)', 0),
('giftOptions', 'no_gift', 'ko quà', 1),
('giftOptions', 'mouse_only', 'chỉ tặng chuột', 2),
('giftOptions', 'bag_only', 'chỉ tặng balo', 3),
('category', '1', 'LEGION 5 2023', 0),
('category', '2', 'ROG G513 2022', 1),
('category', '3', 'ROG Scar 2022', 2),
('category', '4', 'ROG Zephyrus G14', 3),
('category', '5', 'LEGION 5 Pro 2022', 4),
('category', '6', 'LEGION 5 Pro 2023 - 2024', 5),
('category', '7', 'LEGION Slim 7', 6),
('category', '8', 'ASUS TUF Gaming', 7),
('category', '9', 'ROG M16 / G16', 8),
('category', '10', 'ACER Nitro 5', 9),
('saleOnline', '1', 'Thắng Tiktok', 0),
('saleOnline', '2', 'Thắng Zalo', 1),
('saleOnline', '3', 'Vương', 2),
('saleOnline', '4', 'Quế Anh', 3),
('saleOnline', '5', 'Quảng', 4),
('saleOnline', '6', 'Linh', 5),
('saleOnline', '7', 'Hoàng', 6),
('saleOnline', '8', 'Tuấn', 7),
('saleOnline', 'other', 'Khác', 8),
('seller', 'guangzhou', 'Guangzhou Tech', 0),
('seller', 'shenzhen', 'Shenzhen Digital', 1),
('seller', 'beijing', 'Beijing Digital', 2),
('seller', 'aming', 'Shop TQ A-Ming', 3),
('seller', 'xiao', 'Shop TQ Xiao', 4),
('warrantyCaseStatus', 'received', 'TIẾP NHẬN', 0),
('warrantyCaseStatus', 'checking', 'ĐANG KIỂM TRA', 1),
('warrantyCaseStatus', 'wait_parts', 'CHỜ LINH KIỆN', 2),
('warrantyCaseStatus', 'repairing', 'ĐANG SỬA', 3),
('warrantyCaseStatus', 'done', 'HOÀN TẤT', 4),
('warrantyCaseStatus', 'swap_device', 'ĐỔI MÁY', 5),
('warrantyCaseStatus', 'refunded', 'HOÀN TIỀN', 6);


-- =========================================================================================
-- CẤP QUYỀN TRUY CẬP CHO POSTGREST (BẮT BUỘC ĐỂ API HOẠT ĐỘNG)
-- =========================================================================================
-- Browser chỉ được đọc profile của chính mình để khôi phục session. Toàn bộ dữ liệu
-- nghiệp vụ phải đi qua Route Handler đã xác thực/ủy quyền ở server.
DROP POLICY IF EXISTS "Cho phép đọc user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "Chỉ ADMIN được cập nhật user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "Chỉ ADMIN được xóa user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "Chỉ ADMIN được tạo user_profiles" ON user_profiles;
CREATE POLICY "User chỉ đọc profile của chính mình" ON user_profiles FOR SELECT USING (id = auth.uid());

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON SCHEMA public FROM anon, authenticated;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON user_profiles TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.record_order_payment(
  p_order_id BIGINT,
  p_amount NUMERIC,
  p_payment_type TEXT,
  p_payment_method TEXT DEFAULT 'transfer_cash',
  p_payment_date DATE DEFAULT CURRENT_DATE,
  p_reference_code TEXT DEFAULT NULL,
  p_note TEXT DEFAULT NULL,
  p_recorded_by TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order orders%ROWTYPE;
  v_payment payments%ROWTYPE;
  v_financial financial_records%ROWTYPE;
  v_amount_paid NUMERIC;
  v_deposit_amount NUMERIC;
  v_debt_amount NUMERIC;
  v_payment_status TEXT;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Payment amount must be greater than zero';
  END IF;
  IF p_payment_type NOT IN ('deposit', 'balance', 'cod', 'refund', 'other') THEN
    RAISE EXCEPTION 'Unsupported payment type';
  END IF;

  SELECT * INTO v_order FROM orders WHERE id = p_order_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order % does not exist', p_order_id;
  END IF;
  IF v_order.is_active IS NOT TRUE THEN
    RAISE EXCEPTION 'Cannot record payment for an inactive order';
  END IF;

  IF p_payment_type = 'refund' THEN
    IF p_amount > COALESCE(v_order.amount_paid, 0) THEN
      RAISE EXCEPTION 'Refund cannot exceed amount already paid';
    END IF;
    v_amount_paid := GREATEST(COALESCE(v_order.amount_paid, 0) - p_amount, 0);
    v_deposit_amount := COALESCE(v_order.deposit_amount, 0);
  ELSE
    IF COALESCE(v_order.amount_paid, 0) + p_amount > COALESCE(v_order.sale_price, 0) THEN
      RAISE EXCEPTION 'Payment exceeds order sale price';
    END IF;
    v_amount_paid := COALESCE(v_order.amount_paid, 0) + p_amount;
    v_deposit_amount := COALESCE(v_order.deposit_amount, 0)
      + CASE WHEN p_payment_type = 'deposit' THEN p_amount ELSE 0 END;
  END IF;

  v_debt_amount := GREATEST(COALESCE(v_order.sale_price, 0) - v_amount_paid, 0);
  v_payment_status := CASE
    WHEN p_payment_type = 'refund' THEN 'refunded'
    WHEN v_debt_amount = 0 AND COALESCE(v_order.sale_price, 0) > 0 THEN 'paid'
    WHEN p_payment_type = 'cod' THEN 'cod'
    WHEN v_amount_paid > 0 THEN 'deposited'
    ELSE 'unpaid'
  END;

  INSERT INTO payments (
    order_id, payment_type, amount, payment_method, payment_date,
    reference_code, note, recorded_by
  ) VALUES (
    p_order_id, p_payment_type, p_amount, COALESCE(NULLIF(p_payment_method, ''), 'transfer_cash'),
    COALESCE(p_payment_date, CURRENT_DATE), p_reference_code, p_note, p_recorded_by
  ) RETURNING * INTO v_payment;

  INSERT INTO financial_records (
    record_type, category, amount, order_id, payment_id, occurred_on,
    payment_method, note, recorded_by
  ) VALUES (
    CASE WHEN p_payment_type = 'refund' THEN 'refund' ELSE 'income' END,
    p_payment_type,
    p_amount,
    p_order_id,
    v_payment.id,
    COALESCE(p_payment_date, CURRENT_DATE),
    COALESCE(NULLIF(p_payment_method, ''), 'transfer_cash'),
    p_note,
    p_recorded_by
  ) RETURNING * INTO v_financial;

  UPDATE orders
  SET amount_paid = v_amount_paid,
      deposit_amount = v_deposit_amount,
      debt_amount = v_debt_amount,
      payment_status = v_payment_status,
      updated_at = timezone('utc'::text, now())
  WHERE id = p_order_id
  RETURNING * INTO v_order;

  RETURN jsonb_build_object(
    'payment', to_jsonb(v_payment),
    'financial_record', to_jsonb(v_financial),
    'order', to_jsonb(v_order)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.record_order_payment(BIGINT, NUMERIC, TEXT, TEXT, DATE, TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_order_payment(BIGINT, NUMERIC, TEXT, TEXT, DATE, TEXT, TEXT, TEXT)
  TO service_role;

CREATE OR REPLACE FUNCTION public.create_order_with_inventory(
  p_order JSONB,
  p_recorded_by TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order orders%ROWTYPE;
  v_laptop laptops%ROWTYPE;
BEGIN
  INSERT INTO orders (
    created_date, sale_online, sale_offline, note, order_type, order_status,
    payment_status, payment_method, delivery_status, shipping_method, laptop_id,
    sale_price, deposit_amount, deposit_note, cod_amount, amount_paid, debt_amount,
    credit_card_fee, profit_vnd, trade_in_laptop_id, customer_id, customer_info,
    customer_address, tracking_code, ship_date, setup_note, warranty, gifts,
    laptop_locked, reservation_expires_at, cancel_reason, cancelled_at, is_active,
    created_at, updated_at
  )
  SELECT
    x.created_date, x.sale_online, x.sale_offline, x.note, x.order_type, x.order_status,
    x.payment_status, x.payment_method, x.delivery_status, x.shipping_method, x.laptop_id,
    COALESCE(x.sale_price, 0), COALESCE(x.deposit_amount, 0), x.deposit_note, COALESCE(x.cod_amount, 0),
    COALESCE(x.amount_paid, 0), COALESCE(x.debt_amount, 0), COALESCE(x.credit_card_fee, 0),
    COALESCE(x.profit_vnd, 0), x.trade_in_laptop_id, x.customer_id, x.customer_info,
    x.customer_address, x.tracking_code, x.ship_date, x.setup_note, x.warranty, x.gifts,
    COALESCE(x.laptop_locked, false), x.reservation_expires_at, x.cancel_reason, x.cancelled_at,
    COALESCE(x.is_active, true), COALESCE(x.created_at, timezone('utc'::text, now())),
    COALESCE(x.updated_at, timezone('utc'::text, now()))
  FROM jsonb_to_record(p_order) AS x(
    created_date DATE, sale_online VARCHAR(100), sale_offline VARCHAR(100), note TEXT,
    order_type VARCHAR(100), order_status VARCHAR(100), payment_status VARCHAR(100),
    payment_method VARCHAR(100), delivery_status VARCHAR(100), shipping_method VARCHAR(100),
    laptop_id BIGINT, sale_price NUMERIC, deposit_amount NUMERIC, deposit_note TEXT,
    cod_amount NUMERIC, amount_paid NUMERIC, debt_amount NUMERIC, credit_card_fee NUMERIC,
    profit_vnd NUMERIC, trade_in_laptop_id BIGINT, customer_id BIGINT, customer_info TEXT,
    customer_address TEXT, tracking_code TEXT, ship_date DATE, setup_note TEXT, warranty TEXT,
    gifts VARCHAR(100), laptop_locked BOOLEAN, reservation_expires_at TIMESTAMP WITH TIME ZONE,
    cancel_reason TEXT, cancelled_at TIMESTAMP WITH TIME ZONE, is_active BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE, updated_at TIMESTAMP WITH TIME ZONE
  )
  RETURNING * INTO v_order;

  IF v_order.laptop_id IS NOT NULL
     AND v_order.is_active IS TRUE
     AND (v_order.order_status IN ('deposited', 'prepared', 'shipping', 'done') OR v_order.payment_status = 'deposited') THEN
    SELECT * INTO v_laptop FROM laptops WHERE id = v_order.laptop_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Laptop % does not exist', v_order.laptop_id; END IF;

    UPDATE laptops
    SET is_locked = true,
        status = CASE WHEN v_order.order_status = 'done' THEN 'sold' ELSE 'deposited' END,
        updated_at = timezone('utc'::text, now())
    WHERE id = v_order.laptop_id
    RETURNING * INTO v_laptop;

    UPDATE orders
    SET laptop_locked = true,
        updated_at = timezone('utc'::text, now())
    WHERE id = v_order.id
    RETURNING * INTO v_order;

    INSERT INTO stock_movements (laptop_id, order_id, movement_type, note, performed_by)
    VALUES (v_order.laptop_id, v_order.id,
      CASE WHEN v_order.order_status = 'done' THEN 'SOLD' ELSE 'RESERVED' END,
      'Inventory updated by order transaction', p_recorded_by);
  END IF;

  RETURN jsonb_build_object(
    'order', to_jsonb(v_order),
    'laptop', CASE WHEN v_laptop.id IS NULL THEN NULL ELSE to_jsonb(v_laptop) END,
    'inventory_applied', true
  );
END;
$$;

REVOKE ALL ON FUNCTION public.create_order_with_inventory(JSONB, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_order_with_inventory(JSONB, TEXT)
  TO service_role;
