-- DEV ONLY: XÓA TRẮNG TOÀN BỘ CƠ SỞ DỮ LIỆU. KHÔNG CHẠY TRÊN DATABASE ĐANG CÓ DỮ LIỆU.
-- Includes month_key columns/indexes and order RPC support. Run reseed_data.sql
-- afterward for 34 laptops and 20 orders across 07/2026 and 08/2026.
BEGIN;

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO service_role;

-- =========================================================================================
-- BẢNG: user_profiles (Quản lý User)
-- =========================================================================================
CREATE TABLE user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  role TEXT NOT NULL DEFAULT 'SALES'
    CHECK (role IN ('ADMIN', 'SALES', 'TECH', 'TECHNICAL', 'STAFF')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc user_profiles" ON user_profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Chỉ ADMIN được cập nhật user_profiles" ON user_profiles FOR UPDATE USING (
  (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN'
);
CREATE POLICY "Chỉ ADMIN được xóa user_profiles" ON user_profiles FOR DELETE USING (
  (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN'
);
CREATE POLICY "Chỉ ADMIN được tạo user_profiles" ON user_profiles FOR INSERT WITH CHECK (
  (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN'
);

-- =========================================================================================
-- BẢNG: app_settings (Lưu cấu hình JSON)
-- =========================================================================================
CREATE TABLE app_settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc settings" ON app_settings FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi settings" ON app_settings FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật settings" ON app_settings FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: app_options (Danh mục cài đặt thả xuống)
-- =========================================================================================
CREATE TABLE app_options (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_key TEXT NOT NULL,
  option_key TEXT NOT NULL,
  label TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(group_key, option_key)
);
ALTER TABLE app_options ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc options" ON app_options FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi options" ON app_options FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật options" ON app_options FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép xóa options" ON app_options FOR DELETE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: customers (Khách hàng)
-- =========================================================================================
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  address TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc khách hàng" ON customers FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi khách hàng" ON customers FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật khách hàng" ON customers FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: laptops (Quản lý thiết bị/Sản phẩm)
-- =========================================================================================
CREATE TABLE laptops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  serial VARCHAR(100),
  name TEXT,
  category VARCHAR(100),
  import_date DATE,
  warehouse_date DATE,
  location VARCHAR(100),
  charger_status VARCHAR(100),
  status VARCHAR(100),
  price_rmb NUMERIC DEFAULT 0,
  shipping_rmb NUMERIC DEFAULT 0,
  exchange_rate NUMERIC DEFAULT 3550,
  import_price_vnd NUMERIC DEFAULT 0,
  wholesale_price_vnd NUMERIC DEFAULT 0,
  retail_price_vnd NUMERIC DEFAULT 0,
  tracking_code TEXT,
  customer_note TEXT,
  battery_health INTEGER DEFAULT 100,
  warranty_supplier TEXT,
  is_locked BOOLEAN DEFAULT false,
  screen_status VARCHAR(100),
  camera_mic_status VARCHAR(100),
  mainboard_status VARCHAR(100),
  condition_note TEXT,
  seller VARCHAR(100),
  is_active BOOLEAN DEFAULT true,
  parts_history JSONB DEFAULT '[]'::jsonb,
  month_key VARCHAR(10),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  CONSTRAINT laptops_non_negative_values CHECK (
    COALESCE(price_rmb, 0) >= 0
    AND COALESCE(shipping_rmb, 0) >= 0
    AND COALESCE(exchange_rate, 0) >= 0
    AND COALESCE(import_price_vnd, 0) >= 0
    AND COALESCE(wholesale_price_vnd, 0) >= 0
    AND COALESCE(retail_price_vnd, 0) >= 0
  ),
  CONSTRAINT laptops_battery_health_range CHECK (
    battery_health IS NULL OR battery_health BETWEEN 0 AND 100
  )
);
ALTER TABLE laptops ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX laptops_serial_unique_idx
  ON laptops (lower(btrim(serial)))
  WHERE serial IS NOT NULL AND btrim(serial) <> '';
CREATE POLICY "Cho phép đọc laptops" ON laptops FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi laptops" ON laptops FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật laptops" ON laptops FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: orders (Quản lý Đơn hàng)
-- =========================================================================================
CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_date DATE,
  sale_online VARCHAR(100),
  sale_offline VARCHAR(100),
  note TEXT,
  order_type VARCHAR(100),
  order_status VARCHAR(100),
  payment_status VARCHAR(100),
  payment_method VARCHAR(100),
  delivery_status VARCHAR(100),
  shipping_method VARCHAR(100),
  laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  requested_laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  sale_price NUMERIC DEFAULT 0,

  deposit_amount NUMERIC DEFAULT 0,
  deposit_note TEXT,
  cod_amount NUMERIC DEFAULT 0,
  amount_paid NUMERIC DEFAULT 0,
  debt_amount NUMERIC DEFAULT 0,
  credit_card_fee NUMERIC DEFAULT 0,
  profit_vnd NUMERIC DEFAULT 0,
  trade_in_laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  customer_info TEXT,
  customer_address TEXT,
  tracking_code TEXT,
  ship_date DATE,
  setup_note TEXT,
  warranty TEXT,
  gifts VARCHAR(100),
  laptop_locked BOOLEAN DEFAULT false,
  reservation_expires_at TIMESTAMP WITH TIME ZONE,
  cancel_reason TEXT,
  cancelled_at TIMESTAMP WITH TIME ZONE,
  month_key VARCHAR(10),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  CONSTRAINT orders_non_negative_values CHECK (
    COALESCE(sale_price, 0) >= 0
    AND COALESCE(deposit_amount, 0) >= 0
    AND COALESCE(cod_amount, 0) >= 0
    AND COALESCE(amount_paid, 0) >= 0
    AND COALESCE(debt_amount, 0) >= 0
    AND COALESCE(credit_card_fee, 0) >= 0
  ),
  CONSTRAINT orders_payment_totals_valid CHECK (
    COALESCE(amount_paid, 0) <= COALESCE(sale_price, 0)
    AND COALESCE(deposit_amount, 0) <= COALESCE(amount_paid, 0)
  )
);
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.order_uses_laptop(
  p_laptop_id BIGINT,
  p_is_active BOOLEAN,
  p_order_status TEXT,
  p_payment_status TEXT,
  p_reservation_expires_at TIMESTAMP WITH TIME ZONE
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    p_laptop_id IS NOT NULL
    AND p_is_active IS TRUE
    AND COALESCE(p_payment_status, '') <> 'refunded'
    AND COALESCE(p_order_status, '') NOT IN ('cancelled', 'returned')
    AND (
      p_order_status IN ('prepared', 'shipping', 'done')
      OR (
        (p_order_status = 'deposited' OR p_payment_status = 'deposited')
        AND (p_reservation_expires_at IS NULL OR p_reservation_expires_at > CURRENT_TIMESTAMP)
      )
    ),
    false
  );
$$;

CREATE OR REPLACE FUNCTION public.prevent_laptop_double_reservation()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.order_uses_laptop(
    NEW.laptop_id, NEW.is_active, NEW.order_status, NEW.payment_status, NEW.reservation_expires_at
  ) THEN
    RETURN NEW;
  END IF;

  PERFORM pg_advisory_xact_lock(NEW.laptop_id);
  IF EXISTS (
    SELECT 1
    FROM orders existing_order
    WHERE existing_order.laptop_id = NEW.laptop_id
      AND existing_order.id IS DISTINCT FROM NEW.id
      AND public.order_uses_laptop(
        existing_order.laptop_id,
        existing_order.is_active,
        existing_order.order_status,
        existing_order.payment_status,
        existing_order.reservation_expires_at
      )
  ) THEN
    RAISE EXCEPTION 'Laptop % is already reserved by another active order', NEW.laptop_id
      USING ERRCODE = '23505';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS prevent_laptop_double_reservation_trigger ON orders;
CREATE TRIGGER prevent_laptop_double_reservation_trigger
  BEFORE INSERT OR UPDATE OF laptop_id, order_status, payment_status, is_active ON orders
  FOR EACH ROW EXECUTE FUNCTION public.prevent_laptop_double_reservation();

-- PAYMENTS AND FINANCIAL RECORDS
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
  payment_type TEXT NOT NULL CHECK (payment_type IN ('deposit', 'balance', 'cod', 'refund', 'other')),
  amount NUMERIC NOT NULL CHECK (amount > 0),
  payment_method TEXT NOT NULL DEFAULT 'transfer_cash',
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  reference_code TEXT,
  note TEXT,
  recorded_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);
CREATE INDEX payments_order_date_idx ON payments (order_id, payment_date DESC, id DESC);
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

CREATE TABLE financial_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_type TEXT NOT NULL CHECK (record_type IN ('income', 'expense', 'refund', 'adjustment')),
  category TEXT NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  payment_id BIGINT REFERENCES payments(id) ON DELETE SET NULL,
  laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  occurred_on DATE NOT NULL DEFAULT CURRENT_DATE,
  payment_method TEXT,
  note TEXT,
  recorded_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);
CREATE INDEX financial_records_date_idx ON financial_records (occurred_on DESC, id DESC);
CREATE INDEX financial_records_order_idx ON financial_records (order_id, occurred_on DESC);
ALTER TABLE financial_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc orders" ON orders FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi orders" ON orders FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật orders" ON orders FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: warranty_cases (Bảo hành & Sửa chữa)
-- =========================================================================================
CREATE TABLE warranty_cases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  reported_issue TEXT,
  status TEXT,
  received_date DATE,
  resolved_date DATE,
  repair_cost NUMERIC DEFAULT 0,
  parts_replaced TEXT,
  diagnosis TEXT,
  resolution TEXT,
  resolution_note TEXT,
  notes TEXT,
  customer_info TEXT,
  handled_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  CONSTRAINT warranty_cases_repair_cost_non_negative CHECK (COALESCE(repair_cost, 0) >= 0)
);
ALTER TABLE warranty_cases ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc bảo hành" ON warranty_cases FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi bảo hành" ON warranty_cases FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Cho phép cập nhật bảo hành" ON warranty_cases FOR UPDATE USING (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: stock_movements (Lịch sử Kho)
-- =========================================================================================
CREATE TABLE stock_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  movement_type TEXT,
  from_location TEXT,
  to_location TEXT,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  warranty_case_id BIGINT REFERENCES warranty_cases(id) ON DELETE SET NULL,
  note TEXT,
  performed_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc lịch sử kho" ON stock_movements FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Cho phép ghi lịch sử kho" ON stock_movements FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- =========================================================================================
-- BẢNG: activity_logs (Audit append-only)
-- =========================================================================================
CREATE TABLE activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('CREATE', 'UPDATE', 'DELETE')),
  changes JSONB,
  user_name TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
CREATE INDEX activity_logs_entity_created_at_idx ON activity_logs (entity_type, entity_id, created_at DESC);
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

CREATE INDEX orders_laptop_active_idx ON orders (laptop_id, is_active, order_status, payment_status);
CREATE INDEX laptops_active_status_import_date_idx ON laptops (is_active, status, import_date DESC);
CREATE INDEX idx_laptops_month_key ON laptops (month_key);
CREATE INDEX idx_orders_month_key ON orders (month_key);
CREATE INDEX warranty_cases_laptop_created_at_idx ON warranty_cases (laptop_id, created_at DESC);
CREATE INDEX stock_movements_laptop_created_at_idx ON stock_movements (laptop_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.updated_at := timezone('utc'::text, now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS user_profiles_set_updated_at_trigger ON user_profiles;
CREATE TRIGGER user_profiles_set_updated_at_trigger
  BEFORE UPDATE ON user_profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS app_settings_set_updated_at_trigger ON app_settings;
CREATE TRIGGER app_settings_set_updated_at_trigger
  BEFORE UPDATE ON app_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS app_options_set_updated_at_trigger ON app_options;
CREATE TRIGGER app_options_set_updated_at_trigger
  BEFORE UPDATE ON app_options
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS customers_set_updated_at_trigger ON customers;
CREATE TRIGGER customers_set_updated_at_trigger
  BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS laptops_set_updated_at_trigger ON laptops;
CREATE TRIGGER laptops_set_updated_at_trigger
  BEFORE UPDATE ON laptops
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS orders_set_updated_at_trigger ON orders;
CREATE TRIGGER orders_set_updated_at_trigger
  BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS warranty_cases_set_updated_at_trigger ON warranty_cases;
CREATE TRIGGER warranty_cases_set_updated_at_trigger
  BEFORE UPDATE ON warranty_cases
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.prevent_activity_log_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION 'activity_logs is append-only';
END;
$$;

DROP TRIGGER IF EXISTS activity_logs_append_only_trigger ON activity_logs;
CREATE TRIGGER activity_logs_append_only_trigger
  BEFORE UPDATE OR DELETE ON activity_logs
  FOR EACH ROW EXECUTE FUNCTION public.prevent_activity_log_mutation();

-- =========================================================================================
-- RPC FUNCTIONS (Hàm bảo mật)
-- =========================================================================================

CREATE OR REPLACE FUNCTION deactivate_user(target_user_id UUID) RETURNS VOID AS $$
BEGIN
  IF (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN' THEN
    UPDATE user_profiles SET is_active = false WHERE id = target_user_id;
  ELSE
    RAISE EXCEPTION 'Access denied';
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

CREATE OR REPLACE FUNCTION activate_user(target_user_id UUID) RETURNS VOID AS $$
BEGIN
  IF (SELECT role FROM user_profiles WHERE id = auth.uid()) = 'ADMIN' THEN
    UPDATE user_profiles SET is_active = true WHERE id = target_user_id;
  ELSE
    RAISE EXCEPTION 'Access denied';
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- =========================================================================================
-- CHÈN SEED DATA (Dữ liệu mẫu cho App Options)
-- =========================================================================================
INSERT INTO app_options (group_key, option_key, label, sort_order) VALUES
('laptopStatus', 'not_imported', 'Chưa nhập kho', 0),
('laptopStatus', 'available', 'Sẵn hàng (đã nhập kho)', 1),
('laptopStatus', 'deposited', 'Đã cọc (Giữ chỗ)', 2),
('laptopStatus', 'sold', 'Đã bán', 3),
('laptopStatus', 'returned_cn', 'Back lại TQ', 4),
('laptopStatus', 'repairing', 'Đang sửa chữa', 5),
('laptopStatus', 'skipped', 'Bỏ qua', 6),
('laptopLocation', 'store', 'CH', 0),
('laptopLocation', 'wh', 'KHO', 1),
('laptopLocation', 'wh_cn', 'KHO TQ', 2),
('laptopLocation', 'repair', 'Sửa chữa', 3),
('chargerStatus', 'with_charger', 'Có Sạc', 0),
('chargerStatus', 'no_charger', 'Không Sạc', 1),
('chargerStatus', 'shared_charger', 'Sạc Lô', 2),
('chargerStatus', 'unchecked', 'Chưa Check', 3),
('componentStatus', 'ok', 'OK', 0),
('componentStatus', 'error', 'Lỗi / Có vấn đề', 1),
('orderStatus', 'new', 'MỚI TẠO', 0),
('orderStatus', 'deposited', 'ĐÃ CỌC / GIỮ MÁY', 1),
('orderStatus', 'prepared', 'ĐÃ CHUẨN BỊ XONG', 2),
('orderStatus', 'shipping', 'ĐANG GIAO HÀNG', 3),
('orderStatus', 'done', 'HOÀN THÀNH', 4),
('orderStatus', 'returned', 'BACK MÁY', 5),
('orderStatus', 'cancelled', 'HỦY ĐƠN', 6),
('paymentStatus', 'unpaid', 'CHƯA THANH TOÁN', 0),
('paymentStatus', 'deposited', 'ĐÃ CỌC', 1),
('paymentStatus', 'cod', 'ĐANG CHỜ COD', 2),
('paymentStatus', 'paid', 'ĐÃ THANH TOÁN', 3),
('paymentStatus', 'refunded', 'ĐÃ HOÀN TIỀN', 4),
('deliveryStatus', 'preparing', 'ĐANG CHUẨN BỊ', 0),
('deliveryStatus', 'shipped', 'ĐÃ GỬI HÀNG', 1),
('deliveryStatus', 'delivered', 'ĐÃ GIAO HÀNG', 2),
('deliveryStatus', 'at_store', 'TẠI SHOP', 3),
('deliveryStatus', 'returned', 'HOÀN HÀNG', 4),
('orderType', 'retail', 'Bán lẻ (Retail)', 0),
('orderType', 'wholesale', 'Bán sỉ/Thợ (Wholesale)', 1),
('orderType', 'trade_in', 'Thu cũ đổi mới (Trade-in)', 2),
('paymentMethod', 'transfer_cash', 'Chuyển khoản / Tiền mặt', 0),
('paymentMethod', 'card', 'Quẹt thẻ (Tốn phí)', 1),
('paymentMethod', 'installment', 'Trả góp', 2),
('shippingMethod', 'viettelpost', 'ViettelPost', 0),
('shippingMethod', 'shopee_spx', 'Shopee SPX', 1),
('shippingMethod', 'direct_store', 'Trực tiếp Shop', 2),
('shippingMethod', 'hcm_agent', 'Nhờ HCM giao dịch', 3),
('shippingMethod', 'hai_an', 'Nhà xe Hải An', 4),
('shippingMethod', 'shared_car', 'Xe Ghép', 5),
('shippingMethod', 'direct_ship', 'Ship trực tiếp khách', 6),
('shippingMethod', 'bus', 'Xe khách', 7),
('giftOptions', 'basic_gift', 'quà cơ bản (balo + chuột)', 0),
('giftOptions', 'no_gift', 'ko quà', 1),
('giftOptions', 'mouse_only', 'chỉ tặng chuột', 2),
('giftOptions', 'bag_only', 'chỉ tặng balo', 3),
('category', '1', 'LEGION 5 2023', 0),
('category', '2', 'ROG G513 2022', 1),
('category', '3', 'ROG Scar 2022', 2),
('category', '4', 'ROG Zephyrus G14', 3),
('category', '5', 'LEGION 5 Pro 2022', 4),
('category', '6', 'LEGION 5 Pro 2023 - 2024', 5),
('category', '7', 'LEGION Slim 7', 6),
('category', '8', 'ASUS TUF Gaming', 7),
('category', '9', 'ROG M16 / G16', 8),
('category', '10', 'ACER Nitro 5', 9),
('saleOnline', '1', 'Thắng Tiktok', 0),
('saleOnline', '2', 'Thắng Zalo', 1),
('saleOnline', '3', 'Vương', 2),
('saleOnline', '4', 'Quế Anh', 3),
('saleOnline', '5', 'Quảng', 4),
('saleOnline', '6', 'Linh', 5),
('saleOnline', '7', 'Hoàng', 6),
('saleOnline', '8', 'Tuấn', 7),
('saleOnline', 'other', 'Khác', 8),
('saleOffline', '1', 'Thắng', 0),
('saleOffline', '2', 'Vương', 1),
('saleOffline', 'other', 'Khác', 2),
('seller', 'guangzhou', 'Guangzhou Tech', 0),
('seller', 'shenzhen', 'Shenzhen Digital', 1),
('seller', 'beijing', 'Beijing Digital', 2),
('seller', 'aming', 'Shop TQ A-Ming', 3),
('seller', 'xiao', 'Shop TQ Xiao', 4),
('warrantyCaseStatus', 'received', 'TIẾP NHẬN', 0),
('warrantyCaseStatus', 'checking', 'ĐANG KIỂM TRA', 1),
('warrantyCaseStatus', 'wait_parts', 'CHỜ LINH KIỆN', 2),
('warrantyCaseStatus', 'repairing', 'ĐANG SỬA', 3),
('warrantyCaseStatus', 'done', 'HOÀN TẤT', 4),
('warrantyCaseStatus', 'swap_device', 'ĐỔI MÁY', 5),
('warrantyCaseStatus', 'refunded', 'HOÀN TIỀN', 6);


-- =========================================================================================
-- CẤP QUYỀN TRUY CẬP CHO POSTGREST (BẮT BUỘC ĐỂ API HOẠT ĐỘNG)
-- =========================================================================================
-- Browser chỉ được đọc profile của chính mình để khôi phục session. Toàn bộ dữ liệu
-- nghiệp vụ phải đi qua Route Handler đã xác thực/ủy quyền ở server.
DROP POLICY IF EXISTS "Cho phép đọc user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "Chỉ ADMIN được cập nhật user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "Chỉ ADMIN được xóa user_profiles" ON user_profiles;
DROP POLICY IF EXISTS "Chỉ ADMIN được tạo user_profiles" ON user_profiles;
CREATE POLICY "User chỉ đọc profile của chính mình" ON user_profiles FOR SELECT USING (id = auth.uid());

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL ROUTINES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON SCHEMA public FROM anon, authenticated;
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT SELECT ON user_profiles TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO service_role;

-- =========================================================================================
-- CONSISTENCY FUNCTIONS FOR ORDER AND INVENTORY STATE
-- =========================================================================================

CREATE OR REPLACE FUNCTION public.normalize_order_financials(p_order orders)
RETURNS orders
LANGUAGE plpgsql
STABLE
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order orders := p_order;
BEGIN
  v_order.is_active := COALESCE(v_order.is_active, true);
  v_order.sale_price := GREATEST(COALESCE(v_order.sale_price, 0), 0);
  v_order.deposit_amount := LEAST(v_order.sale_price, GREATEST(COALESCE(v_order.deposit_amount, 0), 0));
  v_order.amount_paid := LEAST(v_order.sale_price,
    GREATEST(COALESCE(v_order.amount_paid, 0), v_order.deposit_amount));
  v_order.debt_amount := GREATEST(v_order.sale_price - v_order.amount_paid, 0);
  v_order.cod_amount := LEAST(v_order.debt_amount, GREATEST(COALESCE(v_order.cod_amount, 0), 0));
  v_order.credit_card_fee := GREATEST(COALESCE(v_order.credit_card_fee, 0), 0);
  v_order.profit_vnd := COALESCE(v_order.profit_vnd, 0);

  IF v_order.laptop_id IS NOT NULL
     AND v_order.is_active IS TRUE
     AND v_order.reservation_expires_at IS NULL
     AND (v_order.order_status = 'deposited' OR v_order.payment_status = 'deposited') THEN
    v_order.reservation_expires_at := timezone('utc'::text, now()) + INTERVAL '48 hours';
  END IF;

  v_order.payment_status := lower(btrim(COALESCE(v_order.payment_status, '')));
  IF v_order.payment_status NOT IN ('unpaid', 'deposited', 'cod', 'paid', 'refunded') THEN
    v_order.payment_status := 'unpaid';
  END IF;
  v_order.laptop_locked := public.order_uses_laptop(
    v_order.laptop_id,
    v_order.is_active,
    v_order.order_status,
    v_order.payment_status,
    v_order.reservation_expires_at
  );
  RETURN v_order;
END;
$$;

CREATE OR REPLACE FUNCTION public.refresh_laptop_inventory(p_laptop_id BIGINT)
RETURNS laptops
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_laptop laptops%ROWTYPE;
  v_has_committed BOOLEAN;
  v_has_locked BOOLEAN;
  v_has_requested BOOLEAN;
BEGIN
  IF p_laptop_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT * INTO v_laptop
  FROM laptops
  WHERE id = p_laptop_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Laptop % does not exist', p_laptop_id;
  END IF;

  UPDATE orders
  SET laptop_locked = public.order_uses_laptop(
        laptop_id,
        is_active,
        order_status,
        payment_status,
        reservation_expires_at
      ),
      updated_at = timezone('utc'::text, now())
  WHERE laptop_id = p_laptop_id
    AND laptop_locked IS DISTINCT FROM public.order_uses_laptop(
      laptop_id,
      is_active,
      order_status,
      payment_status,
      reservation_expires_at
    );

  SELECT EXISTS (
    SELECT 1
    FROM orders
    WHERE laptop_id = p_laptop_id
      AND public.order_uses_laptop(
        laptop_id,
        is_active,
        order_status,
        payment_status,
        reservation_expires_at
      )
      AND order_status IN ('prepared', 'shipping', 'done')
  ) INTO v_has_committed;

  SELECT EXISTS (
    SELECT 1
    FROM orders
    WHERE laptop_id = p_laptop_id
      AND public.order_uses_laptop(
        laptop_id,
        is_active,
        order_status,
        payment_status,
        reservation_expires_at
      )
  ) INTO v_has_locked;

  SELECT EXISTS (
    SELECT 1
    FROM orders
    WHERE requested_laptop_id = p_laptop_id
      AND laptop_id IS NULL
      AND is_active IS TRUE
      AND COALESCE(payment_status, '') <> 'refunded'
      AND COALESCE(order_status, '') NOT IN ('cancelled', 'returned')
      AND (order_status = 'deposited' OR payment_status = 'deposited')
      AND (reservation_expires_at IS NULL OR reservation_expires_at > CURRENT_TIMESTAMP)
  ) INTO v_has_requested;

  IF COALESCE(v_laptop.status, '') IN ('not_imported', 'repairing', 'returned_cn', 'skipped') THEN
    UPDATE laptops
    SET is_locked = v_has_locked,
        updated_at = timezone('utc'::text, now())
    WHERE id = p_laptop_id;
  ELSE
    UPDATE laptops
    SET is_locked = v_has_locked,
        status = CASE
          WHEN v_has_committed THEN 'sold'
          WHEN v_has_locked OR v_has_requested THEN 'deposited'
          WHEN status IN ('sold', 'deposited') THEN 'available'
          ELSE status
        END,
        updated_at = timezone('utc'::text, now())
    WHERE id = p_laptop_id;
  END IF;

  SELECT * INTO v_laptop FROM laptops WHERE id = p_laptop_id;
  RETURN v_laptop;
END;
$$;

CREATE OR REPLACE FUNCTION public.record_order_payment(
  p_order_id BIGINT,
  p_amount NUMERIC,
  p_payment_type TEXT,
  p_payment_method TEXT DEFAULT 'transfer_cash',
  p_payment_date DATE DEFAULT CURRENT_DATE,
  p_reference_code TEXT DEFAULT NULL,
  p_note TEXT DEFAULT NULL,
  p_recorded_by TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order orders%ROWTYPE;
  v_payment payments%ROWTYPE;
  v_financial financial_records%ROWTYPE;
  v_new_amount_paid NUMERIC;
  v_old_uses BOOLEAN;
  v_new_uses BOOLEAN;
  v_old_committed BOOLEAN;
  v_new_committed BOOLEAN;
  v_laptop laptops%ROWTYPE;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Payment amount must be greater than zero';
  END IF;
  IF p_payment_type NOT IN ('deposit', 'balance', 'cod', 'refund', 'other') THEN
    RAISE EXCEPTION 'Unsupported payment type';
  END IF;

  SELECT * INTO v_order FROM orders WHERE id = p_order_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order % does not exist', p_order_id;
  END IF;
  IF v_order.is_active IS NOT TRUE THEN
    RAISE EXCEPTION 'Cannot record payment for an inactive order';
  END IF;

  v_old_uses := public.order_uses_laptop(
    v_order.laptop_id,
    v_order.is_active,
    v_order.order_status,
    v_order.payment_status,
    v_order.reservation_expires_at
  );
  v_old_committed := v_old_uses AND v_order.order_status IN ('prepared', 'shipping', 'done');
  IF v_order.laptop_id IS NOT NULL THEN
    PERFORM pg_advisory_xact_lock(v_order.laptop_id);
  END IF;

  IF p_payment_type = 'refund' THEN
    IF p_amount > COALESCE(v_order.amount_paid, 0) THEN
      RAISE EXCEPTION 'Refund cannot exceed amount already paid';
    END IF;
    v_new_amount_paid := GREATEST(COALESCE(v_order.amount_paid, 0) - p_amount, 0);
    v_order.deposit_amount := LEAST(COALESCE(v_order.deposit_amount, 0), v_new_amount_paid);
    IF v_new_amount_paid = 0 THEN
      v_order.payment_status := 'refunded';
    END IF;
  ELSE
    IF COALESCE(v_order.amount_paid, 0) + p_amount > COALESCE(v_order.sale_price, 0) THEN
      RAISE EXCEPTION 'Payment exceeds order sale price';
    END IF;
    v_new_amount_paid := COALESCE(v_order.amount_paid, 0) + p_amount;
    v_order.amount_paid := v_new_amount_paid;
    IF p_payment_type = 'deposit' THEN
      v_order.deposit_amount := COALESCE(v_order.deposit_amount, 0) + p_amount;
    ELSIF p_payment_type = 'cod' THEN
      v_order.payment_status := 'cod';
    END IF;
  END IF;

  v_order.amount_paid := v_new_amount_paid;
  v_order := public.normalize_order_financials(v_order);

  INSERT INTO payments (
    order_id, payment_type, amount, payment_method, payment_date,
    reference_code, note, recorded_by
  ) VALUES (
    p_order_id,
    p_payment_type,
    p_amount,
    COALESCE(NULLIF(btrim(p_payment_method), ''), 'transfer_cash'),
    COALESCE(p_payment_date, CURRENT_DATE),
    p_reference_code,
    p_note,
    p_recorded_by
  ) RETURNING * INTO v_payment;

  INSERT INTO financial_records (
    record_type, category, amount, order_id, payment_id, occurred_on,
    payment_method, note, recorded_by
  ) VALUES (
    CASE WHEN p_payment_type = 'refund' THEN 'refund' ELSE 'income' END,
    p_payment_type,
    p_amount,
    p_order_id,
    v_payment.id,
    COALESCE(p_payment_date, CURRENT_DATE),
    COALESCE(NULLIF(btrim(p_payment_method), ''), 'transfer_cash'),
    p_note,
    p_recorded_by
  ) RETURNING * INTO v_financial;

  UPDATE orders
  SET amount_paid = v_order.amount_paid,
      deposit_amount = v_order.deposit_amount,
      debt_amount = v_order.debt_amount,
      payment_status = v_order.payment_status,
      laptop_locked = v_order.laptop_locked,
      updated_at = timezone('utc'::text, now())
  WHERE id = p_order_id
  RETURNING * INTO v_order;

  v_new_uses := public.order_uses_laptop(
    v_order.laptop_id,
    v_order.is_active,
    v_order.order_status,
    v_order.payment_status,
    v_order.reservation_expires_at
  );
  v_new_committed := v_new_uses AND v_order.order_status IN ('prepared', 'shipping', 'done');
  IF v_order.laptop_id IS NOT NULL THEN
    v_laptop := public.refresh_laptop_inventory(v_order.laptop_id);
    IF v_old_uses IS DISTINCT FROM v_new_uses
       OR v_old_committed IS DISTINCT FROM v_new_committed THEN
      INSERT INTO stock_movements (laptop_id, order_id, movement_type, note, performed_by)
      VALUES (
        v_order.laptop_id,
        v_order.id,
        CASE
          WHEN NOT v_new_uses THEN 'RELEASED'
          WHEN v_new_committed THEN 'SOLD'
          ELSE 'RESERVED'
        END,
        'Laptop state synchronized by payment',
        p_recorded_by
      );
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'payment', to_jsonb(v_payment),
    'financial_record', to_jsonb(v_financial),
    'order', to_jsonb(v_order),
    'laptop', CASE WHEN v_laptop.id IS NULL THEN NULL ELSE to_jsonb(v_laptop) END
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.create_order_with_inventory(
  p_order JSONB,
  p_recorded_by TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_input orders%ROWTYPE;
  v_order orders%ROWTYPE;
  v_laptop laptops%ROWTYPE;
  v_payment payments%ROWTYPE;
  v_initial_deposit NUMERIC;
  v_initial_balance NUMERIC;
  v_created_payments JSONB := '[]'::jsonb;
BEGIN
  v_input := jsonb_populate_record(NULL::orders, COALESCE(p_order, '{}'::jsonb));
  v_input.created_at := COALESCE(v_input.created_at, timezone('utc'::text, now()));
  v_input.updated_at := COALESCE(v_input.updated_at, timezone('utc'::text, now()));
  v_input := public.normalize_order_financials(v_input);

  INSERT INTO orders (
    created_date, sale_online, sale_offline, note, order_type, order_status,
    payment_status, payment_method, delivery_status, shipping_method, laptop_id,
    sale_price, deposit_amount, deposit_note, cod_amount, amount_paid, debt_amount,
    credit_card_fee, profit_vnd, trade_in_laptop_id, customer_id, customer_info,
    customer_address, tracking_code, ship_date, setup_note, warranty, gifts,
    laptop_locked, reservation_expires_at, cancel_reason, cancelled_at, is_active,
    month_key, created_at, updated_at
  ) VALUES (
    v_input.created_date, v_input.sale_online, v_input.sale_offline, v_input.note,
    v_input.order_type, v_input.order_status, v_input.payment_status,
    v_input.payment_method, v_input.delivery_status, v_input.shipping_method,
    v_input.laptop_id, v_input.sale_price, v_input.deposit_amount, v_input.deposit_note,
    v_input.cod_amount, v_input.amount_paid, v_input.debt_amount, v_input.credit_card_fee,
    v_input.profit_vnd, v_input.trade_in_laptop_id, v_input.customer_id,
    v_input.customer_info, v_input.customer_address, v_input.tracking_code,
    v_input.ship_date, v_input.setup_note, v_input.warranty, v_input.gifts,
    v_input.laptop_locked, v_input.reservation_expires_at, v_input.cancel_reason,
    v_input.cancelled_at, v_input.is_active,
    COALESCE(NULLIF(btrim(v_input.month_key), ''), TO_CHAR(CURRENT_DATE, 'MM/YYYY')),
    v_input.created_at, v_input.updated_at
  ) RETURNING * INTO v_order;

  -- Keep the order opening balance and the payment ledger in sync.
  v_initial_deposit := LEAST(COALESCE(v_order.deposit_amount, 0), COALESCE(v_order.amount_paid, 0));
  v_initial_balance := GREATEST(COALESCE(v_order.amount_paid, 0) - v_initial_deposit, 0);
  IF v_initial_deposit > 0 THEN
    INSERT INTO payments (
      order_id, payment_type, amount, payment_method, payment_date, note, recorded_by
    ) VALUES (
      v_order.id,
      'deposit',
      v_initial_deposit,
      COALESCE(NULLIF(btrim(v_order.payment_method), ''), 'transfer_cash'),
      COALESCE(v_order.created_date, CURRENT_DATE),
      v_order.deposit_note,
      p_recorded_by
    ) RETURNING * INTO v_payment;
    v_created_payments := v_created_payments || jsonb_build_array(to_jsonb(v_payment));

    INSERT INTO financial_records (
      record_type, category, amount, order_id, payment_id, occurred_on,
      payment_method, note, recorded_by
    ) VALUES (
      'income', 'deposit', v_initial_deposit, v_order.id, v_payment.id,
      COALESCE(v_order.created_date, CURRENT_DATE),
      COALESCE(NULLIF(btrim(v_order.payment_method), ''), 'transfer_cash'),
      v_order.deposit_note,
      p_recorded_by
    );
  END IF;

  IF v_initial_balance > 0 THEN
    INSERT INTO payments (
      order_id, payment_type, amount, payment_method, payment_date, note, recorded_by
    ) VALUES (
      v_order.id,
      CASE WHEN v_order.payment_status = 'cod' THEN 'cod' ELSE 'balance' END,
      v_initial_balance,
      COALESCE(NULLIF(btrim(v_order.payment_method), ''), 'transfer_cash'),
      COALESCE(v_order.created_date, CURRENT_DATE),
      'Initial payment recorded with order',
      p_recorded_by
    ) RETURNING * INTO v_payment;
    v_created_payments := v_created_payments || jsonb_build_array(to_jsonb(v_payment));

    INSERT INTO financial_records (
      record_type, category, amount, order_id, payment_id, occurred_on,
      payment_method, note, recorded_by
    ) VALUES (
      'income',
      CASE WHEN v_order.payment_status = 'cod' THEN 'cod' ELSE 'balance' END,
      v_initial_balance,
      v_order.id,
      v_payment.id,
      COALESCE(v_order.created_date, CURRENT_DATE),
      COALESCE(NULLIF(btrim(v_order.payment_method), ''), 'transfer_cash'),
      'Initial payment recorded with order',
      p_recorded_by
    );
  END IF;

  IF v_order.laptop_id IS NOT NULL THEN
    v_laptop := public.refresh_laptop_inventory(v_order.laptop_id);
    IF v_order.laptop_locked IS TRUE THEN
      INSERT INTO stock_movements (laptop_id, order_id, movement_type, note, performed_by)
      VALUES (
        v_order.laptop_id,
        v_order.id,
        CASE WHEN v_order.order_status IN ('prepared', 'shipping', 'done') THEN 'SOLD' ELSE 'RESERVED' END,
        'Inventory updated by order transaction',
        p_recorded_by
      );
    END IF;
  END IF;

  RETURN jsonb_build_object(
    'order', to_jsonb(v_order),
    'laptop', CASE WHEN v_laptop.id IS NULL THEN NULL ELSE to_jsonb(v_laptop) END,
    'payments', v_created_payments,
    'inventory_applied', true
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.update_order_with_inventory(
  p_order JSONB,
  p_recorded_by TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order_id BIGINT;
  v_existing orders%ROWTYPE;
  v_next orders%ROWTYPE;
  v_order orders%ROWTYPE;
  v_old_laptop laptops%ROWTYPE;
  v_previous_laptop laptops%ROWTYPE;
  v_laptop laptops%ROWTYPE;
  v_old_laptop_id BIGINT;
  v_new_laptop_id BIGINT;
  v_old_uses BOOLEAN;
  v_new_uses BOOLEAN;
  v_old_committed BOOLEAN;
  v_new_committed BOOLEAN;
BEGIN
  IF p_order IS NULL OR NOT (p_order ? 'id') THEN
    RAISE EXCEPTION 'Order id is required';
  END IF;

  v_order_id := (p_order->>'id')::BIGINT;
  SELECT * INTO v_existing FROM orders WHERE id = v_order_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order % does not exist', v_order_id;
  END IF;

  v_next := jsonb_populate_record(v_existing, p_order);
  v_next.id := v_existing.id;
  v_next.created_at := COALESCE(v_next.created_at, v_existing.created_at);
  v_next.updated_at := timezone('utc'::text, now());
  v_next := public.normalize_order_financials(v_next);

  v_old_laptop_id := v_existing.laptop_id;
  v_new_laptop_id := v_next.laptop_id;
  v_old_uses := public.order_uses_laptop(
    v_existing.laptop_id,
    v_existing.is_active,
    v_existing.order_status,
    v_existing.payment_status,
    v_existing.reservation_expires_at
  );
  v_new_uses := public.order_uses_laptop(
    v_next.laptop_id,
    v_next.is_active,
    v_next.order_status,
    v_next.payment_status,
    v_next.reservation_expires_at
  );
  v_old_committed := v_old_uses AND v_existing.order_status IN ('prepared', 'shipping', 'done');
  v_new_committed := v_new_uses AND v_next.order_status IN ('prepared', 'shipping', 'done');

  IF v_old_laptop_id IS NOT NULL AND v_new_laptop_id IS NOT NULL AND v_old_laptop_id <> v_new_laptop_id THEN
    IF v_old_laptop_id < v_new_laptop_id THEN
      PERFORM pg_advisory_xact_lock(v_old_laptop_id);
      PERFORM pg_advisory_xact_lock(v_new_laptop_id);
    ELSE
      PERFORM pg_advisory_xact_lock(v_new_laptop_id);
      PERFORM pg_advisory_xact_lock(v_old_laptop_id);
    END IF;
  ELSIF v_old_laptop_id IS NOT NULL THEN
    PERFORM pg_advisory_xact_lock(v_old_laptop_id);
  ELSIF v_new_laptop_id IS NOT NULL THEN
    PERFORM pg_advisory_xact_lock(v_new_laptop_id);
  END IF;

  IF v_old_laptop_id IS NOT NULL THEN
    SELECT * INTO v_old_laptop FROM laptops WHERE id = v_old_laptop_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Laptop % does not exist', v_old_laptop_id; END IF;
  END IF;
  IF v_new_laptop_id IS NOT NULL AND v_new_laptop_id <> v_old_laptop_id THEN
    SELECT * INTO v_laptop FROM laptops WHERE id = v_new_laptop_id FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Laptop % does not exist', v_new_laptop_id; END IF;
  END IF;

  UPDATE orders
  SET created_date = v_next.created_date,
      sale_online = v_next.sale_online,
      sale_offline = v_next.sale_offline,
      note = v_next.note,
      order_type = v_next.order_type,
      order_status = v_next.order_status,
      payment_status = v_next.payment_status,
      payment_method = v_next.payment_method,
      delivery_status = v_next.delivery_status,
      shipping_method = v_next.shipping_method,
      laptop_id = v_next.laptop_id,
      sale_price = v_next.sale_price,
      deposit_amount = v_next.deposit_amount,
      deposit_note = v_next.deposit_note,
      cod_amount = v_next.cod_amount,
      amount_paid = v_next.amount_paid,
      debt_amount = v_next.debt_amount,
      credit_card_fee = v_next.credit_card_fee,
      profit_vnd = v_next.profit_vnd,
      trade_in_laptop_id = v_next.trade_in_laptop_id,
      customer_id = v_next.customer_id,
      customer_info = v_next.customer_info,
      customer_address = v_next.customer_address,
      tracking_code = v_next.tracking_code,
      ship_date = v_next.ship_date,
      setup_note = v_next.setup_note,
      warranty = v_next.warranty,
      gifts = v_next.gifts,
      laptop_locked = v_next.laptop_locked,
      reservation_expires_at = v_next.reservation_expires_at,
      cancel_reason = v_next.cancel_reason,
      cancelled_at = v_next.cancelled_at,
      is_active = v_next.is_active,
      month_key = COALESCE(NULLIF(btrim(v_next.month_key), ''), v_existing.month_key, TO_CHAR(CURRENT_DATE, 'MM/YYYY')),
      updated_at = v_next.updated_at
  WHERE id = v_order_id
  RETURNING * INTO v_order;

  IF v_old_laptop_id IS NOT NULL THEN
    v_previous_laptop := public.refresh_laptop_inventory(v_old_laptop_id);
  END IF;
  IF v_new_laptop_id IS NOT NULL THEN
    IF v_new_laptop_id = v_old_laptop_id THEN
      v_laptop := v_previous_laptop;
    ELSE
      v_laptop := public.refresh_laptop_inventory(v_new_laptop_id);
    END IF;
  END IF;

  IF v_old_laptop_id IS DISTINCT FROM v_new_laptop_id THEN
    IF v_old_laptop_id IS NOT NULL AND v_old_uses THEN
      INSERT INTO stock_movements (laptop_id, order_id, movement_type, note, performed_by)
      VALUES (v_old_laptop_id, v_order.id, 'RELEASED', 'Laptop released by order update', p_recorded_by);
    END IF;
    IF v_new_laptop_id IS NOT NULL AND v_new_uses THEN
      INSERT INTO stock_movements (laptop_id, order_id, movement_type, note, performed_by)
      VALUES (
        v_new_laptop_id,
        v_order.id,
        CASE WHEN v_new_committed THEN 'SOLD' ELSE 'RESERVED' END,
        'Laptop assigned by order update',
        p_recorded_by
      );
    END IF;
  ELSIF v_new_laptop_id IS NOT NULL
    AND (
      v_old_uses IS DISTINCT FROM v_new_uses
      OR v_old_committed IS DISTINCT FROM v_new_committed
    ) THEN
    INSERT INTO stock_movements (laptop_id, order_id, movement_type, note, performed_by)
    VALUES (
      v_new_laptop_id,
      v_order.id,
      CASE
        WHEN NOT v_new_uses THEN 'RELEASED'
        WHEN v_new_committed THEN 'SOLD'
        ELSE 'RESERVED'
      END,
      'Laptop state synchronized by order update',
      p_recorded_by
    );
  END IF;

  RETURN jsonb_build_object(
    'order', to_jsonb(v_order),
    'laptop', CASE WHEN v_laptop.id IS NULL THEN NULL ELSE to_jsonb(v_laptop) END,
    'previous_laptop', CASE WHEN v_old_laptop.id IS NULL THEN NULL ELSE to_jsonb(v_old_laptop) END,
    'inventory_applied', true
  );
END;
$$;

REVOKE ALL ON FUNCTION public.order_uses_laptop(BIGINT, BOOLEAN, TEXT, TEXT, TIMESTAMP WITH TIME ZONE)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.normalize_order_financials(orders)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.refresh_laptop_inventory(BIGINT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.refresh_laptop_inventory(BIGINT) TO service_role;
REVOKE ALL ON FUNCTION public.record_order_payment(BIGINT, NUMERIC, TEXT, TEXT, DATE, TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.create_order_with_inventory(JSONB, TEXT)
  FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.update_order_with_inventory(JSONB, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_order_payment(BIGINT, NUMERIC, TEXT, TEXT, DATE, TEXT, TEXT, TEXT)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.create_order_with_inventory(JSONB, TEXT)
  TO service_role;
GRANT EXECUTE ON FUNCTION public.update_order_with_inventory(JSONB, TEXT)
  TO service_role;

REVOKE UPDATE, DELETE ON public.activity_logs FROM service_role;
GRANT SELECT, INSERT ON public.activity_logs TO service_role;
REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.prevent_activity_log_mutation() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.prevent_activity_log_mutation() TO service_role;

COMMIT;
