-- Generated by node qa/build-d1-schema.mjs. Tables/constraints only; business port is tracked separately.

PRAGMA foreign_keys = ON;

CREATE TABLE auth_users (
    id TEXT PRIMARY KEY NOT NULL,
    email TEXT NOT NULL COLLATE NOCASE UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    last_sign_in_at TEXT
  );

CREATE TABLE "accessories" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "sku" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "kind" TEXT DEFAULT 'other' NOT NULL,
  "price" NUMERIC DEFAULT 0 NOT NULL,
  "note" TEXT DEFAULT '' NOT NULL,
  "active" INTEGER DEFAULT true NOT NULL CHECK ("active" IN (0,1)),
  CONSTRAINT "accessories_kind_check" CHECK (kind IN ('mouse', 'backpack', 'mousepad', 'sleeve', 'other')),
  CONSTRAINT "accessories_name_check" CHECK (length(trim(name)) >= 1 AND length(trim(name)) <= 240),
  CONSTRAINT "accessories_price_check" CHECK (price >= 0),
  CONSTRAINT "accessories_sku_check" CHECK (length(trim(sku)) >= 1 AND length(trim(sku)) <= 80),
  CONSTRAINT "accessories_sku_key" UNIQUE (sku)
);

CREATE TABLE "account_reconciliations" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "account_id" TEXT NOT NULL,
  "recorded_balance" NUMERIC NOT NULL,
  "actual_balance" NUMERIC NOT NULL,
  "difference" NUMERIC GENERATED ALWAYS AS ((actual_balance - recorded_balance)) STORED,
  "reconciled_at" TEXT NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "account_reconciliations_account_id_fkey" FOREIGN KEY (account_id) REFERENCES cash_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "account_reconciliations_pkey" PRIMARY KEY (id)
);

CREATE TABLE "account_transactions" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "account_id" TEXT NOT NULL,
  "direction" TEXT NOT NULL,
  "amount" NUMERIC NOT NULL,
  "currency" TEXT NOT NULL,
  "reference_type" TEXT NOT NULL,
  "reference_id" TEXT NOT NULL,
  "transaction_type" TEXT NOT NULL,
  "occurred_at" TEXT NOT NULL,
  "description" TEXT DEFAULT '' NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "transfer_group_id" TEXT,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "account_transactions_account_id_fkey" FOREIGN KEY (account_id) REFERENCES cash_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "account_transactions_amount_check" CHECK (amount > 0),
  CONSTRAINT "account_transactions_currency_check" CHECK (currency IN ('VND', 'CNY')),
  CONSTRAINT "account_transactions_direction_check" CHECK (direction IN ('IN', 'OUT')),
  CONSTRAINT "account_transactions_idempotency_key_check" CHECK (length(trim(idempotency_key)) >= 8 AND length(trim(idempotency_key)) <= 100),
  CONSTRAINT "account_transactions_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "account_transactions_pkey" PRIMARY KEY (id),
  CONSTRAINT "account_transactions_reference_id_check" CHECK (length(trim(reference_id)) >= 1 AND length(trim(reference_id)) <= 100),
  CONSTRAINT "account_transactions_reference_type_check" CHECK (reference_type IN ('PAYMENT', 'SUPPLIER_PAYMENT', 'SUPPLIER_REFUND', 'COD_SETTLEMENT', 'COMMISSION', 'MANUAL', 'TRANSFER')),
  CONSTRAINT "account_transactions_transaction_type_check" CHECK (transaction_type IN ('CUSTOMER_PAYMENT', 'COD_SETTLEMENT', 'SUPPLIER_PAYMENT', 'SUPPLIER_REFUND', 'COMMISSION_PAYMENT', 'MANUAL_IN', 'MANUAL_OUT', 'TRANSFER_IN', 'TRANSFER_OUT', 'OTHER'))
);

CREATE TABLE "activity_logs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "entity_type" TEXT NOT NULL,
  "entity_id" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "changes" TEXT CHECK ("changes" IS NULL OR json_valid("changes")),
  "user_name" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  CONSTRAINT "activity_logs_action_check" CHECK (action IN ('CREATE', 'UPDATE', 'DELETE'))
);

CREATE TABLE "app_options" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "group_key" TEXT NOT NULL,
  "option_key" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "is_active" INTEGER DEFAULT true CHECK ("is_active" IN (0,1)),
  "sort_order" INTEGER DEFAULT 0,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  CONSTRAINT "app_options_group_key_option_key_key" UNIQUE (group_key, option_key)
);

CREATE TABLE "app_settings" (
  "key" TEXT NOT NULL,
  "value" TEXT NOT NULL CHECK ("value" IS NULL OR json_valid("value")),
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  CONSTRAINT "app_settings_pkey" PRIMARY KEY (key)
);

CREATE TABLE "branches" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "address" TEXT DEFAULT '' NOT NULL,
  "active" INTEGER DEFAULT true NOT NULL CHECK ("active" IN (0,1)),
  CONSTRAINT "branches_name_check" CHECK (length(trim(name)) >= 1 AND length(trim(name)) <= 160)
);

CREATE TABLE "cash_accounts" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "account_type" TEXT NOT NULL,
  "currency" TEXT NOT NULL,
  "opening_balance" NUMERIC DEFAULT 0 NOT NULL,
  "opening_balance_at" TEXT NOT NULL,
  "is_active" INTEGER DEFAULT true NOT NULL CHECK ("is_active" IN (0,1)),
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "cash_accounts_account_type_check" CHECK (account_type IN ('CASH', 'BANK', 'WECHAT', 'ALIPAY', 'OTHER')),
  CONSTRAINT "cash_accounts_code_check" CHECK (length(code) BETWEEN 2 AND 40 AND code NOT GLOB '*[^A-Z0-9_-]*'),
  CONSTRAINT "cash_accounts_code_key" UNIQUE (code),
  CONSTRAINT "cash_accounts_currency_check" CHECK (currency IN ('VND', 'CNY')),
  CONSTRAINT "cash_accounts_name_check" CHECK (length(trim(name)) >= 1 AND length(trim(name)) <= 160),
  CONSTRAINT "cash_accounts_pkey" PRIMARY KEY (id)
);

CREATE TABLE "cod_receivables" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "order_id" INTEGER NOT NULL,
  "carrier" TEXT DEFAULT '' NOT NULL,
  "tracking_number" TEXT DEFAULT '' NOT NULL,
  "expected_cod_amount_vnd" NUMERIC NOT NULL,
  "status" TEXT DEFAULT 'PENDING_DELIVERY' NOT NULL,
  "shipped_at" TEXT,
  "delivered_at" TEXT,
  "expected_settlement_at" TEXT,
  "settled_at" TEXT,
  "notes" TEXT DEFAULT '' NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "cod_receivables_expected_cod_amount_vnd_check" CHECK (expected_cod_amount_vnd > 0),
  CONSTRAINT "cod_receivables_idempotency_key_check" CHECK (length(trim(idempotency_key)) >= 8 AND length(trim(idempotency_key)) <= 100),
  CONSTRAINT "cod_receivables_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "cod_receivables_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT "cod_receivables_order_id_key" UNIQUE (order_id),
  CONSTRAINT "cod_receivables_pkey" PRIMARY KEY (id),
  CONSTRAINT "cod_receivables_status_check" CHECK (status IN ('PENDING_DELIVERY', 'DELIVERED', 'WAITING_SETTLEMENT', 'PARTIALLY_SETTLED', 'SETTLED', 'DISPUTED', 'RETURNED', 'CANCELLED'))
);

CREATE TABLE "cod_settlements" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "cod_receivable_id" TEXT NOT NULL,
  "amount_vnd" NUMERIC NOT NULL,
  "account_id" TEXT NOT NULL,
  "reference" TEXT DEFAULT '' NOT NULL,
  "settled_at" TEXT NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "cod_settlements_account_id_fkey" FOREIGN KEY (account_id) REFERENCES cash_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "cod_settlements_amount_vnd_check" CHECK (amount_vnd > 0),
  CONSTRAINT "cod_settlements_cod_receivable_id_fkey" FOREIGN KEY (cod_receivable_id) REFERENCES cod_receivables(id) ON DELETE RESTRICT,
  CONSTRAINT "cod_settlements_idempotency_key_check" CHECK (length(trim(idempotency_key)) >= 8 AND length(trim(idempotency_key)) <= 100),
  CONSTRAINT "cod_settlements_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "cod_settlements_pkey" PRIMARY KEY (id)
);

CREATE TABLE "commissions" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "order_id" INTEGER NOT NULL,
  "laptop_id" INTEGER,
  "beneficiary_type" TEXT NOT NULL,
  "beneficiary_user_id" TEXT,
  "beneficiary_name" TEXT,
  "commission_type" TEXT NOT NULL,
  "amount_vnd" NUMERIC NOT NULL,
  "status" TEXT DEFAULT 'PENDING' NOT NULL,
  "calculation_basis" TEXT NOT NULL,
  "calculation_snapshot_json" TEXT CHECK ("calculation_snapshot_json" IS NULL OR json_valid("calculation_snapshot_json")),
  "earned_at" TEXT NOT NULL,
  "approved_at" TEXT,
  "paid_at" TEXT,
  "payment_account_id" TEXT,
  "payment_reference" TEXT,
  "idempotency_key" TEXT NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "commissions_amount_vnd_check" CHECK (amount_vnd > 0),
  CONSTRAINT "commissions_beneficiary_type_check" CHECK (beneficiary_type IN ('EMPLOYEE', 'CTV', 'OTHER')),
  CONSTRAINT "commissions_beneficiary_user_id_fkey" FOREIGN KEY (beneficiary_user_id) REFERENCES user_profiles(id) ON DELETE SET NULL,
  CONSTRAINT "commissions_check" CHECK (beneficiary_user_id IS NOT NULL OR trim(COALESCE(beneficiary_name, '')) <> ''),
  CONSTRAINT "commissions_commission_type_check" CHECK (commission_type IN ('FIXED', 'MANUAL')),
  CONSTRAINT "commissions_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "commissions_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE SET NULL,
  CONSTRAINT "commissions_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT "commissions_payment_account_id_fkey" FOREIGN KEY (payment_account_id) REFERENCES cash_accounts(id),
  CONSTRAINT "commissions_pkey" PRIMARY KEY (id),
  CONSTRAINT "commissions_status_check" CHECK (status IN ('PENDING', 'APPROVED', 'PAID', 'CANCELLED'))
);

CREATE TABLE "customers" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "phone" TEXT,
  "address" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE "financial_records" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "record_type" TEXT NOT NULL,
  "category" TEXT NOT NULL,
  "amount" NUMERIC NOT NULL,
  "order_id" INTEGER,
  "payment_id" INTEGER,
  "laptop_id" INTEGER,
  "occurred_on" TEXT DEFAULT CURRENT_DATE NOT NULL,
  "payment_method" TEXT,
  "note" TEXT,
  "recorded_by" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "financial_records_amount_check" CHECK (amount > 0),
  CONSTRAINT "financial_records_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE SET NULL,
  CONSTRAINT "financial_records_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT "financial_records_payment_id_fkey" FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE SET NULL,
  CONSTRAINT "financial_records_record_type_check" CHECK (record_type IN ('income', 'expense', 'refund', 'adjustment'))
);

CREATE TABLE "invoices" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_id" INTEGER NOT NULL,
  "laptop_id" INTEGER,
  "customer_id" INTEGER,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "created_by" TEXT NOT NULL,
  "snapshot" TEXT NOT NULL CHECK ("snapshot" IS NULL OR json_valid("snapshot")),
  CONSTRAINT "invoices_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
  CONSTRAINT "invoices_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE RESTRICT,
  CONSTRAINT "invoices_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT "invoices_order_id_key" UNIQUE (order_id)
);

CREATE TABLE "laptop_cost_components" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "laptop_id" INTEGER NOT NULL,
  "cost_type" TEXT NOT NULL,
  "amount_vnd" NUMERIC NOT NULL,
  "amount_rmb" NUMERIC,
  "exchange_rate" NUMERIC,
  "source_type" TEXT NOT NULL,
  "source_id" TEXT,
  "description" TEXT DEFAULT '' NOT NULL,
  "occurred_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "created_by" TEXT NOT NULL,
  "voided_at" TEXT,
  "voided_by" TEXT,
  "void_reason" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "laptop_cost_components_amount_vnd_check" CHECK (amount_vnd >= 0),
  CONSTRAINT "laptop_cost_components_check" CHECK (amount_rmb IS NULL AND exchange_rate IS NULL OR amount_rmb >= 0 AND exchange_rate > 0),
  CONSTRAINT "laptop_cost_components_cost_type_check" CHECK (cost_type IN ('PURCHASE', 'TRADE_IN_ACQUISITION', 'CN_SHIPPING', 'VN_SHIPPING', 'PAYMENT_FEE', 'REPAIR', 'RAM_UPGRADE', 'SSD_UPGRADE', 'ACCESSORY', 'CLEANING', 'OTHER', 'REFUND_CREDIT')),
  CONSTRAINT "laptop_cost_components_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE RESTRICT,
  CONSTRAINT "laptop_cost_components_pkey" PRIMARY KEY (id),
  CONSTRAINT "laptop_cost_components_source_identity_check" CHECK (source_id IS NOT NULL AND length(trim(source_id)) >= 1 AND length(trim(source_id)) <= 100),
  CONSTRAINT "laptop_cost_components_source_type_check" CHECK (source_type IN ('TRADE_IN', 'REPAIR_JOB', 'MANUAL', 'SUPPLIER_REFUND'))
);

CREATE TABLE "laptops" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "serial" TEXT,
  "name" TEXT,
  "category" TEXT,
  "import_date" TEXT,
  "warehouse_date" TEXT,
  "location" TEXT,
  "charger_status" TEXT,
  "status" TEXT,
  "price_rmb" NUMERIC DEFAULT 0,
  "shipping_rmb" NUMERIC DEFAULT 0,
  "exchange_rate" NUMERIC DEFAULT 3550,
  "import_price_vnd" NUMERIC DEFAULT 0,
  "wholesale_price_vnd" NUMERIC DEFAULT 0,
  "retail_price_vnd" NUMERIC DEFAULT 0,
  "tracking_code" TEXT,
  "customer_note" TEXT,
  "battery_health" INTEGER,
  "warranty_supplier" TEXT,
  "screen_status" TEXT,
  "camera_mic_status" TEXT,
  "mainboard_status" TEXT,
  "condition_note" TEXT,
  "seller" TEXT,
  "is_active" INTEGER DEFAULT true CHECK ("is_active" IN (0,1)),
  "parts_history" TEXT DEFAULT '[]' CHECK ("parts_history" IS NULL OR json_valid("parts_history")),
  "month_key" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "sku" TEXT DEFAULT ('LT-' || upper(hex(randomblob(8)))) NOT NULL,
  "available_for_sale_at" TEXT,
  "source_type" TEXT DEFAULT 'UNKNOWN' NOT NULL,
  "source_reference_id" TEXT,
  "purchase_batch_id" INTEGER,
  "tracking_code_cn" TEXT DEFAULT '' NOT NULL,
  "purchase_price_rmb" NUMERIC DEFAULT 0 NOT NULL,
  "purchase_exchange_rate" NUMERIC,
  "received_at" TEXT,
  "sold_at" TEXT,
  "ignored_at" TEXT,
  "ignored_by" TEXT,
  "ignore_reason" TEXT DEFAULT '' NOT NULL,
  "created_by" TEXT DEFAULT 'System' NOT NULL,
  "qc_details" TEXT DEFAULT '{}' NOT NULL CHECK ("qc_details" IS NULL OR json_valid("qc_details")),
  CONSTRAINT "laptops_battery_health_range" CHECK (battery_health IS NULL OR battery_health >= 0 AND battery_health <= 100),
  CONSTRAINT "laptops_non_negative_values" CHECK (COALESCE(price_rmb, 0) >= 0 AND COALESCE(shipping_rmb, 0) >= 0 AND COALESCE(exchange_rate, 0) >= 0 AND COALESCE(import_price_vnd, 0) >= 0 AND COALESCE(wholesale_price_vnd, 0) >= 0 AND COALESCE(retail_price_vnd, 0) >= 0),
  CONSTRAINT "laptops_purchase_batch_id_fkey" FOREIGN KEY (purchase_batch_id) REFERENCES purchase_batches(id) ON DELETE RESTRICT,
  CONSTRAINT "laptops_purchase_values_check" CHECK (purchase_price_rmb >= 0 AND COALESCE(shipping_rmb, 0) >= 0 AND (purchase_exchange_rate IS NULL OR purchase_exchange_rate > 0)),
  CONSTRAINT "laptops_sale_prices_non_negative" CHECK (COALESCE(wholesale_price_vnd, 0) >= 0 AND COALESCE(retail_price_vnd, 0) >= 0),
  CONSTRAINT "laptops_source_lineage_check" CHECK ((source_type IN ('SUPPLIER_PURCHASE', 'SUPPLIER_REPLACEMENT')) AND purchase_batch_id IS NOT NULL AND purchase_exchange_rate IS NOT NULL OR (source_type IN ('UNKNOWN', 'TRADE_IN')) AND purchase_batch_id IS NULL),
  CONSTRAINT "laptops_source_type_check" CHECK (source_type IN ('SUPPLIER_PURCHASE', 'SUPPLIER_REPLACEMENT', 'TRADE_IN', 'UNKNOWN')),
  CONSTRAINT "laptops_status_check" CHECK (status IN ('in_transit', 'waiting_qc', 'available', 'reserved', 'sold', 'repair', 'supplier_return', 'ignored'))
);

CREATE TABLE "operation_requests" (
  "idempotency_key" TEXT NOT NULL,
  "operation" TEXT NOT NULL,
  "result" TEXT NOT NULL CHECK ("result" IS NULL OR json_valid("result")),
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "operation_requests_idempotency_key_check" CHECK (length(trim(idempotency_key)) >= 8 AND length(trim(idempotency_key)) <= 100),
  CONSTRAINT "operation_requests_operation_check" CHECK (length(trim(operation)) >= 2 AND length(trim(operation)) <= 80),
  CONSTRAINT "operation_requests_pkey" PRIMARY KEY (idempotency_key)
);

CREATE TABLE "orders" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "created_date" TEXT,
  "sale_online" TEXT,
  "sale_offline" TEXT,
  "note" TEXT,
  "order_type" TEXT,
  "order_status" TEXT,
  "payment_status" TEXT,
  "payment_method" TEXT,
  "delivery_status" TEXT,
  "shipping_method" TEXT,
  "laptop_id" INTEGER,
  "requested_laptop_id" INTEGER,
  "sale_price" NUMERIC DEFAULT 0,
  "deposit_amount" NUMERIC DEFAULT 0,
  "deposit_note" TEXT,
  "cod_amount" NUMERIC DEFAULT 0,
  "amount_paid" NUMERIC DEFAULT 0,
  "debt_amount" NUMERIC DEFAULT 0,
  "credit_card_fee" NUMERIC DEFAULT 0,
  "profit_vnd" NUMERIC DEFAULT 0,
  "trade_in_laptop_id" INTEGER,
  "customer_id" INTEGER,
  "customer_info" TEXT,
  "customer_address" TEXT,
  "tracking_code" TEXT,
  "ship_date" TEXT,
  "setup_note" TEXT,
  "warranty" TEXT,
  "laptop_locked" INTEGER DEFAULT false CHECK ("laptop_locked" IN (0,1)),
  "reservation_expires_at" TEXT,
  "cancel_reason" TEXT,
  "cancelled_at" TEXT,
  "month_key" TEXT,
  "is_active" INTEGER DEFAULT true CHECK ("is_active" IN (0,1)),
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "returned_at" TEXT,
  "return_reason" TEXT,
  "branch_id" INTEGER,
  "gift_accessory_ids" TEXT DEFAULT '[]' NOT NULL CHECK ("gift_accessory_ids" IS NULL OR json_valid("gift_accessory_ids")),
  "gift_preset" TEXT DEFAULT '' NOT NULL,
  "cost_snapshot_vnd" NUMERIC,
  "gross_profit_snapshot_vnd" NUMERIC,
  "direct_cost_snapshot_vnd" NUMERIC,
  "net_contribution_snapshot_vnd" NUMERIC,
  "cost_snapshot_status" TEXT,
  "cost_snapshot_reasons" TEXT CHECK ("cost_snapshot_reasons" IS NULL OR json_valid("cost_snapshot_reasons")),
  "cost_snapshotted_at" TEXT,
  "payment_due_at" TEXT,
  "trade_in_credit_vnd" NUMERIC DEFAULT 0 NOT NULL,
  "requested_configuration" TEXT,
  "requested_category" TEXT,
  CONSTRAINT "orders_amount_paid_lte_sale_price_chk" CHECK (COALESCE(amount_paid, 0) >= 0 AND COALESCE(amount_paid, 0) <= COALESCE(sale_price, 0)),
  CONSTRAINT "orders_branch_id_fkey" FOREIGN KEY (branch_id) REFERENCES branches(id),
  CONSTRAINT "orders_cod_amount_lte_sale_price_chk" CHECK (COALESCE(cod_amount, 0) >= 0 AND COALESCE(cod_amount, 0) <= COALESCE(sale_price, 0)),
  CONSTRAINT "orders_cost_snapshot_status_check" CHECK (cost_snapshot_status IS NULL OR (cost_snapshot_status IN ('COMPLETE', 'INCOMPLETE', 'LEGACY'))),
  CONSTRAINT "orders_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT "orders_deposit_amount_lte_sale_price_chk" CHECK (COALESCE(deposit_amount, 0) >= 0 AND COALESCE(deposit_amount, 0) <= COALESCE(sale_price, 0)),
  CONSTRAINT "orders_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE SET NULL,
  CONSTRAINT "orders_non_negative_values" CHECK (COALESCE(sale_price, 0) >= 0 AND COALESCE(deposit_amount, 0) >= 0 AND COALESCE(cod_amount, 0) >= 0 AND COALESCE(amount_paid, 0) >= 0 AND COALESCE(debt_amount, 0) >= 0 AND COALESCE(credit_card_fee, 0) >= 0),
  CONSTRAINT "orders_payment_totals_valid" CHECK (COALESCE(amount_paid, 0) <= COALESCE(sale_price, 0) AND COALESCE(deposit_amount, 0) <= COALESCE(amount_paid, 0)),
  CONSTRAINT "orders_requested_laptop_id_fkey" FOREIGN KEY (requested_laptop_id) REFERENCES laptops(id) ON DELETE SET NULL,
  CONSTRAINT "orders_trade_in_credit_vnd_check" CHECK (trade_in_credit_vnd >= 0),
  CONSTRAINT "orders_trade_in_laptop_id_fkey" FOREIGN KEY (trade_in_laptop_id) REFERENCES laptops(id) ON DELETE SET NULL
);

CREATE TABLE "payments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_id" INTEGER NOT NULL,
  "payment_type" TEXT NOT NULL,
  "amount" NUMERIC NOT NULL,
  "payment_method" TEXT DEFAULT 'transfer_cash' NOT NULL,
  "payment_date" TEXT DEFAULT CURRENT_DATE NOT NULL,
  "reference_code" TEXT,
  "note" TEXT,
  "recorded_by" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "account_id" TEXT,
  "idempotency_key" TEXT,
  CONSTRAINT "payments_account_id_fkey" FOREIGN KEY (account_id) REFERENCES cash_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "payments_amount_check" CHECK (amount > 0),
  CONSTRAINT "payments_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
  CONSTRAINT "payments_payment_type_check" CHECK (payment_type IN ('deposit', 'balance', 'cod', 'refund', 'other'))
);

CREATE TABLE "purchase_batches" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "batch_code" TEXT NOT NULL,
  "supplier_id" TEXT NOT NULL,
  "purchase_date" TEXT NOT NULL,
  "currency" TEXT DEFAULT 'CNY' NOT NULL,
  "exchange_rate" NUMERIC NOT NULL,
  "subtotal_rmb" NUMERIC DEFAULT 0 NOT NULL,
  "domestic_shipping_rmb" NUMERIC DEFAULT 0 NOT NULL,
  "other_cost_rmb" NUMERIC DEFAULT 0 NOT NULL,
  "destination" TEXT DEFAULT 'OTHER' NOT NULL,
  "status" TEXT DEFAULT 'DRAFT' NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "active" INTEGER DEFAULT true NOT NULL CHECK ("active" IN (0,1)),
  "created_by" TEXT NOT NULL,
  "updated_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "idempotency_key" TEXT,
  "procurement_flow" TEXT DEFAULT 'LEGACY' NOT NULL,
  CONSTRAINT "purchase_batches_batch_code_key" UNIQUE (batch_code),
  CONSTRAINT "purchase_batches_currency_check" CHECK (currency = 'CNY'),
  CONSTRAINT "purchase_batches_destination_check" CHECK (destination IN ('YUNNAN', 'GUANGXI', 'OTHER')),
  CONSTRAINT "purchase_batches_domestic_shipping_rmb_check" CHECK (domestic_shipping_rmb >= 0),
  CONSTRAINT "purchase_batches_exchange_rate_check" CHECK (exchange_rate > 0),
  CONSTRAINT "purchase_batches_id_supplier_unique" UNIQUE (id, supplier_id),
  CONSTRAINT "purchase_batches_other_cost_rmb_check" CHECK (other_cost_rmb >= 0),
  CONSTRAINT "purchase_batches_procurement_flow_check" CHECK (procurement_flow IN ('LEGACY', 'DIRECT')),
  CONSTRAINT "purchase_batches_status_check" CHECK (status IN ('DRAFT', 'CONFIRMED', 'PARTIALLY_PAID', 'PAID', 'IN_TRANSIT_CN', 'AT_CN_WAREHOUSE', 'IN_TRANSIT_VN', 'RECEIVED', 'PARTIALLY_RECEIVED', 'CLOSED', 'CANCELLED')),
  CONSTRAINT "purchase_batches_subtotal_rmb_check" CHECK (subtotal_rmb >= 0),
  CONSTRAINT "purchase_batches_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT
);

CREATE TABLE "qc_check_items" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "qc_inspection_id" TEXT NOT NULL,
  "check_key" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "result" TEXT NOT NULL,
  "note" TEXT DEFAULT '' NOT NULL,
  "checked_by" TEXT NOT NULL,
  "checked_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "category" TEXT DEFAULT 'OTHER' NOT NULL,
  "requirement" TEXT DEFAULT 'REQUIRED' NOT NULL,
  "sort_order" INTEGER DEFAULT 0 NOT NULL,
  CONSTRAINT "qc_check_items_check_key_check" CHECK (length(check_key) BETWEEN 2 AND 60 AND check_key NOT GLOB '*[^a-z0-9_]*'),
  CONSTRAINT "qc_check_items_label_check" CHECK (length(trim(label)) >= 1 AND length(trim(label)) <= 120),
  CONSTRAINT "qc_check_items_qc_inspection_id_check_key_key" UNIQUE (qc_inspection_id, check_key),
  CONSTRAINT "qc_check_items_qc_inspection_id_fkey" FOREIGN KEY (qc_inspection_id) REFERENCES qc_inspections(id) ON DELETE CASCADE,
  CONSTRAINT "qc_check_items_requirement_check" CHECK (requirement IN ('REQUIRED', 'OPTIONAL', 'CONDITIONAL')),
  CONSTRAINT "qc_check_items_result_check" CHECK (result IN ('PASS', 'FAIL', 'WARNING', 'NOT_TESTED', 'NOT_APPLICABLE'))
);

CREATE TABLE "qc_inspections" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "inspection_code" TEXT NOT NULL,
  "laptop_id" INTEGER NOT NULL,
  "status" TEXT DEFAULT 'IN_PROGRESS' NOT NULL,
  "result" TEXT,
  "started_by" TEXT NOT NULL,
  "started_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "completed_by" TEXT,
  "completed_at" TEXT,
  "overall_notes" TEXT DEFAULT '' NOT NULL,
  "mainboard_status" TEXT DEFAULT 'UNKNOWN' NOT NULL,
  "charger_status" TEXT DEFAULT 'UNKNOWN' NOT NULL,
  "cosmetic_grade" TEXT,
  "idempotency_key" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "completion_idempotency_key" TEXT,
  "disposition" TEXT,
  "detail_snapshot" TEXT CHECK ("detail_snapshot" IS NULL OR json_valid("detail_snapshot")),
  CONSTRAINT "qc_inspections_charger_status_check" CHECK (charger_status IN ('ORIGINAL', 'ORIGINAL_US', 'COMPATIBLE', 'MISSING', 'UNKNOWN')),
  CONSTRAINT "qc_inspections_check" CHECK (status = 'IN_PROGRESS' AND result IS NULL AND completed_at IS NULL OR status = 'COMPLETED' AND result IS NOT NULL AND completed_at IS NOT NULL OR status = 'CANCELLED'),
  CONSTRAINT "qc_inspections_cosmetic_grade_check" CHECK (cosmetic_grade IS NULL OR (cosmetic_grade IN ('A', 'B', 'C', 'D'))),
  CONSTRAINT "qc_inspections_disposition_check" CHECK (disposition IN ('PASS', 'FAIL', 'REPAIR', 'RETURN_CN')),
  CONSTRAINT "qc_inspections_idempotency_key_check" CHECK (length(trim(idempotency_key)) >= 8 AND length(trim(idempotency_key)) <= 100),
  CONSTRAINT "qc_inspections_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "qc_inspections_inspection_code_key" UNIQUE (inspection_code),
  CONSTRAINT "qc_inspections_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE RESTRICT,
  CONSTRAINT "qc_inspections_mainboard_status_check" CHECK (mainboard_status IN ('ORIGINAL', 'OFFICIAL_REPLACED', 'REPAIRED', 'UNKNOWN')),
  CONSTRAINT "qc_inspections_pkey" PRIMARY KEY (id),
  CONSTRAINT "qc_inspections_result_check" CHECK (result IN ('PASS', 'FAIL')),
  CONSTRAINT "qc_inspections_status_check" CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE "repair_actions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "repair_job_id" TEXT NOT NULL,
  "action_type" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "performed_by" TEXT NOT NULL,
  "performed_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "repair_actions_action_type_check" CHECK (action_type IN ('DIAGNOSIS', 'CLEANING', 'PART_REPLACEMENT', 'BIOS', 'SOFTWARE', 'THERMAL_SERVICE', 'TEST', 'OTHER')),
  CONSTRAINT "repair_actions_repair_job_id_fkey" FOREIGN KEY (repair_job_id) REFERENCES repair_jobs(id) ON DELETE RESTRICT
);

CREATE TABLE "repair_jobs" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "repair_code" TEXT NOT NULL,
  "laptop_id" INTEGER NOT NULL,
  "source_type" TEXT NOT NULL,
  "source_id" TEXT,
  "status" TEXT DEFAULT 'OPEN' NOT NULL,
  "reported_issue" TEXT NOT NULL,
  "diagnosis" TEXT DEFAULT '' NOT NULL,
  "repair_plan" TEXT DEFAULT '' NOT NULL,
  "resolution" TEXT DEFAULT '' NOT NULL,
  "priority" TEXT DEFAULT 'NORMAL' NOT NULL,
  "assigned_to" TEXT,
  "started_at" TEXT,
  "completed_at" TEXT,
  "labor_cost_vnd" NUMERIC DEFAULT 0 NOT NULL,
  "parts_cost_vnd" NUMERIC DEFAULT 0 NOT NULL,
  "total_cost_vnd" NUMERIC GENERATED ALWAYS AS ((labor_cost_vnd + parts_cost_vnd)) STORED,
  "requires_re_qc" INTEGER DEFAULT true NOT NULL CHECK ("requires_re_qc" IN (0,1)),
  "notes" TEXT DEFAULT '' NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "completion_idempotency_key" TEXT,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "outcome" TEXT,
  "recommended_action" TEXT,
  CONSTRAINT "repair_jobs_assigned_to_fkey" FOREIGN KEY (assigned_to) REFERENCES user_profiles(id) ON DELETE RESTRICT,
  CONSTRAINT "repair_jobs_completion_idempotency_key_check" CHECK (completion_idempotency_key IS NULL OR length(trim(completion_idempotency_key)) >= 8 AND length(trim(completion_idempotency_key)) <= 100),
  CONSTRAINT "repair_jobs_completion_idempotency_key_key" UNIQUE (completion_idempotency_key),
  CONSTRAINT "repair_jobs_idempotency_key_check" CHECK (length(trim(idempotency_key)) >= 8 AND length(trim(idempotency_key)) <= 100),
  CONSTRAINT "repair_jobs_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "repair_jobs_labor_cost_vnd_check" CHECK (labor_cost_vnd >= 0),
  CONSTRAINT "repair_jobs_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE RESTRICT,
  CONSTRAINT "repair_jobs_outcome_check" CHECK (outcome IS NULL OR (outcome IN ('REPAIRED', 'NOT_REPAIRED', 'PARTIALLY_REPAIRED', 'NO_FAULT_FOUND'))),
  CONSTRAINT "repair_jobs_parts_cost_vnd_check" CHECK (parts_cost_vnd >= 0),
  CONSTRAINT "repair_jobs_pkey" PRIMARY KEY (id),
  CONSTRAINT "repair_jobs_priority_check" CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),
  CONSTRAINT "repair_jobs_recommended_action_check" CHECK (recommended_action IS NULL OR (recommended_action IN ('RE_QC', 'SUPPLIER_RETURN', 'NO_FURTHER_ACTION', 'OTHER'))),
  CONSTRAINT "repair_jobs_repair_code_key" UNIQUE (repair_code),
  CONSTRAINT "repair_jobs_reported_issue_check" CHECK (length(trim(reported_issue)) >= 1 AND length(trim(reported_issue)) <= 5000),
  CONSTRAINT "repair_jobs_source_type_check" CHECK (source_type IN ('QC', 'WARRANTY', 'TRADE_IN', 'INTERNAL')),
  CONSTRAINT "repair_jobs_status_check" CHECK (status IN ('OPEN', 'IN_PROGRESS', 'WAITING_PART', 'TESTING', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE "repair_parts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "repair_job_id" TEXT NOT NULL,
  "part_type" TEXT NOT NULL,
  "part_name" TEXT NOT NULL,
  "serial" TEXT,
  "quantity" INTEGER NOT NULL,
  "unit_cost_vnd" NUMERIC NOT NULL,
  "total_cost_vnd" NUMERIC GENERATED ALWAYS AS (((quantity) * unit_cost_vnd)) STORED,
  "source" TEXT NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "repair_parts_part_type_check" CHECK (part_type IN ('RAM', 'SSD', 'SCREEN', 'KEYBOARD', 'FAN', 'BATTERY', 'MAINBOARD', 'WIFI_CARD', 'CHARGER', 'HINGE', 'CABLE', 'THERMAL_MATERIAL', 'OTHER')),
  CONSTRAINT "repair_parts_quantity_check" CHECK (quantity > 0),
  CONSTRAINT "repair_parts_repair_job_id_fkey" FOREIGN KEY (repair_job_id) REFERENCES repair_jobs(id) ON DELETE RESTRICT,
  CONSTRAINT "repair_parts_source_check" CHECK (source IN ('STOCK', 'PURCHASED', 'CUSTOMER', 'SUPPLIER', 'OTHER')),
  CONSTRAINT "repair_parts_unit_cost_vnd_check" CHECK (unit_cost_vnd >= 0)
);

CREATE TABLE "reservations" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "reservation_code" TEXT NOT NULL,
  "laptop_id" INTEGER NOT NULL,
  "customer_id" INTEGER,
  "order_id" INTEGER,
  "status" TEXT NOT NULL,
  "reserved_by" TEXT,
  "reserved_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "expires_at" TEXT NOT NULL,
  "deposit_payment_id" INTEGER,
  "notes" TEXT DEFAULT '' NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "converted_at" TEXT,
  "expired_at" TEXT,
  "cancelled_at" TEXT,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "reservations_check" CHECK (expires_at > reserved_at),
  CONSTRAINT "reservations_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT "reservations_deposit_payment_id_fkey" FOREIGN KEY (deposit_payment_id) REFERENCES payments(id) ON DELETE SET NULL,
  CONSTRAINT "reservations_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "reservations_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE RESTRICT,
  CONSTRAINT "reservations_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT "reservations_pkey" PRIMARY KEY (id),
  CONSTRAINT "reservations_reservation_code_key" UNIQUE (reservation_code),
  CONSTRAINT "reservations_reserved_by_fkey" FOREIGN KEY (reserved_by) REFERENCES user_profiles(id) ON DELETE SET NULL,
  CONSTRAINT "reservations_status_check" CHECK (status IN ('ACTIVE', 'CONVERTED', 'EXPIRED', 'CANCELLED'))
);

CREATE TABLE "stock_movements" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "laptop_id" INTEGER,
  "movement_type" TEXT,
  "from_location" TEXT,
  "to_location" TEXT,
  "order_id" INTEGER,
  "warranty_case_id" INTEGER,
  "note" TEXT,
  "performed_by" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "reference_type" TEXT,
  "reference_id" TEXT,
  CONSTRAINT "stock_movements_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE SET NULL,
  CONSTRAINT "stock_movements_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT "stock_movements_warranty_case_id_fkey" FOREIGN KEY (warranty_case_id) REFERENCES warranty_cases(id) ON DELETE SET NULL
);

CREATE TABLE "supplier_payments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "supplier_id" TEXT NOT NULL,
  "purchase_batch_id" INTEGER NOT NULL,
  "amount_rmb" NUMERIC NOT NULL,
  "amount_vnd" NUMERIC NOT NULL,
  "exchange_rate" NUMERIC NOT NULL,
  "payment_method" TEXT NOT NULL,
  "reference" TEXT DEFAULT '' NOT NULL,
  "payment_date" TEXT NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "recorded_by" TEXT NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "account_id" TEXT,
  CONSTRAINT "supplier_payments_account_id_fkey" FOREIGN KEY (account_id) REFERENCES cash_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_payments_amount_rmb_check" CHECK (amount_rmb > 0),
  CONSTRAINT "supplier_payments_amount_vnd_check" CHECK (amount_vnd > 0),
  CONSTRAINT "supplier_payments_batch_supplier_fk" FOREIGN KEY (purchase_batch_id, supplier_id) REFERENCES purchase_batches(id, supplier_id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_payments_exchange_rate_check" CHECK (exchange_rate > 0),
  CONSTRAINT "supplier_payments_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "supplier_payments_idempotency_not_blank" CHECK (length(trim(idempotency_key)) >= 8 AND length(trim(idempotency_key)) <= 100),
  CONSTRAINT "supplier_payments_payment_method_check" CHECK (payment_method IN ('WECHAT', 'ALIPAY', 'BANK_TRANSFER', 'CASH', 'OTHER')),
  CONSTRAINT "supplier_payments_purchase_batch_id_fkey" FOREIGN KEY (purchase_batch_id) REFERENCES purchase_batches(id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_payments_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT
);

CREATE TABLE "supplier_refunds" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "supplier_id" TEXT NOT NULL,
  "supplier_return_id" TEXT NOT NULL,
  "amount_rmb" NUMERIC NOT NULL,
  "amount_vnd" NUMERIC,
  "exchange_rate" NUMERIC,
  "refund_method" TEXT NOT NULL,
  "reference" TEXT DEFAULT '' NOT NULL,
  "received_at" TEXT NOT NULL,
  "idempotency_key" TEXT NOT NULL,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "account_id" TEXT,
  CONSTRAINT "supplier_refunds_account_id_fkey" FOREIGN KEY (account_id) REFERENCES cash_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_refunds_amount_rmb_check" CHECK (amount_rmb > 0),
  CONSTRAINT "supplier_refunds_check" CHECK (amount_vnd IS NULL AND exchange_rate IS NULL OR amount_vnd >= 0 AND exchange_rate > 0),
  CONSTRAINT "supplier_refunds_idempotency_key_check" CHECK (length(trim(idempotency_key)) >= 8 AND length(trim(idempotency_key)) <= 100),
  CONSTRAINT "supplier_refunds_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "supplier_refunds_refund_method_check" CHECK (refund_method IN ('WECHAT', 'ALIPAY', 'BANK_TRANSFER', 'OFFSET', 'OTHER')),
  CONSTRAINT "supplier_refunds_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_refunds_supplier_return_id_fkey" FOREIGN KEY (supplier_return_id) REFERENCES supplier_returns(id) ON DELETE RESTRICT
);

CREATE TABLE "supplier_return_events" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "supplier_return_id" TEXT NOT NULL,
  "event_type" TEXT NOT NULL,
  "details" TEXT DEFAULT '{}' NOT NULL CHECK ("details" IS NULL OR json_valid("details")),
  "performed_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "supplier_return_events_supplier_return_id_fkey" FOREIGN KEY (supplier_return_id) REFERENCES supplier_returns(id) ON DELETE RESTRICT
);

CREATE TABLE "supplier_return_items" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "supplier_return_id" TEXT NOT NULL,
  "laptop_id" INTEGER NOT NULL,
  "repair_job_id" TEXT,
  "qc_inspection_id" TEXT,
  "reason" TEXT NOT NULL,
  "condition_notes" TEXT DEFAULT '' NOT NULL,
  "expected_refund_rmb" NUMERIC,
  "agreed_refund_rmb" NUMERIC,
  "replacement_laptop_id" INTEGER,
  "status" TEXT DEFAULT 'ACTIVE' NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "previous_laptop_status" TEXT,
  CONSTRAINT "supplier_return_items_agreed_refund_rmb_check" CHECK (agreed_refund_rmb IS NULL OR agreed_refund_rmb >= 0),
  CONSTRAINT "supplier_return_items_expected_refund_rmb_check" CHECK (expected_refund_rmb IS NULL OR expected_refund_rmb >= 0),
  CONSTRAINT "supplier_return_items_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_return_items_qc_inspection_id_fkey" FOREIGN KEY (qc_inspection_id) REFERENCES qc_inspections(id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_return_items_reason_check" CHECK (reason IN ('MAINBOARD_REPAIRED', 'WRONG_CONFIGURATION', 'HARDWARE_FAULT', 'SCREEN_FAULT', 'GPU_FAULT', 'FUNCTIONAL_FAILURE', 'PHYSICAL_DAMAGE', 'MISSING_ACCESSORY', 'SUPPLIER_AGREEMENT', 'OTHER')),
  CONSTRAINT "supplier_return_items_repair_job_id_fkey" FOREIGN KEY (repair_job_id) REFERENCES repair_jobs(id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_return_items_replacement_laptop_id_fkey" FOREIGN KEY (replacement_laptop_id) REFERENCES laptops(id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_return_items_status_check" CHECK (status IN ('ACTIVE', 'SHIPPED', 'SUPPLIER_RECEIVED', 'REFUNDED', 'REPLACED', 'REJECTED', 'CANCELLED')),
  CONSTRAINT "supplier_return_items_supplier_return_id_fkey" FOREIGN KEY (supplier_return_id) REFERENCES supplier_returns(id) ON DELETE RESTRICT,
  CONSTRAINT "supplier_return_items_supplier_return_id_laptop_id_key" UNIQUE (supplier_return_id, laptop_id)
);

CREATE TABLE "supplier_returns" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "return_code" TEXT NOT NULL,
  "supplier_id" TEXT NOT NULL,
  "status" TEXT DEFAULT 'DRAFT' NOT NULL,
  "resolution_type" TEXT,
  "reason" TEXT NOT NULL,
  "reason_notes" TEXT DEFAULT '' NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "return_carrier" TEXT DEFAULT '' NOT NULL,
  "return_tracking_number" TEXT DEFAULT '' NOT NULL,
  "created_by" TEXT NOT NULL,
  "approved_by" TEXT,
  "approved_at" TEXT,
  "shipped_at" TEXT,
  "supplier_received_at" TEXT,
  "closed_at" TEXT,
  "idempotency_key" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "supplier_returns_idempotency_key_check" CHECK (length(trim(idempotency_key)) >= 8 AND length(trim(idempotency_key)) <= 100),
  CONSTRAINT "supplier_returns_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "supplier_returns_pkey" PRIMARY KEY (id),
  CONSTRAINT "supplier_returns_reason_check" CHECK (reason IN ('MAINBOARD_REPAIRED', 'WRONG_CONFIGURATION', 'HARDWARE_FAULT', 'SCREEN_FAULT', 'GPU_FAULT', 'FUNCTIONAL_FAILURE', 'PHYSICAL_DAMAGE', 'MISSING_ACCESSORY', 'SUPPLIER_AGREEMENT', 'OTHER')),
  CONSTRAINT "supplier_returns_resolution_type_check" CHECK (resolution_type IS NULL OR (resolution_type IN ('REFUND', 'REPLACEMENT', 'PARTIAL_REFUND', 'SUPPLIER_REPAIR', 'OTHER'))),
  CONSTRAINT "supplier_returns_return_code_key" UNIQUE (return_code),
  CONSTRAINT "supplier_returns_status_check" CHECK (status IN ('DRAFT', 'APPROVED', 'READY_TO_SHIP', 'SHIPPED', 'SUPPLIER_RECEIVED', 'WAITING_REFUND', 'WAITING_REPLACEMENT', 'PARTIALLY_RESOLVED', 'REFUNDED', 'REPLACED', 'REJECTED', 'CLOSED', 'CANCELLED')),
  CONSTRAINT "supplier_returns_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT
);

CREATE TABLE "suppliers" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "display_name" TEXT DEFAULT '' NOT NULL,
  "wechat_name" TEXT DEFAULT '' NOT NULL,
  "wechat_id" TEXT DEFAULT '' NOT NULL,
  "phone" TEXT DEFAULT '' NOT NULL,
  "country" TEXT DEFAULT 'Trung Quá»‘c' NOT NULL,
  "province" TEXT DEFAULT '' NOT NULL,
  "city" TEXT DEFAULT '' NOT NULL,
  "address" TEXT DEFAULT '' NOT NULL,
  "bank_name" TEXT DEFAULT '' NOT NULL,
  "bank_account_name" TEXT DEFAULT '' NOT NULL,
  "bank_account_number" TEXT DEFAULT '' NOT NULL,
  "alipay_account" TEXT DEFAULT '' NOT NULL,
  "preferred_shipping_destination" TEXT DEFAULT 'OTHER' NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  "active" INTEGER DEFAULT true NOT NULL CHECK ("active" IN (0,1)),
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "suppliers_code_check" CHECK (length(code) BETWEEN 2 AND 40 AND code NOT GLOB '*[^A-Z0-9_-]*'),
  CONSTRAINT "suppliers_code_key" UNIQUE (code),
  CONSTRAINT "suppliers_name_check" CHECK (length(trim(name)) >= 1 AND length(trim(name)) <= 200),
  CONSTRAINT "suppliers_pkey" PRIMARY KEY (id),
  CONSTRAINT "suppliers_preferred_shipping_destination_check" CHECK (preferred_shipping_destination IN ('YUNNAN', 'GUANGXI', 'OTHER'))
);

CREATE TABLE "trade_in_check_items" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "inspection_id" TEXT NOT NULL,
  "check_key" TEXT NOT NULL,
  "result" TEXT NOT NULL,
  "notes" TEXT DEFAULT '' NOT NULL,
  CONSTRAINT "trade_in_check_items_inspection_id_check_key_key" UNIQUE (inspection_id, check_key),
  CONSTRAINT "trade_in_check_items_inspection_id_fkey" FOREIGN KEY (inspection_id) REFERENCES trade_in_inspections(id) ON DELETE RESTRICT,
  CONSTRAINT "trade_in_check_items_result_check" CHECK (result IN ('PASS', 'FAIL', 'WARNING', 'NOT_TESTED'))
);

CREATE TABLE "trade_in_inspections" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "trade_in_id" TEXT NOT NULL,
  "status" TEXT DEFAULT 'IN_PROGRESS' NOT NULL,
  "mainboard_status" TEXT DEFAULT 'UNKNOWN' NOT NULL,
  "findings" TEXT DEFAULT '' NOT NULL,
  "inspected_by" TEXT,
  "started_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "completed_at" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "trade_in_inspections_inspected_by_fkey" FOREIGN KEY (inspected_by) REFERENCES user_profiles(id),
  CONSTRAINT "trade_in_inspections_mainboard_status_check" CHECK (mainboard_status IN ('ORIGINAL', 'OFFICIAL_REPLACED', 'REPAIRED', 'UNKNOWN')),
  CONSTRAINT "trade_in_inspections_pkey" PRIMARY KEY (id),
  CONSTRAINT "trade_in_inspections_status_check" CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
  CONSTRAINT "trade_in_inspections_trade_in_id_fkey" FOREIGN KEY (trade_in_id) REFERENCES trade_ins(id) ON DELETE RESTRICT
);

CREATE TABLE "trade_ins" (
  "id" TEXT DEFAULT (lower(hex(randomblob(4))) || '-' || lower(hex(randomblob(2))) || '-4' || substr(lower(hex(randomblob(2))),2) || '-' || substr('89ab',abs(random() % 4)+1,1) || substr(lower(hex(randomblob(2))),2) || '-' || lower(hex(randomblob(6)))) NOT NULL,
  "trade_in_code" TEXT NOT NULL,
  "customer_id" INTEGER,
  "order_id" INTEGER,
  "brand" TEXT NOT NULL,
  "model" TEXT NOT NULL,
  "serial" TEXT,
  "cpu" TEXT,
  "gpu" TEXT,
  "ram" TEXT,
  "ssd" TEXT,
  "status" TEXT NOT NULL,
  "estimated_value_vnd" NUMERIC,
  "agreed_value_vnd" NUMERIC,
  "reported_condition" TEXT,
  "notes" TEXT,
  "received_at" TEXT,
  "inventory_laptop_id" INTEGER,
  "idempotency_key" TEXT NOT NULL,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')) NOT NULL,
  CONSTRAINT "trade_ins_agreed_value_vnd_check" CHECK (agreed_value_vnd IS NULL OR agreed_value_vnd > 0),
  CONSTRAINT "trade_ins_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT "trade_ins_idempotency_key_key" UNIQUE (idempotency_key),
  CONSTRAINT "trade_ins_inventory_laptop_id_fkey" FOREIGN KEY (inventory_laptop_id) REFERENCES laptops(id) ON DELETE RESTRICT,
  CONSTRAINT "trade_ins_inventory_laptop_id_key" UNIQUE (inventory_laptop_id),
  CONSTRAINT "trade_ins_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT "trade_ins_order_id_key" UNIQUE (order_id),
  CONSTRAINT "trade_ins_pkey" PRIMARY KEY (id),
  CONSTRAINT "trade_ins_status_check" CHECK (status IN ('DRAFT', 'INSPECTING', 'QUOTED', 'ACCEPTED', 'REJECTED', 'RECEIVED', 'CONVERTED_TO_INVENTORY', 'CANCELLED')),
  CONSTRAINT "trade_ins_trade_in_code_key" UNIQUE (trade_in_code)
);

CREATE TABLE "user_profiles" (
  "id" TEXT NOT NULL,
  "name" TEXT,
  "role" TEXT DEFAULT 'SALES' NOT NULL,
  "is_active" INTEGER DEFAULT true CHECK ("is_active" IN (0,1)),
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  CONSTRAINT "user_profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth_users(id) ON DELETE CASCADE,
  CONSTRAINT "user_profiles_pkey" PRIMARY KEY (id),
  CONSTRAINT "user_profiles_role_check" CHECK (role IN ('ADMIN', 'SALES', 'TECH', 'TECHNICAL', 'STAFF'))
);

CREATE TABLE "warranty_cases" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "order_id" INTEGER,
  "laptop_id" INTEGER,
  "reported_issue" TEXT,
  "status" TEXT,
  "received_date" TEXT,
  "resolved_date" TEXT,
  "repair_cost" NUMERIC DEFAULT 0,
  "parts_replaced" TEXT,
  "diagnosis" TEXT,
  "resolution" TEXT,
  "resolution_note" TEXT,
  "notes" TEXT,
  "customer_info" TEXT,
  "handled_by" TEXT,
  "created_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  "updated_at" TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  CONSTRAINT "warranty_cases_laptop_id_fkey" FOREIGN KEY (laptop_id) REFERENCES laptops(id) ON DELETE SET NULL,
  CONSTRAINT "warranty_cases_order_id_fkey" FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT "warranty_cases_repair_cost_non_negative" CHECK (COALESCE(repair_cost, 0) >= 0)
);

CREATE INDEX account_reconciliations_account_idx ON account_reconciliations (account_id, reconciled_at DESC);

CREATE INDEX account_transactions_account_time_idx ON account_transactions (account_id, occurred_at DESC, id);

CREATE UNIQUE INDEX account_transactions_source_unique ON account_transactions (reference_type, reference_id, transaction_type);

CREATE INDEX activity_logs_entity_created_at_idx ON activity_logs (entity_type, entity_id, created_at DESC);

CREATE INDEX cod_receivables_status_due_idx ON cod_receivables (status, expected_settlement_at);

CREATE INDEX cod_settlements_receivable_idx ON cod_settlements (cod_receivable_id, settled_at, id);

CREATE UNIQUE INDEX commissions_source_unique ON commissions (order_id, beneficiary_type, COALESCE((beneficiary_user_id), beneficiary_name), commission_type) WHERE (status <> 'CANCELLED');

CREATE UNIQUE INDEX customers_phone_unique_ci_idx ON customers (lower(trim(phone))) WHERE ((phone IS NOT NULL) AND (trim(phone) <> ''));

CREATE INDEX financial_records_date_idx ON financial_records (occurred_on DESC, id DESC);

CREATE INDEX financial_records_order_idx ON financial_records (order_id, occurred_on DESC);

CREATE INDEX invoices_customer_idx ON invoices (customer_id);

CREATE INDEX invoices_laptop_idx ON invoices (laptop_id);

CREATE INDEX laptop_cost_components_laptop_idx ON laptop_cost_components (laptop_id, occurred_at, id);

CREATE UNIQUE INDEX laptop_cost_components_source_unique ON laptop_cost_components (laptop_id, source_type, source_id, cost_type) WHERE ((source_id IS NOT NULL) AND (voided_at IS NULL));

CREATE UNIQUE INDEX laptop_cost_components_trade_in_source_unique ON laptop_cost_components (source_id) WHERE ((source_type = 'TRADE_IN') AND (cost_type = 'TRADE_IN_ACQUISITION') AND (voided_at IS NULL));

CREATE INDEX idx_laptops_month_key ON laptops (month_key);

CREATE INDEX laptops_active_status_import_date_idx ON laptops (is_active, status, import_date DESC);

CREATE INDEX laptops_purchase_batch_idx ON laptops (purchase_batch_id, id);

CREATE UNIQUE INDEX laptops_serial_unique_ci_idx ON laptops (lower(trim((serial)))) WHERE ((serial IS NOT NULL) AND (trim((serial)) <> ''));

CREATE UNIQUE INDEX laptops_sku_unique ON laptops (sku);

CREATE INDEX laptops_status_received_idx ON laptops (status, received_at DESC, id DESC);

CREATE INDEX laptops_tracking_code_cn_idx ON laptops (lower(tracking_code_cn)) WHERE (trim(tracking_code_cn) <> '');

CREATE INDEX idx_orders_month_key ON orders (month_key);

CREATE INDEX orders_laptop_active_idx ON orders (laptop_id, is_active, order_status, payment_status);

CREATE INDEX orders_requested_laptop_idx ON orders (requested_laptop_id, is_active, order_status, payment_status);

CREATE UNIQUE INDEX payments_idempotency_unique ON payments (idempotency_key) WHERE (idempotency_key IS NOT NULL);

CREATE INDEX payments_order_date_idx ON payments (order_id, payment_date DESC, id DESC);

CREATE UNIQUE INDEX purchase_batches_idempotency_unique ON purchase_batches (idempotency_key) WHERE (idempotency_key IS NOT NULL);

CREATE INDEX purchase_batches_supplier_idx ON purchase_batches (supplier_id, purchase_date DESC);

CREATE UNIQUE INDEX qc_inspections_completion_idempotency_unique ON qc_inspections (completion_idempotency_key) WHERE (completion_idempotency_key IS NOT NULL);

CREATE INDEX qc_inspections_laptop_history_idx ON qc_inspections (laptop_id, started_at DESC);

CREATE UNIQUE INDEX qc_inspections_one_active_per_laptop ON qc_inspections (laptop_id) WHERE (status = 'IN_PROGRESS');

CREATE UNIQUE INDEX repair_jobs_one_active_per_laptop ON repair_jobs (laptop_id) WHERE (status NOT IN ('COMPLETED', 'CANCELLED'));

CREATE INDEX repair_jobs_status_idx ON repair_jobs (status, priority, created_at DESC);

CREATE UNIQUE INDEX reservations_one_active_laptop ON reservations (laptop_id) WHERE (status = 'ACTIVE');

CREATE INDEX reservations_status_expiry_idx ON reservations (status, expires_at);

CREATE INDEX stock_movements_laptop_created_at_idx ON stock_movements (laptop_id, created_at DESC);

CREATE INDEX supplier_payments_batch_idx ON supplier_payments (purchase_batch_id, payment_date, id);

CREATE INDEX supplier_refunds_return_idx ON supplier_refunds (supplier_return_id, received_at, id);

CREATE INDEX supplier_return_events_return_idx ON supplier_return_events (supplier_return_id, created_at, id);

CREATE UNIQUE INDEX supplier_return_items_one_active_laptop ON supplier_return_items (laptop_id) WHERE (status NOT IN ('REFUNDED', 'REPLACED', 'REJECTED', 'CANCELLED'));

CREATE UNIQUE INDEX supplier_return_items_replacement_laptop_unique ON supplier_return_items (replacement_laptop_id) WHERE (replacement_laptop_id IS NOT NULL);

CREATE INDEX supplier_return_items_return_idx ON supplier_return_items (supplier_return_id, status, id);

CREATE INDEX supplier_returns_supplier_status_idx ON supplier_returns (supplier_id, status, created_at DESC);

CREATE INDEX supplier_returns_tracking_idx ON supplier_returns (lower(return_tracking_number)) WHERE (trim(return_tracking_number) <> '');

CREATE UNIQUE INDEX trade_in_one_open_inspection ON trade_in_inspections (trade_in_id) WHERE (status = 'IN_PROGRESS');

CREATE UNIQUE INDEX trade_ins_serial_active_unique ON trade_ins (lower(serial)) WHERE ((serial IS NOT NULL) AND (status NOT IN ('REJECTED', 'CANCELLED')));

CREATE INDEX warranty_cases_laptop_created_at_idx ON warranty_cases (laptop_id, created_at DESC);

CREATE UNIQUE INDEX warranty_cases_one_open_per_laptop_idx ON warranty_cases (laptop_id) WHERE (status IN ('received', 'checking', 'wait_parts', 'repairing'));
