-- Generated by node qa/build-d1-views.mjs from the final PostgreSQL catalog.

CREATE VIEW cash_account_balances AS
SELECT a.id,
    a.code,
    a.name,
    a.account_type,
    a.currency,
    a.opening_balance,
    a.opening_balance_at,
    a.is_active,
    a.created_by,
    a.created_at,
    a.updated_at,
    (COALESCE(t.inflow, (0))) AS inflow,
    (COALESCE(t.outflow, (0))) AS outflow,
    (((a.opening_balance + COALESCE(t.inflow, (0))) - COALESCE(t.outflow, (0)))) AS recorded_balance,
    t.last_transaction_at,
    r.last_reconciled_at,
    r.last_difference
   FROM ((cash_accounts a
     LEFT JOIN ( SELECT x.account_id,
            sum(x.amount) FILTER (WHERE (x.direction = 'IN')) AS inflow,
            sum(x.amount) FILTER (WHERE (x.direction = 'OUT')) AS outflow,
            max(x.occurred_at) AS last_transaction_at
           FROM (account_transactions x
             JOIN cash_accounts ca ON ((ca.id = x.account_id)))
          WHERE (x.occurred_at >= ca.opening_balance_at)
          GROUP BY x.account_id) t ON ((t.account_id = a.id)))
     LEFT JOIN (SELECT account_id,reconciled_at AS last_reconciled_at,difference AS last_difference,
        row_number() OVER (PARTITION BY account_id ORDER BY reconciled_at DESC,id DESC) AS position
        FROM account_reconciliations) r ON (r.account_id=a.id AND r.position=1));

CREATE VIEW cod_receivable_summaries AS
SELECT c.id,
    c.order_id,
    c.carrier,
    c.tracking_number,
    c.expected_cod_amount_vnd,
    c.status,
    c.shipped_at,
    c.delivered_at,
    c.expected_settlement_at,
    c.settled_at,
    c.notes,
    c.idempotency_key,
    c.created_by,
    c.created_at,
    c.updated_at,
    (COALESCE(s.settled_vnd, (0))) AS settled_vnd,
    (max((c.expected_cod_amount_vnd - COALESCE(s.settled_vnd, (0))), (0))) AS outstanding_vnd,
    o.customer_id,
    o.sale_price,
    o.amount_paid,
    o.debt_amount
   FROM ((cod_receivables c
     JOIN orders o ON ((o.id = c.order_id)))
     LEFT JOIN ( SELECT cod_settlements.cod_receivable_id,
            sum(cod_settlements.amount_vnd) AS settled_vnd
           FROM cod_settlements
          GROUP BY cod_settlements.cod_receivable_id) s ON ((s.cod_receivable_id = c.id)));

CREATE VIEW customer_receivable_summaries AS
SELECT o.id AS order_id,
    o.customer_id,
    c.name AS customer_name,
    c.phone AS customer_phone,
    o.sale_price,
    o.amount_paid,
    o.debt_amount,
    o.payment_due_at,
    o.created_date,
    o.sale_online AS salesperson,
    ( SELECT max(p.payment_date) AS max
           FROM payments p
          WHERE (p.order_id = o.id)) AS last_payment_date,
        CASE
            WHEN (o.payment_due_at IS NULL) THEN 'NO_DUE_DATE'
            WHEN (julianday(o.payment_due_at) >= julianday('now')) THEN 'NOT_DUE'
            WHEN (julianday('now') - julianday(o.payment_due_at) <= 7) THEN 'OVERDUE_1_7'
            WHEN (julianday('now') - julianday(o.payment_due_at) <= 30) THEN 'OVERDUE_8_30'
            WHEN (julianday('now') - julianday(o.payment_due_at) <= 60) THEN 'OVERDUE_31_60'
            ELSE 'OVERDUE_60_PLUS'
        END AS aging_bucket
   FROM (orders o
     LEFT JOIN customers c ON ((c.id = o.customer_id)))
  WHERE (o.is_active AND (o.debt_amount > (0)) AND ((o.order_status) NOT IN (('cancelled'), ('returned'))) AND ((o.payment_status) <> 'refunded'));

CREATE VIEW laptop_landed_costs AS
WITH component_sums AS (
         SELECT laptop_cost_components.laptop_id,
            sum(laptop_cost_components.amount_vnd) FILTER (WHERE (laptop_cost_components.cost_type = 'TRADE_IN_ACQUISITION')) AS trade_in_cost_vnd,
            sum(laptop_cost_components.amount_vnd) FILTER (WHERE (laptop_cost_components.cost_type = 'VN_SHIPPING')) AS vn_shipping_vnd,
            sum(laptop_cost_components.amount_vnd) FILTER (WHERE (laptop_cost_components.cost_type = 'REPAIR')) AS repair_cost_vnd,
            sum(laptop_cost_components.amount_vnd) FILTER (WHERE (laptop_cost_components.cost_type IN ('RAM_UPGRADE', 'SSD_UPGRADE'))) AS upgrade_cost_vnd,
            sum(laptop_cost_components.amount_vnd) FILTER (WHERE (laptop_cost_components.cost_type = 'ACCESSORY')) AS accessory_cost_vnd,
            sum(laptop_cost_components.amount_vnd) FILTER (WHERE (laptop_cost_components.cost_type IN ('CLEANING', 'OTHER', 'PAYMENT_FEE'))) AS other_cost_vnd,
            sum(laptop_cost_components.amount_vnd) FILTER (WHERE (laptop_cost_components.cost_type = 'REFUND_CREDIT')) AS refund_credit_vnd
           FROM laptop_cost_components
          WHERE (laptop_cost_components.voided_at IS NULL)
          GROUP BY laptop_cost_components.laptop_id
        ), calculated AS (
         SELECT l.id,
            l.serial,
            l.name,
            l.category,
            l.import_date,
            l.warehouse_date,
            l.location,
            l.charger_status,
            l.status,
            l.price_rmb,
            l.shipping_rmb,
            l.exchange_rate,
            l.import_price_vnd,
            l.wholesale_price_vnd,
            l.retail_price_vnd,
            l.tracking_code,
            l.customer_note,
            l.battery_health,
            l.warranty_supplier,
            l.screen_status,
            l.camera_mic_status,
            l.mainboard_status,
            l.condition_note,
            l.seller,
            l.is_active,
            l.parts_history,
            l.month_key,
            l.created_at,
            l.updated_at,
            l.sku,
            l.available_for_sale_at,
            l.source_type,
            l.source_reference_id,
            l.purchase_batch_id,
            l.tracking_code_cn,
            l.purchase_price_rmb,
            l.purchase_exchange_rate,
            l.received_at,
            l.sold_at,
            l.ignored_at,
            l.ignored_by,
            l.ignore_reason,
            l.created_by,
                CASE
                    WHEN (l.source_type = 'TRADE_IN') THEN COALESCE(c.trade_in_cost_vnd, (0))
                    WHEN (l.purchase_exchange_rate IS NOT NULL) THEN round((l.purchase_price_rmb * l.purchase_exchange_rate), 2)
                    ELSE (0)
                END AS purchase_cost_vnd,
                CASE
                    WHEN (l.purchase_exchange_rate IS NOT NULL) THEN round((l.shipping_rmb * l.purchase_exchange_rate), 2)
                    ELSE (0)
                END AS cn_shipping_vnd,
            c.vn_shipping_vnd,
            c.repair_cost_vnd,
            c.upgrade_cost_vnd,
            c.accessory_cost_vnd,
            c.other_cost_vnd,
            c.refund_credit_vnd,
                CASE
                    WHEN (l.source_type = 'UNKNOWN') THEN 'INCOMPLETE'
                    WHEN ((l.source_type IN ('SUPPLIER_PURCHASE', 'SUPPLIER_REPLACEMENT')) AND ((l.purchase_batch_id IS NULL) OR (l.purchase_exchange_rate IS NULL))) THEN 'INCOMPLETE'
                    WHEN ((l.source_type = 'TRADE_IN') AND (COALESCE(c.trade_in_cost_vnd, (0)) <= (0))) THEN 'INCOMPLETE'
                    WHEN (EXISTS ( SELECT 1
                       FROM repair_jobs r
                      WHERE ((r.laptop_id = l.id) AND (r.status NOT IN ('COMPLETED', 'CANCELLED'))))) THEN 'INCOMPLETE'
                    ELSE 'COMPLETE'
                END AS cost_status
           FROM (laptops l
             LEFT JOIN component_sums c ON ((c.laptop_id = l.id)))
        )
 SELECT id AS laptop_id,
    (COALESCE(purchase_cost_vnd, (0))) AS purchase_cost_vnd,
    (COALESCE(cn_shipping_vnd, (0))) AS cn_shipping_vnd,
    (COALESCE(vn_shipping_vnd, (0))) AS vn_shipping_vnd,
    (COALESCE(repair_cost_vnd, (0))) AS repair_cost_vnd,
    (COALESCE(upgrade_cost_vnd, (0))) AS upgrade_cost_vnd,
    (COALESCE(accessory_cost_vnd, (0))) AS accessory_cost_vnd,
    (COALESCE(other_cost_vnd, (0))) AS other_cost_vnd,
    (COALESCE(refund_credit_vnd, (0))) AS refund_credit_vnd,
    (max((((((((COALESCE(purchase_cost_vnd, (0)) + COALESCE(cn_shipping_vnd, (0))) + COALESCE(vn_shipping_vnd, (0))) + COALESCE(repair_cost_vnd, (0))) + COALESCE(upgrade_cost_vnd, (0))) + COALESCE(accessory_cost_vnd, (0))) + COALESCE(other_cost_vnd, (0))) - COALESCE(refund_credit_vnd, (0))), (0))) AS landed_cost_vnd,
    cost_status,
    (SELECT json_group_array(value) FROM json_each(json_array(
        CASE
            WHEN (source_type = 'UNKNOWN') THEN 'UNKNOWN_SOURCE'
            ELSE NULL
        END,
        CASE
            WHEN ((source_type IN ('SUPPLIER_PURCHASE', 'SUPPLIER_REPLACEMENT')) AND (purchase_batch_id IS NULL)) THEN 'MISSING_PURCHASE_BATCH'
            ELSE NULL
        END,
        CASE
            WHEN ((source_type IN ('SUPPLIER_PURCHASE', 'SUPPLIER_REPLACEMENT')) AND (purchase_exchange_rate IS NULL)) THEN 'MISSING_EXCHANGE_RATE'
            ELSE NULL
        END,
        CASE
            WHEN ((source_type = 'TRADE_IN') AND (purchase_cost_vnd <= (0))) THEN 'MISSING_TRADE_IN_ACQUISITION'
            ELSE NULL
        END,
        CASE
            WHEN (EXISTS ( SELECT 1
               FROM repair_jobs r
              WHERE ((r.laptop_id = calculated.id) AND (r.status NOT IN ('COMPLETED', 'CANCELLED'))))) THEN 'ACTIVE_REPAIR_COST_PENDING'
            ELSE NULL
        END)) WHERE value IS NOT NULL) AS reasons
   FROM calculated;

CREATE VIEW order_sales_operations_summary AS
SELECT o.id AS order_id,
    (o.sale_price * (1000000)) AS sale_revenue_vnd,
    o.trade_in_credit_vnd,
    (o.debt_amount * (1000000)) AS customer_outstanding_vnd,
    o.gross_profit_snapshot_vnd,
    o.net_contribution_snapshot_vnd,
    COALESCE(sum(c.amount_vnd) FILTER (WHERE (c.status IN ('APPROVED', 'PAID'))), (0)) AS commission_cost_vnd,
    (o.net_contribution_snapshot_vnd - COALESCE(sum(c.amount_vnd) FILTER (WHERE (c.status IN ('APPROVED', 'PAID'))), (0))) AS net_contribution_after_commission_vnd
   FROM (orders o
     LEFT JOIN commissions c ON ((c.order_id = o.id)))
  GROUP BY o.id;

CREATE VIEW purchase_batch_summaries AS
SELECT b.id,
    b.batch_code,
    b.supplier_id,
    b.purchase_date,
    b.notes,
    b.created_by,
    b.created_at,
    b.updated_at,
    b.idempotency_key,
    s.code AS supplier_code,
    s.name AS supplier_name,
    COALESCE(x.laptop_count, (0)) AS item_count,
    COALESCE(x.received_count, (0)) AS received_count,
    COALESCE(x.pending_count, (0)) AS pending_count,
    COALESCE(x.ignored_count, (0)) AS ignored_count,
    (COALESCE(x.purchase_total_rmb, (0))) AS subtotal_rmb,
    (COALESCE(x.purchase_total_rmb, (0))) AS purchase_total_rmb,
    (COALESCE(x.shipping_total_rmb, (0))) AS shipping_total_rmb,
    (COALESCE(x.purchase_total_rmb, (0))) AS total_rmb,
    (COALESCE(p.paid_rmb, (0))) AS paid_rmb,
    (max((COALESCE(x.purchase_total_rmb, (0)) - COALESCE(p.paid_rmb, (0))), (0))) AS debt_rmb,
        CASE
            WHEN (COALESCE(x.pending_count, (0)) = 0) THEN 'RECEIVED'
            WHEN (COALESCE(x.received_count, (0)) > 0) THEN 'PARTIALLY_RECEIVED'
            ELSE 'IN_TRANSIT'
        END AS status
   FROM (((purchase_batches b
     JOIN suppliers s ON ((s.id = b.supplier_id)))
     LEFT JOIN ( SELECT laptops.purchase_batch_id,
            count(*) AS laptop_count,
            count(*) FILTER (WHERE (laptops.received_at IS NOT NULL)) AS received_count,
            count(*) FILTER (WHERE ((laptops.status) = 'in_transit')) AS pending_count,
            count(*) FILTER (WHERE ((laptops.status) = 'ignored')) AS ignored_count,
            sum(laptops.purchase_price_rmb) FILTER (WHERE ((laptops.status) <> 'ignored')) AS purchase_total_rmb,
            sum(laptops.shipping_rmb) FILTER (WHERE ((laptops.status) <> 'ignored')) AS shipping_total_rmb
           FROM laptops
          WHERE (laptops.purchase_batch_id IS NOT NULL)
          GROUP BY laptops.purchase_batch_id) x ON ((x.purchase_batch_id = b.id)))
     LEFT JOIN ( SELECT supplier_payments.purchase_batch_id,
            sum(supplier_payments.amount_rmb) AS paid_rmb
           FROM supplier_payments
          GROUP BY supplier_payments.purchase_batch_id) p ON ((p.purchase_batch_id = b.id)));

CREATE VIEW unified_inventory AS
SELECT CAST(l.id AS TEXT) AS entity_key,
    'LAPTOP' AS entity_type,
    l.id AS entity_id,
    l.id AS laptop_id,
    l.name,
    l.category,
    l.serial,
    l.tracking_code_cn,
    l.status AS display_status,
    l.status AS backend_status,
    s.name AS supplier_name,
    b.batch_code,
    l.received_at,
    l.warehouse_date,
    l.available_for_sale_at,
    b.purchase_date,
        CASE
            WHEN (b.purchase_date IS NULL) THEN NULL
            ELSE strftime('%m/%Y',b.purchase_date)
        END AS month_key,
    l.purchase_price_rmb,
    l.shipping_rmb,
    l.purchase_exchange_rate AS exchange_rate,
    l.charger_status,
    l.battery_health,
    l.warranty_supplier,
        CASE
            WHEN (l.purchase_exchange_rate IS NULL) THEN NULL
            ELSE round(((l.purchase_price_rmb + l.shipping_rmb) * l.purchase_exchange_rate), 2)
        END AS landed_cost_vnd,
    (l.source_type = 'UNKNOWN') AS source_unresolved,
    l.condition_note AS notes
   FROM ((laptops l
     LEFT JOIN purchase_batches b ON ((b.id = l.purchase_batch_id)))
     LEFT JOIN suppliers s ON ((s.id = b.supplier_id)));
