-- Seed the canonical Settings option catalog.
-- Existing rows win so this migration never overwrites administrator customizations.

INSERT INTO app_options (group_key, option_key, label, is_active, sort_order) VALUES
  ('laptopStatus', 'in_transit', 'Chưa về hàng', 1, 0),
  ('laptopStatus', 'waiting_qc', 'Chờ QC', 1, 1),
  ('laptopStatus', 'available', 'Sẵn hàng', 1, 2),
  ('laptopStatus', 'reserved', 'Đã giữ cho đơn', 1, 3),
  ('laptopStatus', 'sold', 'Đã bán', 1, 4),
  ('laptopStatus', 'supplier_return', 'Back lại NCC', 1, 5),
  ('laptopStatus', 'repair', 'Đang sửa chữa', 1, 6),
  ('laptopStatus', 'ignored', 'Bỏ qua', 1, 7),
  ('laptopLocation', 'store', 'CH', 1, 0),
  ('laptopLocation', 'wh', 'KHO', 1, 1),
  ('laptopLocation', 'wh_cn', 'KHO TQ', 1, 2),
  ('laptopLocation', 'repair', 'Sửa chữa', 1, 3),
  ('chargerStatus', 'with_charger', 'Có Sạc', 1, 0),
  ('chargerStatus', 'no_charger', 'Không Sạc', 1, 1),
  ('chargerStatus', 'shared_charger', 'Sạc Lô', 1, 2),
  ('chargerStatus', 'unchecked', 'Chưa Check', 1, 3),
  ('componentStatus', 'ok', 'OK', 1, 0),
  ('componentStatus', 'error', 'Lỗi / Có vấn đề', 1, 1),
  ('orderStatus', 'new', 'MỚI TẠO', 1, 0),
  ('orderStatus', 'deposited', 'ĐÃ CỌC / GIỮ MÁY', 1, 1),
  ('orderStatus', 'prepared', 'ĐÃ CHUẨN BỊ XONG', 1, 2),
  ('orderStatus', 'shipping', 'ĐANG GIAO HÀNG', 1, 3),
  ('orderStatus', 'done', 'HOÀN THÀNH', 1, 4),
  ('orderStatus', 'returned', 'BACK MÁY', 1, 5),
  ('orderStatus', 'cancelled', 'HỦY ĐƠN', 1, 6),
  ('paymentStatus', 'unpaid', 'CHƯA THANH TOÁN', 1, 0),
  ('paymentStatus', 'deposited', 'ĐÃ CỌC', 1, 1),
  ('paymentStatus', 'cod', 'ĐANG CHỜ COD', 1, 2),
  ('paymentStatus', 'paid', 'ĐÃ THANH TOÁN', 1, 3),
  ('paymentStatus', 'refunded', 'ĐÃ HOÀN TIỀN', 1, 4),
  ('deliveryStatus', 'preparing', 'ĐANG CHUẨN BỊ', 1, 0),
  ('deliveryStatus', 'shipped', 'ĐÃ GỬI HÀNG', 1, 1),
  ('deliveryStatus', 'delivered', 'ĐÃ GIAO HÀNG', 1, 2),
  ('deliveryStatus', 'at_store', 'TẠI SHOP', 1, 3),
  ('deliveryStatus', 'returned', 'HOÀN HÀNG', 1, 4),
  ('orderType', 'retail', 'Bán lẻ (Retail)', 1, 0),
  ('orderType', 'wholesale', 'Bán sỉ/Thợ (Wholesale)', 1, 1),
  ('orderType', 'trade_in', 'Thu cũ đổi mới (Trade-in)', 1, 2),
  ('paymentMethod', 'transfer_cash', 'Chuyển khoản / Tiền mặt', 1, 0),
  ('paymentMethod', 'card', 'Quẹt thẻ (Tốn phí)', 1, 1),
  ('paymentMethod', 'installment', 'Trả góp', 1, 2),
  ('shippingMethod', 'viettelpost', 'ViettelPost', 1, 0),
  ('shippingMethod', 'shopee_spx', 'Shopee SPX', 1, 1),
  ('shippingMethod', 'direct_store', 'Trực tiếp Shop', 1, 2),
  ('shippingMethod', 'hcm_agent', 'Nhờ HCM giao dịch', 1, 3),
  ('shippingMethod', 'hai_an', 'Nhà xe Hải An', 1, 4),
  ('shippingMethod', 'shared_car', 'Xe Ghép', 1, 5),
  ('shippingMethod', 'direct_ship', 'Ship trực tiếp khách', 1, 6),
  ('shippingMethod', 'bus', 'Xe khách', 1, 7),
  ('category', '1', 'LEGION 5 2023', 1, 0),
  ('category', '2', 'ROG G513 2022', 1, 1),
  ('category', '3', 'ROG Scar 2022', 1, 2),
  ('category', '4', 'ROG Zephyrus G14', 1, 3),
  ('category', '5', 'LEGION 5 Pro 2022', 1, 4),
  ('category', '6', 'LEGION 5 Pro 2023 - 2024', 1, 5),
  ('category', '7', 'LEGION Slim 7', 1, 6),
  ('category', '8', 'ASUS TUF Gaming', 1, 7),
  ('category', '9', 'ROG M16 / G16', 1, 8),
  ('category', '10', 'ACER Nitro 5', 1, 9),
  ('saleOnline', '1', 'Thắng Tiktok', 1, 0),
  ('saleOnline', '2', 'Thắng Zalo', 1, 1),
  ('saleOnline', '3', 'Vương', 1, 2),
  ('saleOnline', '4', 'Quế Anh', 1, 3),
  ('saleOnline', '5', 'Quảng', 1, 4),
  ('saleOnline', '6', 'Linh', 1, 5),
  ('saleOnline', '7', 'Hoàng', 1, 6),
  ('saleOnline', '8', 'Tuấn', 1, 7),
  ('saleOnline', 'other', 'Khác', 1, 8),
  ('saleOffline', '1', 'Thắng', 1, 0),
  ('saleOffline', '2', 'Vương', 1, 1),
  ('saleOffline', 'other', 'Khác', 1, 2),
  ('warrantyCaseStatus', 'received', 'TIẾP NHẬN', 1, 0),
  ('warrantyCaseStatus', 'checking', 'ĐANG KIỂM TRA', 1, 1),
  ('warrantyCaseStatus', 'wait_parts', 'CHỜ LINH KIỆN', 1, 2),
  ('warrantyCaseStatus', 'repairing', 'ĐANG SỬA', 1, 3),
  ('warrantyCaseStatus', 'done', 'HOÀN TẤT', 1, 4),
  ('warrantyCaseStatus', 'swap_device', 'ĐỔI MÁY', 1, 5),
  ('warrantyCaseStatus', 'refunded', 'HOÀN TIỀN', 1, 6)
ON CONFLICT(group_key, option_key) DO NOTHING;
