'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Calculator, CirclePlus, Coins, RefreshCw, Search, Ship, X } from 'lucide-react';
import { getAuthHeaders } from '@/lib/apiFetchers';

const TYPE_LABELS = { PURCHASE:'Giá mua', CN_SHIPPING:'VC nội địa TQ', VN_SHIPPING:'VC về Việt Nam', PAYMENT_FEE:'Phí thanh toán', REPAIR:'Sửa chữa', RAM_UPGRADE:'Nâng cấp RAM', SSD_UPGRADE:'Nâng cấp SSD', ACCESSORY:'Phụ kiện', CLEANING:'Vệ sinh', OTHER:'Khác', REFUND_CREDIT:'Hoàn/giảm giá' };
const MANUAL_TYPES = ['RAM_UPGRADE','SSD_UPGRADE','ACCESSORY','CLEANING','OTHER'];
const REASON_LABELS = { LEGACY_NO_PURCHASE_LINEAGE:'Máy cũ chưa có nguồn mua', MISSING_EXCHANGE_RATE:'Thiếu tỷ giá lô mua', UNALLOCATED_SHIPPING:'Chưa phân bổ vận chuyển', ACTIVE_REPAIR_COST_PENDING:'Phiếu sửa chưa hoàn tất' };
const vnd = value => `${new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 0 }).format(Number(value || 0))} ₫`;

async function api(url, options={}) {
  const headers = await getAuthHeaders();
  const response = await fetch(url, { ...options, headers:{ ...headers, 'Content-Type':'application/json' } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Không thể xử lý yêu cầu');
  return data;
}

export default function Costs() {
  const [rows,setRows] = useState([]), [search,setSearch] = useState(''), [status,setStatus] = useState('');
  const [detail,setDetail] = useState(null), [error,setError] = useState(''), [saving,setSaving] = useState(false);
  const [shipmentId,setShipmentId] = useState(''), [allocation,setAllocation] = useState(null), [method,setMethod] = useState('EQUAL'), [costType,setCostType] = useState('VN_SHIPPING'), [exchangeRate,setExchangeRate] = useState('');
  const load = useCallback(async()=>{ try { setRows(await api('/api/costs')); setError(''); } catch(e) { setError(e.message); } },[]);
  useEffect(()=>{ api('/api/costs').then(setRows).catch(e=>setError(e.message)); },[]);
  const visible = useMemo(()=>rows.filter(row=>(!status||row.cost_status===status)&&`${row.laptops?.name||''} ${row.laptops?.serial||''} ${row.laptops?.location||''}`.toLowerCase().includes(search.toLowerCase())),[rows,search,status]);
  const totals = useMemo(()=>({ landed:rows.reduce((s,x)=>s+Number(x.landed_cost_vnd||0),0), incomplete:rows.filter(x=>x.cost_status==='INCOMPLETE').length, legacy:rows.filter(x=>x.cost_status==='LEGACY').length }),[rows]);
  const open = async row => { try { setDetail(await api(`/api/costs?laptopId=${row.laptop_id}`)); } catch(e) { setError(e.message); } };
  const refreshDetail = async laptopId => { setDetail(await api(`/api/costs?laptopId=${laptopId}`)); await load(); };
  const addCost = async e => { e.preventDefault(); const f=new FormData(e.currentTarget); setSaving(true); try { await api('/api/costs',{method:'POST',body:JSON.stringify({action:'add',laptopId:detail.summary.laptop_id,costType:f.get('costType'),amountVnd:f.get('amountVnd'),description:f.get('description'),idempotencyKey:crypto.randomUUID()})}); await refreshDetail(detail.summary.laptop_id); e.currentTarget.reset(); } catch(err) { setError(err.message); } finally { setSaving(false); } };
  const voidCost = async component => { const reason=window.prompt('Lý do void cấu phần chi phí'); if(!reason)return; setSaving(true); try { await api('/api/costs',{method:'POST',body:JSON.stringify({action:'void',id:component.id,reason})}); await refreshDetail(detail.summary.laptop_id); } catch(err){setError(err.message);} finally{setSaving(false);} };
  const loadShipment = async e => { e.preventDefault(); try { setAllocation(await api(`/api/cost-allocations?shipmentId=${shipmentId}`)); } catch(err){setError(err.message);} };
  const sourceAmount = allocation ? Math.round(Number(allocation.shipment?.shipping_cost_vnd||0) || Number(allocation.shipment?.shipping_cost_rmb||0)*Number(exchangeRate||0)) : 0;
  const finalize = async e => { e.preventDefault(); const f=new FormData(e.currentTarget),items=allocation.items.map(item=>({shipmentItemId:item.id,laptopId:item.laptop_id,amountVnd:method==='MANUAL'?f.get(`amount-${item.id}`):0})); setSaving(true); try { await api('/api/cost-allocations',{method:'POST',body:JSON.stringify({shipmentId:Number(shipmentId),costType,method,exchangeRate:exchangeRate||null,items,idempotencyKey:crypto.randomUUID()})}); setAllocation(await api(`/api/cost-allocations?shipmentId=${shipmentId}`)); await load(); } catch(err){setError(err.message);} finally{setSaving(false);} };
  return <div className="cost-page">
    <header className="cost-hero"><div><span>TRUE COST / PHASE 6</span><h1>Giá vốn thực tế</h1><p>Giá mua, vận chuyển, sửa chữa và nâng cấp được truy vết theo từng máy. Giá bán đã chốt giữ snapshot bất biến.</p></div><button onClick={load}><RefreshCw size={17}/> Đồng bộ danh sách</button></header>
    {error&&<div className="error-message">{error}<button onClick={()=>setError('')}>×</button></div>}
    <section className="cost-metrics"><article><Coins/><div><b>{vnd(totals.landed)}</b><span>Tổng landed cost</span></div></article><article><Calculator/><div><b>{rows.length}</b><span>Laptop được theo dõi</span></div></article><article className="warn"><b>{totals.incomplete}</b><span>Thiếu dữ liệu</span></article><article className="muted"><b>{totals.legacy}</b><span>Legacy</span></article></section>
    <section className="cost-toolbar"><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm tên, serial, vị trí"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option><option>COMPLETE</option><option>INCOMPLETE</option><option>LEGACY</option></select></section>
    <div className="cost-layout"><section className="cost-table-wrap"><table className="cost-table"><thead><tr><th>Laptop</th><th>Giá mua</th><th>Vận chuyển</th><th>Sửa / nâng cấp</th><th>Landed cost</th><th>Độ đầy đủ</th></tr></thead><tbody>{visible.map(row=><tr key={row.laptop_id} onClick={()=>open(row)}><td><b>{row.laptops?.name}</b><small>{row.laptops?.serial||'Chưa có serial'} · {row.laptops?.location||'—'}</small></td><td>{vnd(row.purchase_cost_vnd)}</td><td>{vnd(Number(row.cn_shipping_vnd)+Number(row.vn_shipping_vnd))}</td><td>{vnd(Number(row.repair_cost_vnd)+Number(row.upgrade_cost_vnd)+Number(row.accessory_cost_vnd)+Number(row.other_cost_vnd))}</td><td><strong>{vnd(row.landed_cost_vnd)}</strong></td><td><span className={`cost-status ${row.cost_status}`}>{row.cost_status}</span>{row.reasons?.map(reason=><small key={reason}>{REASON_LABELS[reason]||reason}</small>)}</td></tr>)}</tbody></table>{!visible.length&&<div className="cost-empty">Không có laptop phù hợp bộ lọc.</div>}</section>
      <aside className="allocation-panel"><header><Ship/><div><b>Phân bổ vận chuyển</b><span>Theo shipment đã nhận</span></div></header><form onSubmit={loadShipment}><label>Shipment ID<input type="number" min="1" value={shipmentId} onChange={e=>setShipmentId(e.target.value)} required/></label><button>Tải shipment</button></form>{allocation&&<form className="allocation-form" onSubmit={finalize}><div className="allocation-source"><b>{allocation.shipment?.shipment_code}</b><span>Nguồn duy nhất: {vnd(sourceAmount)}</span></div><label>Phân loại chặng<select value={costType} onChange={e=>setCostType(e.target.value)}><option value="CN_SHIPPING">Nội địa Trung Quốc</option><option value="VN_SHIPPING">Về Việt Nam</option></select></label><small>Mỗi shipment hiện có một tổng phí; chỉ được finalise một lần dưới phân loại đã chọn.</small><label>Phương pháp<select value={method} onChange={e=>setMethod(e.target.value)}><option value="EQUAL">Chia đều</option><option value="MANUAL">Nhập thủ công</option></select></label>{Number(allocation.shipment?.shipping_cost_vnd||0)<=0&&<label>Tỷ giá<input type="number" min="0.01" step="0.01" value={exchangeRate} onChange={e=>setExchangeRate(e.target.value)} required/></label>}<div className="allocation-items">{allocation.items.map(item=><label key={item.id}><span>{item.purchase_items?.model}<small>{item.purchase_items?.serial||`Laptop #${item.laptop_id}`}</small></span>{method==='MANUAL'&&<input name={`amount-${item.id}`} type="number" min="0" step="1" required/>}</label>)}</div>{allocation.allocations?.length>0&&<small>Đã finalise: {allocation.allocations.map(x=>`${x.cost_type} · ${x.status}`).join(', ')}</small>}<button disabled={saving||allocation.allocations?.some(x=>x.status!=='VOIDED')}>Finalise allocation</button></form>}</aside>
    </div>
    {detail&&<div className="modal-backdrop active"><div className="cost-drawer"><header><div><small>LAPTOP #{detail.summary.laptop_id}</small><h2>Breakdown giá vốn</h2><span className={`cost-status ${detail.summary.cost_status}`}>{detail.summary.cost_status}</span></div><button onClick={()=>setDetail(null)}><X/></button></header><div className="cost-total"><span>Landed cost hiện tại</span><b>{vnd(detail.summary.landed_cost_vnd)}</b></div><section className="cost-components">{detail.components.map(component=><article className={component.voided_at?'voided':''} key={component.id}><div><b>{TYPE_LABELS[component.cost_type]||component.cost_type}</b><small>{component.description} · {component.source_type}</small><small>{new Date(component.occurred_at).toLocaleString('vi-VN')}</small></div><strong>{component.cost_type==='REFUND_CREDIT'?'-':''}{vnd(component.amount_vnd)}</strong>{component.source_type==='MANUAL'&&!component.voided_at&&<button onClick={()=>voidCost(component)}>Void</button>}</article>)}</section><form className="cost-add-form" onSubmit={addCost}><h3><CirclePlus size={17}/> Thêm chi phí thủ công</h3><select name="costType">{MANUAL_TYPES.map(type=><option key={type} value={type}>{TYPE_LABELS[type]}</option>)}</select><input name="amountVnd" type="number" min="0" step="1" placeholder="Số tiền VND" required/><input name="description" placeholder="Mô tả / chứng từ" required/><button disabled={saving}>Ghi nhận</button></form></div></div>}
  </div>;
}
