'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Banknote, Landmark, RefreshCw, Scale, ShieldCheck, WalletCards } from 'lucide-react';
import { getAuthHeaders } from '@/lib/apiFetchers';
import { useAuth } from '@/context/AuthContext';

const money = (value, currency='VND') => new Intl.NumberFormat('vi-VN', { style:'currency', currency, maximumFractionDigits:currency==='VND'?0:2 }).format(Number(value||0));
const nowLocal = () => { const d=new Date(),offset=d.getTimezoneOffset()*60000;return new Date(d-offset).toISOString().slice(0,16); };
async function api(url,options={}) { const response=await fetch(url,{...options,headers:{...(await getAuthHeaders()),'Content-Type':'application/json',...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Không thể xử lý yêu cầu');return data; }
const tabs=[['overview','/finance','Tổng quan'],['cod','/finance/cod','COD'],['receivables','/finance/receivables','Phải thu'],['payables','/finance/payables','Phải trả'],['accounts','/finance/accounts','Tài khoản tiền'],['transactions','/finance/transactions','Giao dịch']];

export default function Finance({ mode='overview' }) {
  const { user } = useAuth();
  const authorized = user?.role === 'ADMIN';
  const [summary,setSummary]=useState(null),[rows,setRows]=useState([]),[accounts,setAccounts]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[page,setPage]=useState(1),[total,setTotal]=useState(0),[dialog,setDialog]=useState(''),[codDialog,setCodDialog]=useState(null);
  const load=useCallback(async()=>{if(!authorized){setLoading(false);return;}setLoading(true);setError('');try{const accountRows=await api('/api/cash-accounts');setAccounts(accountRows);if(mode==='overview')setSummary(await api('/api/financial-operations'));else if(mode==='accounts')setRows(accountRows);else{const endpoint=mode==='transactions'?'account-transactions':mode;const result=await api(`/api/${endpoint}?page=${page}&limit=30`);setRows(result.data||[]);setTotal(result.total||0);}}catch(e){setError(e.message);}finally{setLoading(false);}},[authorized,mode,page]);
  // Network synchronization intentionally refreshes server-owned finance data.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{load();},[load]);
  const byCurrency=useMemo(()=>({VND:accounts.filter(x=>x.currency==='VND').reduce((s,x)=>s+Number(x.recorded_balance||0),0),CNY:accounts.filter(x=>x.currency==='CNY').reduce((s,x)=>s+Number(x.recorded_balance||0),0)}),[accounts]);
  const submit=async(event,kind)=>{event.preventDefault();const form=new FormData(event.currentTarget),body=Object.fromEntries(form);try{if(kind==='account')await api('/api/cash-accounts',{method:'POST',body:JSON.stringify({code:body.code,name:body.name,accountType:body.accountType,currency:body.currency,openingBalance:body.openingBalance,openingBalanceAt:body.openingBalanceAt})});if(kind==='manual')await api('/api/account-transactions',{method:'POST',body:JSON.stringify({action:'manual',accountId:body.accountId,direction:body.direction,amount:body.amount,description:body.description,occurredAt:body.occurredAt,idempotencyKey:crypto.randomUUID()})});if(kind==='transfer')await api('/api/account-transactions',{method:'POST',body:JSON.stringify({action:'transfer',sourceAccountId:body.sourceAccountId,destinationAccountId:body.destinationAccountId,amount:body.amount,description:body.description,occurredAt:body.occurredAt,idempotencyKey:crypto.randomUUID()})});if(kind==='reconcile')await api('/api/account-reconciliations',{method:'POST',body:JSON.stringify({accountId:body.accountId,actualBalance:body.actualBalance,notes:body.notes})});if(kind==='cod')await api('/api/cod',{method:'POST',body:JSON.stringify({action:'create',orderId:body.orderId,carrier:body.carrier,trackingNumber:body.trackingNumber,expectedSettlementAt:body.expectedSettlementAt||null,notes:body.notes,idempotencyKey:crypto.randomUUID()})});setDialog('');await load();}catch(e){setError(e.message);}};
  const codAction=async(row,target)=>{if(['DELIVERED','SETTLE','DISPUTED'].includes(target)){setCodDialog({row,target});return;}try{await api('/api/cod',{method:'POST',body:JSON.stringify({action:'transition',id:row.id,target,expectedSettlementAt:null,notes:''})});await load();}catch(e){setError(e.message);}};
  const submitCodAction=async event=>{event.preventDefault();const form=new FormData(event.currentTarget),{row,target}=codDialog;try{if(target==='SETTLE')await api('/api/cod',{method:'POST',body:JSON.stringify({action:'settle',id:row.id,amountVnd:form.get('amountVnd'),accountId:form.get('accountId'),reference:form.get('reference'),settledAt:new Date().toISOString(),idempotencyKey:crypto.randomUUID()})});else await api('/api/cod',{method:'POST',body:JSON.stringify({action:'transition',id:row.id,target,expectedSettlementAt:target==='DELIVERED'?(form.get('expectedSettlementAt')||null):null,notes:form.get('notes')||''})});setCodDialog(null);await load();}catch(e){setError(e.message);}};
  if (!authorized) return <main className="finance-page"><div className="finance-empty" role="alert">Bạn không có quyền truy cập khu vực tài chính vận hành.</div></main>;
  return <main className="finance-page">
    <header className="finance-hero"><div><span>FINANCIAL OPERATIONS · PHASE 8</span><h1>Vị thế tiền vận hành</h1><p>Tiền được truy vết theo tài khoản; công nợ và lợi nhuận giữ nguyên nguồn sự thật riêng.</p></div><button onClick={load}><RefreshCw size={17}/> Đồng bộ</button></header>
    <nav className="finance-tabs">{tabs.map(([key,href,label])=><Link key={key} href={href} className={mode===key?'active':''}>{label}</Link>)}</nav>
    {error&&<div className="error-message">{error}<button onClick={()=>setError('')}>×</button></div>}
    {loading?<div className="finance-empty">Đang tải dữ liệu tài chính…</div>:mode==='overview'?<>
      <section className="finance-metrics"><article><WalletCards/><span>Recorded cash VND</span><b>{money(byCurrency.VND)}</b></article><article><Landmark/><span>Recorded cash CNY</span><b>{money(byCurrency.CNY,'CNY')}</b></article><article><ArrowDownLeft/><span>Khách còn phải trả</span><b>{money(summary?.customer_receivable_vnd)}</b><small>{summary?.customer_receivable_orders||0} đơn</small></article><article><ShieldCheck/><span>COD chưa về</span><b>{money(summary?.cod?.outstanding_vnd)}</b><small>Quá hạn {money(summary?.cod?.overdue_vnd)}</small></article><article><ArrowUpRight/><span>Phải trả NCC</span><b>{money(summary?.supplier_payable_cny,'CNY')}</b></article><article><Banknote/><span>NCC phải hoàn</span><b>{money(summary?.supplier_refund_pending_cny,'CNY')}</b></article></section>
      <section className="finance-account-board"><div><h2>Account balances</h2><p>Số dư ghi nhận, không phải số dư ngân hàng xác nhận.</p></div>{accounts.map(a=><article key={a.id}><span>{a.code} · {a.account_type}</span><b>{money(a.recorded_balance,a.currency)}</b><small>Đối soát: {a.last_reconciled_at?new Date(a.last_reconciled_at).toLocaleString('vi-VN'):'Chưa có'}{Number(a.last_difference)!==0?` · lệch ${money(a.last_difference,a.currency)}`:''}</small></article>)}</section>
    </>:<FinanceTable mode={mode} rows={rows} accounts={accounts} codAction={codAction}/>} 
    {mode==='accounts'&&<div className="finance-actions"><button onClick={()=>setDialog('account')}>Tạo tài khoản</button><button onClick={()=>setDialog('manual')}>Thu/chi thủ công</button><button onClick={()=>setDialog('transfer')}>Chuyển nội bộ</button><button onClick={()=>setDialog('reconcile')}>Đối soát</button></div>}
    {mode==='cod'&&<div className="finance-actions"><button onClick={()=>setDialog('cod')}>Tạo COD từ đơn hàng</button></div>}
    {total>30&&<footer className="finance-pager"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Trước</button><span>Trang {page} · {total} bản ghi</span><button disabled={page*30>=total} onClick={()=>setPage(p=>p+1)}>Sau</button></footer>}
    {dialog&&<FinanceDialog kind={dialog} accounts={accounts} submit={submit} close={()=>setDialog('')}/>} 
    {codDialog&&<CodActionDialog action={codDialog} accounts={accounts.filter(x=>x.currency==='VND')} submit={submitCodAction} close={()=>setCodDialog(null)}/>} 
  </main>;
}

function FinanceTable({mode,rows,accounts,codAction}) { if(!rows.length)return <div className="finance-empty">Chưa có dữ liệu phù hợp.</div>;return <div className="finance-table-wrap"><table><thead><tr>{mode==='cod'?<><th>Đơn / Khách</th><th>Vận chuyển</th><th>Expected</th><th>Settled</th><th>Remaining</th><th>Trạng thái</th><th>Thao tác</th></>:mode==='receivables'?<><th>Khách / Đơn</th><th>Giá bán</th><th>Đã trả</th><th>Còn nợ</th><th>Hạn</th><th>Tuổi nợ</th></>:mode==='payables'?<><th>NCC / Lô</th><th>Tổng CNY</th><th>Đã trả</th><th>Còn nợ</th><th>Ngày mua</th><th>Trạng thái</th></>:mode==='accounts'?<><th>Tài khoản</th><th>Loại</th><th>Tiền tệ</th><th>Opening</th><th>Số dư ghi nhận</th><th>Đối soát cuối</th></>:<><th>Ngày</th><th>Tài khoản</th><th>Hướng</th><th>Số tiền</th><th>Loại</th><th>Tham chiếu / mô tả</th><th>Người ghi</th></>}</tr></thead><tbody>{rows.map(row=><tr key={row.id||row.order_id}>{mode==='cod'?<><td><b>#{row.order_id}</b><small>{row.orders?.customer_info||'Chưa có tên khách'}</small></td><td>{row.carrier||'—'}<small>{row.tracking_number||'—'}</small></td><td>{money(row.expected_cod_amount_vnd)}</td><td>{money(row.settled_vnd)}</td><td><b>{money(row.outstanding_vnd)}</b></td><td>{row.status}</td><td><CodButtons row={row} act={codAction}/></td></>:mode==='receivables'?<><td><b>{row.customer_name||'Khách lẻ'}</b><small>#{row.order_id} · {row.customer_phone||'—'}</small></td><td>{money(Number(row.sale_price)*1000000)}</td><td>{money(Number(row.amount_paid)*1000000)}</td><td><b>{money(Number(row.debt_amount)*1000000)}</b></td><td>{row.payment_due_at?new Date(row.payment_due_at).toLocaleDateString('vi-VN'):'Không có'}</td><td>{row.aging_bucket}</td></>:mode==='payables'?<><td><b>{row.supplier_name}</b><small>{row.batch_code}</small></td><td>{money(row.total_rmb,'CNY')}</td><td>{money(row.paid_rmb,'CNY')}</td><td><b>{money(row.debt_rmb,'CNY')}</b></td><td>{row.purchase_date}</td><td>{row.status}</td></>:mode==='accounts'?<><td><b>{row.code}</b><small>{row.name}</small></td><td>{row.account_type}</td><td>{row.currency}</td><td>{money(row.opening_balance,row.currency)}<small>{new Date(row.opening_balance_at).toLocaleString('vi-VN')}</small></td><td><b>{money(row.recorded_balance,row.currency)}</b></td><td>{row.last_reconciled_at?new Date(row.last_reconciled_at).toLocaleString('vi-VN'):'Chưa có'}</td></>:<><td>{new Date(row.occurred_at).toLocaleString('vi-VN')}</td><td>{row.cash_accounts?.code}</td><td className={row.direction==='IN'?'finance-in':'finance-out'}>{row.direction}</td><td><b>{money(row.amount,row.currency)}</b></td><td>{row.transaction_type}</td><td>{row.reference_type} · {row.reference_id}<small>{row.description}</small></td><td>{row.created_by}</td></>}</tr>)}</tbody></table></div>}
function CodButtons({row,act}) { return <div className="finance-row-actions">{row.status==='PENDING_DELIVERY'&&<><button onClick={()=>act(row,'DELIVERED')}>Đã giao</button><button onClick={()=>act(row,'RETURNED')}>Hoàn</button></>}{row.status==='DELIVERED'&&<button onClick={()=>act(row,'WAITING_SETTLEMENT')}>Chờ đối soát</button>}{['WAITING_SETTLEMENT','PARTIALLY_SETTLED'].includes(row.status)&&<><button onClick={()=>act(row,'SETTLE')}>Nhận tiền</button><button onClick={()=>act(row,'DISPUTED')}>Tranh chấp</button></>}</div>}
function FinanceDialog({kind,accounts,submit,close}) { const cny=accounts.filter(x=>x.currency==='CNY'),vnd=accounts.filter(x=>x.currency==='VND');return <div className="modal-backdrop active"><form className="finance-dialog" onSubmit={e=>submit(e,kind)}><header><div><small>FINANCE CONTROL</small><h2>{kind==='account'?'Tạo tài khoản':kind==='manual'?'Giao dịch thủ công':kind==='transfer'?'Chuyển tiền nội bộ':kind==='cod'?'Tạo COD từ đơn hàng':'Đối soát tài khoản'}</h2></div><button type="button" onClick={close}>×</button></header>{kind==='account'?<><label>Mã<input name="code" required/></label><label>Tên<input name="name" required/></label><label>Loại<select name="accountType"><option>CASH</option><option>BANK</option><option>WECHAT</option><option>ALIPAY</option><option>OTHER</option></select></label><label>Tiền tệ<select name="currency"><option>VND</option><option>CNY</option></select></label><label>Opening balance<input name="openingBalance" type="number" min="0" step="0.01" required/></label><label>Thời điểm cutover<input name="openingBalanceAt" type="datetime-local" defaultValue={nowLocal()} required/></label></>:kind==='manual'?<><AccountSelect name="accountId" rows={accounts}/><label>Hướng<select name="direction"><option value="IN">Thu vào</option><option value="OUT">Chi ra</option></select></label><label>Số tiền<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Thời điểm<input name="occurredAt" type="datetime-local" defaultValue={nowLocal()} required/></label><label className="wide">Mô tả<input name="description" required/></label></>:kind==='transfer'?<><AccountSelect name="sourceAccountId" rows={accounts} label="Tài khoản nguồn"/><AccountSelect name="destinationAccountId" rows={accounts} label="Tài khoản đích (cùng tiền tệ)"/><label>Số tiền<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Thời điểm<input name="occurredAt" type="datetime-local" defaultValue={nowLocal()} required/></label><label className="wide">Mô tả<input name="description" required/></label><p className="wide">Chuyển VND ↔ CNY được hoãn trong Phase 8.</p></>:kind==='cod'?<><label>Order ID<input name="orderId" inputMode="numeric" required/></label><label>Đơn vị vận chuyển<input name="carrier" required/></label><label>Mã vận đơn<input name="trackingNumber" required/></label><label>Ngày dự kiến tiền về<input name="expectedSettlementAt" type="datetime-local"/></label><label className="wide">Ghi chú<textarea name="notes"/></label></>:<><AccountSelect name="accountId" rows={[...vnd,...cny]}/><label>Số dư quan sát<input name="actualBalance" type="number" step="0.01" required/></label><label className="wide">Ghi chú<textarea name="notes"/></label></>}<footer><button type="button" onClick={close}>Đóng</button><button>Xác nhận</button></footer></form></div>}
function AccountSelect({name,rows,label='Tài khoản'}) { return <label>{label}<select name={name} required><option value="">Chọn tài khoản</option>{rows.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name} · {a.currency}</option>)}</select></label>}
function CodActionDialog({action,accounts,submit,close}) { const {row,target}=action;return <div className="modal-backdrop active"><form className="finance-dialog" onSubmit={submit}><header><div><small>COD CONTROL · ORDER #{row.order_id}</small><h2>{target==='DELIVERED'?'Xác nhận đã giao':target==='SETTLE'?'Ghi nhận tiền COD':'Ghi nhận tranh chấp'}</h2></div><button type="button" onClick={close}>×</button></header>{target==='DELIVERED'?<><label>Ngày dự kiến tiền về<input name="expectedSettlementAt" type="datetime-local"/></label><label className="wide">Ghi chú<textarea name="notes"/></label></>:target==='SETTLE'?<><AccountSelect name="accountId" rows={accounts}/><label>Số tiền VND<input name="amountVnd" type="number" min="1" step="1" max={row.outstanding_vnd} defaultValue={row.outstanding_vnd} required/></label><label className="wide">Tham chiếu<input name="reference"/></label></>:<label className="wide">Lý do tranh chấp<textarea name="notes" required/></label>}<footer><button type="button" onClick={close}>Đóng</button><button>Xác nhận</button></footer></form></div>}
