'use client';
import { useEffect, useMemo, useState } from 'react';
import { ClipboardCheck, Play, ShieldCheck, ShieldX, Wrench, X } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { getAuthHeaders } from '@/lib/apiFetchers';

const CHECKS=[['serial','Serial'],['model','Model'],['cpu','CPU'],['gpu','GPU'],['ram','RAM'],['ssd','SSD'],['mainboard','Mainboard'],['screen','Màn hình'],['keyboard','Bàn phím'],['touchpad','Touchpad'],['camera','Camera'],['wifi','WiFi'],['bluetooth','Bluetooth'],['speaker','Loa'],['microphone','Microphone'],['usb','USB'],['usb_c','USB-C'],['hdmi','HDMI'],['battery','Pin'],['ssd_health','Sức khỏe SSD'],['cpu_stress','CPU stress'],['gpu_stress','GPU stress'],['cooling','Tản nhiệt'],['fan','Quạt'],['charger','Sạc'],['exterior','Ngoại hình']];
const RESULTS=['PASS','FAIL','WARNING','NOT_TESTED','NOT_APPLICABLE'];
const LABEL={PASS:'Đạt',FAIL:'Lỗi',WARNING:'Cảnh báo',NOT_TESTED:'Chưa test',NOT_APPLICABLE:'Không áp dụng'};
async function request(url,options={}){const res=await fetch(url,{...options,headers:await getAuthHeaders()});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Không thể xử lý yêu cầu');return data}

export default function QC(){
 const router=useRouter();
 const [laptops,setLaptops]=useState([]),[history,setHistory]=useState([]),[active,setActive]=useState(null),[items,setItems]=useState([]),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{const [ls,hs]=await Promise.all([request('/api/inventory?all=true'),request('/api/qc')]);setLaptops(ls.filter(x=>['waiting_qc','qc_in_progress','qc_failed'].includes(String(x.status).toLowerCase())));setHistory(hs);setError('')}catch(e){setError(e.message)}};useEffect(()=>{Promise.all([request('/api/inventory?all=true'),request('/api/qc')]).then(([ls,hs])=>{setLaptops(ls.filter(x=>['waiting_qc','qc_in_progress','qc_failed'].includes(String(x.status).toLowerCase())));setHistory(hs)}).catch(e=>setError(e.message))},[]);
 const counts=useMemo(()=>items.reduce((a,x)=>(a[x.result]=(a[x.result]||0)+1,a),{}),[items]);
 const open=async q=>{try{const d=await request(`/api/qc?id=${q.id}`);setActive(d.inspection);setItems(d.items.length?d.items.map(x=>({checkKey:x.check_key,label:x.label,result:x.result,note:x.note})):CHECKS.map(([checkKey,label])=>({checkKey,label,result:'NOT_TESTED',note:''})))}catch(e){setError(e.message)}};
 const start=async laptop=>{setSaving(true);try{const q=await request('/api/qc',{method:'POST',body:JSON.stringify({action:'start',laptopId:Number(String(laptop.id).replace('#','')),idempotencyKey:crypto.randomUUID()})});await load();await open(q)}catch(e){setError(e.message)}finally{setSaving(false)}};
 const complete=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setSaving(true);try{await request('/api/qc',{method:'POST',body:JSON.stringify({action:'complete',inspectionId:active.id,result:f.get('result'),mainboardStatus:f.get('mainboardStatus'),chargerStatus:f.get('chargerStatus'),cosmeticGrade:f.get('cosmeticGrade'),notes:f.get('notes'),items,idempotencyKey:crypto.randomUUID()})});setActive(null);await load()}catch(err){setError(err.message)}finally{setSaving(false)}};
 return <div className="qc-page"><header className="qc-header"><div><span>TECHNICAL GATE</span><h1>QC & Kiểm tra kỹ thuật</h1><p>Chỉ máy đạt toàn bộ tiêu chuẩn mới được mở khóa để bán.</p></div><div className="qc-score"><ClipboardCheck/><strong>{laptops.length}</strong><small>máy cần xử lý</small></div></header>{error&&<div className="error-message">{error}</div>}
 <section className="qc-grid"><div className="qc-panel"><div className="qc-panel-title"><h2>Hàng chờ QC</h2><span>{laptops.length} máy</span></div>{laptops.map(l=><article className="qc-machine" key={l.id}><div><small>#{String(l.id).replace('#','')} · {l.serial||'Chưa có serial'}</small><strong>{l.name}</strong><span>{l.location} · <b className={`qc-state ${l.status}`}>{l.status}</b></span></div>{l.status==='qc_in_progress'?<button onClick={()=>{const q=history.find(q=>String(q.laptop_id)===String(l.id).replace('#','')&&q.status==='IN_PROGRESS');if(q)open(q)}}>Tiếp tục</button>:<button disabled={saving} onClick={()=>start(l)}><Play size={15}/>Bắt đầu</button>}</article>)}{!laptops.length&&<div className="qc-empty">Không có máy chờ kiểm tra.</div>}</div>
 <div className="qc-panel"><div className="qc-panel-title"><h2>Lịch sử gần đây</h2><span>{history.length} phiên</span></div>{history.slice(0,20).map(q=><div className="qc-history-wrap" key={q.id}><button className="qc-history" onClick={()=>open(q)}><span className={`qc-result ${q.result||'IN_PROGRESS'}`}>{q.result==='PASS'?<ShieldCheck/>:q.result==='FAIL'?<ShieldX/>:<ClipboardCheck/>}</span><span><strong>{q.inspection_code}</strong><small>{q.laptops?.name}</small></span><b>{q.result||'Đang kiểm tra'}</b></button>{q.result==='FAIL'&&q.laptops?.status==='qc_failed'&&<button className="qc-repair-link" onClick={()=>router.push(`/repairs?laptopId=${q.laptop_id}&qcId=${q.id}`)}><Wrench size={14}/> Tạo phiếu sửa</button>}</div>)}</div></section>
 {active&&<div className="modal-backdrop active"><form className="qc-modal" onSubmit={complete}><header><div><small>{active.inspection_code}</small><h2>{active.laptops?.name}</h2><p>{active.laptops?.serial} · {active.started_by}</p></div><button type="button" onClick={()=>setActive(null)}><X/></button></header>{active.status==='IN_PROGRESS'?<><div className="qc-summary"><span><b>{counts.PASS||0}</b> đạt</span><span><b>{counts.FAIL||0}</b> lỗi</span><span><b>{counts.WARNING||0}</b> cảnh báo</span><span><b>{counts.NOT_TESTED||0}</b> chưa test</span></div><div className="qc-checklist">{items.map((item,i)=><div className={`qc-check ${item.result.toLowerCase()}`} key={item.checkKey}><strong>{item.label}</strong><select value={item.result} onChange={e=>setItems(items.map((x,n)=>n===i?{...x,result:e.target.value}:x))}>{RESULTS.map(r=><option value={r} key={r}>{LABEL[r]}</option>)}</select><input value={item.note} onChange={e=>setItems(items.map((x,n)=>n===i?{...x,note:e.target.value}:x))} placeholder="Ghi chú"/></div>)}</div><div className="qc-conclusion"><label>Kết quả<select name="result" defaultValue="PASS"><option>PASS</option><option>FAIL</option></select></label><label>Mainboard<select name="mainboardStatus" defaultValue="UNKNOWN"><option>ORIGINAL</option><option>OFFICIAL_REPLACED</option><option>REPAIRED</option><option>UNKNOWN</option></select></label><label>Sạc<select name="chargerStatus" defaultValue="UNKNOWN"><option>ORIGINAL</option><option>ORIGINAL_US</option><option>COMPATIBLE</option><option>MISSING</option><option>UNKNOWN</option></select></label><label>Ngoại hình<select name="cosmeticGrade"><option value="">—</option><option>A</option><option>B</option><option>C</option><option>D</option></select></label><label className="wide">Kết luận<textarea name="notes" rows="3"/></label></div><footer><span>PASS sẽ chuyển máy sang available.</span><button disabled={saving}>{saving?'Đang lưu…':'Hoàn tất QC'}</button></footer></>:<div className="qc-readonly"><span className={`qc-result ${active.result}`}>{active.result==='PASS'?<ShieldCheck/>:<ShieldX/>}</span><h3>Kết quả: {active.result}</h3><p>{active.overall_notes||'Không có ghi chú'}</p><div className="qc-checklist">{items.map(x=><div className={`qc-check ${x.result.toLowerCase()}`} key={x.checkKey}><strong>{x.label}</strong><b>{LABEL[x.result]}</b><span>{x.note}</span></div>)}</div></div>}</form></div>}</div>
}
