'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowRight, CirclePlus, PackageX, RefreshCw, Search, Truck, X } from 'lucide-react';
import { getAuthHeaders } from '@/lib/apiFetchers';
import ListPagination, { useListPagination } from '../ui/ListPagination';

const STATUS = { DRAFT:'Nháp', APPROVED:'Đã duyệt', READY_TO_SHIP:'Sẵn sàng gửi', SHIPPED:'Đã gửi', SUPPLIER_RECEIVED:'NCC đã nhận', WAITING_REFUND:'Chờ hoàn tiền', WAITING_REPLACEMENT:'Chờ đổi máy', PARTIALLY_RESOLVED:'Hoàn một phần', REFUNDED:'Đã hoàn tiền', REPLACED:'Đã đổi máy', REJECTED:'NCC từ chối', CLOSED:'Đã đóng', CANCELLED:'Đã hủy' };
const REASONS = { MAINBOARD_REPAIRED:'Mainboard đã sửa', WRONG_CONFIGURATION:'Sai cấu hình', HARDWARE_FAULT:'Lỗi phần cứng', SCREEN_FAULT:'Lỗi màn hình', GPU_FAULT:'Lỗi GPU', FUNCTIONAL_FAILURE:'Lỗi chức năng', PHYSICAL_DAMAGE:'Hư hỏng vật lý', MISSING_ACCESSORY:'Thiếu phụ kiện', SUPPLIER_AGREEMENT:'Thỏa thuận với NCC', OTHER:'Khác' };
const NEXT = { DRAFT:['APPROVED','CANCELLED'], APPROVED:['READY_TO_SHIP','CANCELLED'], READY_TO_SHIP:['SHIPPED','CANCELLED'], SHIPPED:['SUPPLIER_RECEIVED'], SUPPLIER_RECEIVED:['WAITING_REFUND','WAITING_REPLACEMENT','REJECTED'], REFUNDED:['CLOSED'], REPLACED:['CLOSED'], REJECTED:['CLOSED'] };
const money = value => new Intl.NumberFormat('vi-VN', { maximumFractionDigits: 2 }).format(Number(value || 0));
async function api(url, options={}) { const headers=await getAuthHeaders(); const response=await fetch(url,{...options,headers:{...headers,'Content-Type':'application/json'}}); const data=await response.json().catch(()=>({})); if(!response.ok) throw new Error(data.error||'Không thể xử lý yêu cầu'); return data; }

export default function SupplierReturns() {
  const [data,setData]=useState({returns:[],suppliers:[],eligible:[],replacementCandidates:[]}),[active,setActive]=useState(null),[detail,setDetail]=useState(null);
  const [cashAccounts,setCashAccounts]=useState([]);
  const [search,setSearch]=useState(''),[status,setStatus]=useState(''),[showCreate,setShowCreate]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{try{setData(await api('/api/supplier-returns'));setError('');}catch(e){setError(e.message);}},[]);
  useEffect(()=>{api('/api/supplier-returns').then(setData).catch(e=>setError(e.message));api('/api/cash-accounts?currency=CNY').then(setCashAccounts).catch(()=>setCashAccounts([]));},[]);
  const open=async row=>{try{setActive(row);setDetail(await api(`/api/supplier-returns?id=${row.id}`));}catch(e){setError(e.message);}};
  const mutate=async body=>{setSaving(true);try{await api('/api/supplier-returns',{method:'POST',body:JSON.stringify(body)});await load();if(active)setDetail(await api(`/api/supplier-returns?id=${active.id}`));return true;}catch(e){setError(e.message);return false;}finally{setSaving(false);}};
  const visible=useMemo(()=>data.returns.filter(row=>(!status||row.status===status)&&`${row.return_code} ${row.suppliers?.name} ${row.return_tracking_number}`.toLowerCase().includes(search.toLowerCase())),[data.returns,status,search]);
  const returnPages=useListPagination(visible,`${search}|${status}`);
  const create=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const laptop=data.eligible.find(x=>String(x.id)===f.get('laptopId'));if(!laptop)return;const ok=await mutate({action:'create',supplierId:laptop.supplier_id,reason:f.get('reason'),reasonNotes:f.get('reasonNotes'),notes:f.get('notes'),idempotencyKey:crypto.randomUUID(),items:[{laptopId:laptop.id,repairJobId:laptop.repair?.id||null,qcInspectionId:laptop.qc?.id||null,reason:f.get('reason'),conditionNotes:f.get('conditionNotes'),expectedRefundRmb:f.get('expectedRefundRmb'),agreedRefundRmb:''}]});if(ok)setShowCreate(false);};
  const transition=async target=>{const record=detail.record;let carrier=record.return_carrier,trackingNumber=record.return_tracking_number,resolutionType=record.resolution_type;if(target==='SHIPPED'){carrier=window.prompt('Đơn vị vận chuyển',carrier)||'';trackingNumber=window.prompt('Mã tracking',trackingNumber)||'';}if(target==='WAITING_REFUND')resolutionType=window.prompt('Loại xử lý: REFUND hoặc PARTIAL_REFUND','REFUND');if(target==='WAITING_REPLACEMENT')resolutionType='REPLACEMENT';await mutate({action:'transition',id:record.id,target,carrier,trackingNumber,resolutionType});};
  const refund=async e=>{e.preventDefault(); const formElement = e.currentTarget;const f=new FormData(formElement);if(await mutate({action:'refund',id:detail.record.id,amountRmb:f.get('amountRmb'),exchangeRate:f.get('exchangeRate'),method:f.get('method'),accountId:f.get('accountId'),reference:f.get('reference'),receivedAt:new Date().toISOString(),idempotencyKey:crypto.randomUUID()}))formElement.reset();};
  const linkReplacement=async(e,item)=>{e.preventDefault();const f=new FormData(e.currentTarget),candidate=data.replacementCandidates.find(x=>String(x.id)===f.get('replacementPurchaseItemId'));if(!candidate||!window.confirm(`Liên kết ${candidate.model}${candidate.serial?` · ${candidate.serial}`:''} làm máy thay thế? Máy vẫn phải đi qua Shipment, Receiving và QC.`))return;await mutate({action:'replacement',itemId:item.id,replacementPurchaseItemId:candidate.id,replacementLaptopId:candidate.laptop_id||null});};
  return <div className="supplier-return-page">
    <header className="supplier-return-hero"><div><span>SUPPLIER RECOVERY</span><h1>Trả hàng nhà cung cấp</h1><p>Theo dõi máy lỗi từ quyết định kỹ thuật đến vận chuyển, hoàn tiền hoặc đổi máy.</p></div><button onClick={()=>setShowCreate(true)}><CirclePlus size={18}/> Tạo phiếu trả</button></header>{error && <p role="alert" className="form-submit-error">{error}</p>}
    {error&&<div className="error-message">{error}<button onClick={()=>setError('')}>×</button></div>}
    <section className="supplier-return-metrics"><article><b>{data.returns.length}</b><span>Tổng phiếu</span></article><article><b>{data.returns.filter(x=>!['CLOSED','CANCELLED'].includes(x.status)).length}</b><span>Đang xử lý</span></article><article><b>¥{money(data.returns.flatMap(x=>x.supplier_return_items||[]).reduce((sum,x)=>sum+Number(x.agreed_refund_rmb??x.expected_refund_rmb??0),0))}</b><span>Giá trị dự kiến</span></article></section>
    <section className="supplier-return-toolbar"><label><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm mã phiếu, NCC, tracking"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tất cả trạng thái</option>{Object.entries(STATUS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><button onClick={load}><RefreshCw size={16}/> Làm mới</button></section>
    <section className="supplier-return-board">{returnPages.pageRows.map(row=><button className="supplier-return-card" key={row.id} onClick={()=>open(row)}><span className={`supplier-return-status ${row.status}`}>{STATUS[row.status]}</span><small>{row.return_code}</small><strong>{row.suppliers?.name}</strong><p>{REASONS[row.reason]} · {row.supplier_return_items?.length||0} máy</p><footer><span>{row.return_tracking_number||'Chưa có tracking'}</span><ArrowRight size={17}/></footer></button>)}{!visible.length&&<div className="repair-empty"><PackageX/><b>Chưa có phiếu phù hợp</b><span>Máy QC lỗi đủ nguồn gốc sẽ có thể tạo phiếu tại đây.</span></div>}</section>
    <ListPagination {...returnPages}/>
    {showCreate&&<div className="modal-backdrop active"><form className="supplier-return-modal create" onSubmit={create}><header><div><small>PHASE 5</small><h2>Tạo phiếu trả NCC</h2></div><button type="button" onClick={()=>setShowCreate(false)}><X/></button></header>{error && <p role="alert" className="form-submit-error">{error}</p>}<div className="supplier-return-form"><label className="wide">Laptop<select name="laptopId" required><option value="">Chọn máy QC lỗi</option>{data.eligible.map(x=><option key={x.id} value={x.id}>{x.name} · {x.serial||'chưa serial'} · {data.suppliers.find(s=>s.id===x.supplier_id)?.name}</option>)}</select></label><label>Lý do<select name="reason">{Object.entries(REASONS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Hoàn dự kiến (RMB)<input name="expectedRefundRmb" type="number" min="0" step="0.01"/></label><label className="wide">Tình trạng máy<textarea name="conditionNotes" required/></label><label className="wide">Chi tiết lý do<textarea name="reasonNotes"/></label><label className="wide">Ghi chú nội bộ<textarea name="notes"/></label></div><footer><button type="button" onClick={()=>setShowCreate(false)}>Đóng</button><button disabled={saving}>Tạo phiếu nháp</button></footer></form></div>}
    {detail&&<div className="modal-backdrop active"><div className="supplier-return-modal"><header><div><small>{detail.record.return_code} · {detail.record.suppliers?.code}</small><h2>{detail.record.suppliers?.name}</h2><p><b>{STATUS[detail.record.status]}</b> · {REASONS[detail.record.reason]}</p></div><button onClick={()=>{setDetail(null);setActive(null);}}><X/></button></header>{error && <p role="alert" className="form-submit-error">{error}</p>}
      <div className="supplier-return-timeline">{detail.events.map(event=><span key={event.id}><i/><b>{STATUS[event.event_type]||event.event_type}</b><small>{new Date(event.created_at).toLocaleString('vi-VN')} · {event.performed_by}</small></span>)}</div>
      <section className="supplier-return-detail"><div><h3>Máy trả & replacement</h3>{detail.items.map(item=><article className="supplier-return-item" key={item.id}><div><b>{item.laptops?.name}</b><small>{item.laptops?.serial} · {item.status}</small>{item.replacement_purchase_item&&<div className="replacement-summary"><b>Replacement: {item.replacement_purchase_item.model}</b><small>Serial: {item.replacement_purchase_item.serial||'chưa biết'}</small><small>Logistics: {item.replacement_shipment?.shipments?.status||'chưa vào shipment'}{item.replacement_shipment?.shipments?.tracking_number?` · ${item.replacement_shipment.shipments.tracking_number}`:''}</small><small>Receiving: {item.replacement_laptop_id?'đã tạo laptop':'chưa nhận'} · QC: {item.replacement_qc?.result||item.replacement_qc?.status||'chưa QC'}</small></div>}{detail.record.status==='WAITING_REPLACEMENT'&&!item.replacement_purchase_item_id&&<form className="replacement-link-form" onSubmit={e=>linkReplacement(e,item)}><select name="replacementPurchaseItemId" required><option value="">Chọn purchase item miễn phí cùng NCC</option>{data.replacementCandidates.filter(x=>x.supplier_id===detail.record.supplier_id).map(x=><option key={x.id} value={x.id}>{x.model} · {x.serial||'chưa serial'} · {x.shipment?.shipments?.status||'chưa shipment'}</option>)}</select><button disabled={saving}>Liên kết máy thay thế</button></form>}</div><strong>¥{money(item.agreed_refund_rmb??item.expected_refund_rmb)}</strong></article>)}</div><div><h3>Hoàn tiền</h3>{detail.refunds.map(row=><article key={row.id}><div><b>{row.refund_method}</b><small>{row.reference||'Không có tham chiếu'}</small></div><strong>¥{money(row.amount_rmb)}</strong></article>)}{['WAITING_REFUND','PARTIALLY_RESOLVED'].includes(detail.record.status)&&<form className="supplier-refund-form" onSubmit={refund}><input name="amountRmb" type="number" min="0.01" step="0.01" placeholder="Số RMB" required/><input name="exchangeRate" type="number" min="0.01" step="0.01" placeholder="Tỷ giá (tuỳ chọn)"/><select name="method"><option>WECHAT</option><option>ALIPAY</option><option>BANK_TRANSFER</option><option>OFFSET</option><option>OTHER</option></select><select name="accountId" required><option value="">Tài khoản nhận CNY</option>{cashAccounts.map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><input name="reference" placeholder="Tham chiếu"/><button disabled={saving}>Ghi nhận hoàn tiền</button></form>}</div></section>
      <footer className="supplier-return-actions">{(NEXT[detail.record.status]||[]).map(target=><button key={target} className={target==='CANCELLED'?'danger':''} disabled={saving} onClick={()=>transition(target)}>{target==='SHIPPED'&&<Truck size={16}/>} {STATUS[target]}</button>)}</footer>
    </div></div>}
  </div>;
}
