-- Phase 6 — server-derived landed cost, audited allocation and immutable sale snapshots.
BEGIN;

CREATE TABLE public.laptop_cost_components(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),laptop_id bigint NOT NULL REFERENCES laptops(id) ON DELETE RESTRICT,
 cost_type text NOT NULL CHECK(cost_type IN('PURCHASE','CN_SHIPPING','VN_SHIPPING','PAYMENT_FEE','REPAIR','RAM_UPGRADE','SSD_UPGRADE','ACCESSORY','CLEANING','OTHER','REFUND_CREDIT')),
 amount_vnd numeric(18,2) NOT NULL CHECK(amount_vnd>=0),amount_rmb numeric(14,2),exchange_rate numeric(14,4),
 source_type text NOT NULL CHECK(source_type IN('PURCHASE_ITEM','REPAIR_JOB','COST_ALLOCATION','MANUAL','SUPPLIER_REFUND')),
 source_id text,allocation_batch_id uuid,description text NOT NULL DEFAULT '',occurred_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
 created_by text NOT NULL,voided_at timestamptz,voided_by text,void_reason text,created_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
 CHECK((amount_rmb IS NULL AND exchange_rate IS NULL) OR (amount_rmb>=0 AND exchange_rate>0))
);
CREATE UNIQUE INDEX laptop_cost_components_source_unique ON laptop_cost_components(laptop_id,source_type,source_id,cost_type) WHERE source_id IS NOT NULL AND voided_at IS NULL;
CREATE INDEX laptop_cost_components_laptop_idx ON laptop_cost_components(laptop_id,occurred_at,id);

CREATE TABLE public.cost_allocations(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),shipment_id bigint NOT NULL REFERENCES shipments(id) ON DELETE RESTRICT,
 cost_type text NOT NULL CHECK(cost_type IN('CN_SHIPPING','VN_SHIPPING')),method text NOT NULL CHECK(method IN('EQUAL','MANUAL')),
 source_amount_vnd numeric(18,2) NOT NULL CHECK(source_amount_vnd>0),source_amount_rmb numeric(14,2),exchange_rate numeric(14,4),
 status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','FINALIZED','VOIDED')),idempotency_key text NOT NULL UNIQUE CHECK(length(btrim(idempotency_key)) BETWEEN 8 AND 100),
 created_by text NOT NULL,finalized_by text,finalized_at timestamptz,voided_by text,voided_at timestamptz,void_reason text,
 created_at timestamptz NOT NULL DEFAULT timezone('utc',now()),updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
 CHECK((source_amount_rmb IS NULL AND exchange_rate IS NULL) OR (source_amount_rmb>=0 AND exchange_rate>0))
);
CREATE UNIQUE INDEX cost_allocations_one_active_source ON cost_allocations(shipment_id,cost_type) WHERE status<>'VOIDED';
CREATE TABLE public.cost_allocation_items(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,cost_allocation_id uuid NOT NULL REFERENCES cost_allocations(id) ON DELETE RESTRICT,
 shipment_item_id bigint NOT NULL REFERENCES shipment_items(id) ON DELETE RESTRICT,laptop_id bigint NOT NULL REFERENCES laptops(id) ON DELETE RESTRICT,
 amount_vnd numeric(18,2) NOT NULL CHECK(amount_vnd>=0),created_at timestamptz NOT NULL DEFAULT timezone('utc',now()),UNIQUE(cost_allocation_id,shipment_item_id),UNIQUE(cost_allocation_id,laptop_id)
);

ALTER TABLE laptop_cost_components ADD CONSTRAINT laptop_cost_components_allocation_fk FOREIGN KEY(allocation_batch_id) REFERENCES cost_allocations(id) ON DELETE RESTRICT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cost_snapshot_vnd numeric(18,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS gross_profit_snapshot_vnd numeric(18,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS direct_cost_snapshot_vnd numeric(18,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS net_contribution_snapshot_vnd numeric(18,2);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cost_snapshot_status text CHECK(cost_snapshot_status IS NULL OR cost_snapshot_status IN('COMPLETE','INCOMPLETE','LEGACY'));
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cost_snapshot_reasons jsonb;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cost_snapshotted_at timestamptz;

CREATE OR REPLACE FUNCTION public.sync_laptop_cost_components(p_laptop_id bigint,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE l laptops%ROWTYPE;pi purchase_items%ROWTYPE;pb purchase_batches%ROWTYPE;r repair_jobs%ROWTYPE;purchase_amount numeric;repair_count integer:=0;
BEGIN
 SELECT * INTO l FROM laptops WHERE id=p_laptop_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy laptop';END IF;
 PERFORM set_config('app.cost_component_sync','on',true);
 IF l.purchase_item_id IS NOT NULL THEN
  SELECT * INTO pi FROM purchase_items WHERE id=l.purchase_item_id;SELECT * INTO pb FROM purchase_batches WHERE id=pi.purchase_batch_id;
  IF pb.exchange_rate IS NOT NULL AND pb.exchange_rate>0 THEN
   purchase_amount:=round(pi.purchase_price_rmb*pb.exchange_rate,2);
   INSERT INTO laptop_cost_components(laptop_id,cost_type,amount_vnd,amount_rmb,exchange_rate,source_type,source_id,description,occurred_at,created_by)
   VALUES(l.id,'PURCHASE',purchase_amount,pi.purchase_price_rmb,pb.exchange_rate,'PURCHASE_ITEM',pi.id::text,'Giá mua từ '||pb.batch_code,pb.purchase_date::timestamptz,p_actor)
   ON CONFLICT(laptop_id,source_type,source_id,cost_type) WHERE source_id IS NOT NULL AND voided_at IS NULL DO UPDATE SET amount_vnd=excluded.amount_vnd,amount_rmb=excluded.amount_rmb,exchange_rate=excluded.exchange_rate,description=excluded.description;
  END IF;
 END IF;
 FOR r IN SELECT * FROM repair_jobs WHERE laptop_id=l.id AND status='COMPLETED' LOOP
  INSERT INTO laptop_cost_components(laptop_id,cost_type,amount_vnd,source_type,source_id,description,occurred_at,created_by)
  VALUES(l.id,'REPAIR',r.total_cost_vnd,'REPAIR_JOB',r.id::text,'Chi phí '||r.repair_code,coalesce(r.completed_at,r.updated_at),p_actor)
  ON CONFLICT(laptop_id,source_type,source_id,cost_type) WHERE source_id IS NOT NULL AND voided_at IS NULL DO UPDATE SET amount_vnd=excluded.amount_vnd,description=excluded.description;
  repair_count:=repair_count+1;
 END LOOP;
 RETURN jsonb_build_object('laptop_id',l.id,'purchase_cost_vnd',purchase_amount,'repair_jobs_synced',repair_count);
END $$;

CREATE OR REPLACE FUNCTION public.add_manual_laptop_cost(p_laptop_id bigint,p_cost_type text,p_amount_vnd numeric,p_description text,p_occurred_at timestamptz,p_actor text,p_idempotency_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE c laptop_cost_components%ROWTYPE;
BEGIN
 IF p_cost_type NOT IN('RAM_UPGRADE','SSD_UPGRADE','ACCESSORY','CLEANING','OTHER') OR p_amount_vnd<0 OR btrim(coalesce(p_description,''))='' THEN RAISE EXCEPTION 'Chi phí thủ công không hợp lệ';END IF;
 SELECT * INTO c FROM laptop_cost_components WHERE laptop_id=p_laptop_id AND source_type='MANUAL' AND source_id=p_idempotency_key AND cost_type=p_cost_type AND voided_at IS NULL;IF FOUND THEN RETURN to_jsonb(c);END IF;
 INSERT INTO laptop_cost_components(laptop_id,cost_type,amount_vnd,source_type,source_id,description,occurred_at,created_by) VALUES(p_laptop_id,p_cost_type,p_amount_vnd,'MANUAL',p_idempotency_key,left(p_description,1000),coalesce(p_occurred_at,timezone('utc',now())),p_actor) RETURNING * INTO c;
 INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('LAPTOP_COST',c.id::text,'CREATE',jsonb_build_object('event','COST_COMPONENT_ADDED','laptop_id',p_laptop_id,'cost_type',p_cost_type,'amount_vnd',p_amount_vnd),p_actor);RETURN to_jsonb(c);
END $$;

CREATE OR REPLACE FUNCTION public.void_manual_laptop_cost(p_id uuid,p_reason text,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE c laptop_cost_components%ROWTYPE;
BEGIN IF btrim(coalesce(p_reason,''))='' THEN RAISE EXCEPTION 'Cần nhập lý do void chi phí';END IF;PERFORM set_config('app.cost_component_void','on',true);UPDATE laptop_cost_components SET voided_at=timezone('utc',now()),voided_by=p_actor,void_reason=left(btrim(p_reason),1000) WHERE id=p_id AND source_type='MANUAL' AND voided_at IS NULL RETURNING * INTO c;IF NOT FOUND THEN RAISE EXCEPTION 'Chỉ có thể void chi phí thủ công đang hoạt động';END IF;INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('LAPTOP_COST',c.id::text,'UPDATE',jsonb_build_object('event','COST_COMPONENT_VOIDED','reason',p_reason),p_actor);RETURN to_jsonb(c);END $$;

CREATE OR REPLACE FUNCTION public.create_cost_allocation(p_shipment_id bigint,p_cost_type text,p_method text,p_exchange_rate numeric,p_items jsonb,p_actor text,p_idempotency_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE s shipments%ROWTYPE;a cost_allocations%ROWTYPE;row_data record;entry jsonb;source_vnd numeric;allocated numeric:=0;eligible_count integer;base numeric;remainder integer;i integer:=0;amount numeric;
BEGIN
 SELECT * INTO a FROM cost_allocations WHERE idempotency_key=p_idempotency_key;IF FOUND THEN RETURN to_jsonb(a);END IF;
 IF p_cost_type NOT IN('CN_SHIPPING','VN_SHIPPING') OR p_method NOT IN('EQUAL','MANUAL') OR length(btrim(coalesce(p_idempotency_key,''))) NOT BETWEEN 8 AND 100 THEN RAISE EXCEPTION 'Yêu cầu phân bổ không hợp lệ';END IF;
 SELECT * INTO s FROM shipments WHERE id=p_shipment_id FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy shipment';END IF;
 source_vnd:=CASE WHEN s.shipping_cost_vnd>0 THEN round(s.shipping_cost_vnd,0) WHEN s.shipping_cost_rmb>0 AND p_exchange_rate>0 THEN round(s.shipping_cost_rmb*p_exchange_rate,0) ELSE 0 END;
 IF source_vnd<=0 THEN RAISE EXCEPTION 'Shipment chưa có chi phí VND hoặc tỷ giá RMB hợp lệ';END IF;
 SELECT count(*) INTO eligible_count FROM shipment_items WHERE shipment_id=s.id AND status='RECEIVED' AND laptop_id IS NOT NULL;
 IF eligible_count=0 THEN RAISE EXCEPTION 'Shipment chưa có laptop đã nhận để phân bổ';END IF;
 IF p_method='MANUAL' AND (jsonb_typeof(p_items)<>'array' OR jsonb_array_length(p_items)<>eligible_count) THEN RAISE EXCEPTION 'Manual allocation phải bao gồm toàn bộ laptop đã nhận';END IF;
 INSERT INTO cost_allocations(shipment_id,cost_type,method,source_amount_vnd,source_amount_rmb,exchange_rate,idempotency_key,created_by)
 VALUES(s.id,p_cost_type,p_method,source_vnd,CASE WHEN s.shipping_cost_vnd=0 THEN s.shipping_cost_rmb ELSE NULL END,CASE WHEN s.shipping_cost_vnd=0 THEN p_exchange_rate ELSE NULL END,p_idempotency_key,p_actor) RETURNING * INTO a;
 IF p_method='EQUAL' THEN
  base:=floor(source_vnd/eligible_count);remainder:=(source_vnd-base*eligible_count)::integer;
  FOR row_data IN SELECT id,laptop_id FROM shipment_items WHERE shipment_id=s.id AND status='RECEIVED' AND laptop_id IS NOT NULL ORDER BY id LOOP i:=i+1;amount:=base+CASE WHEN i<=remainder THEN 1 ELSE 0 END;INSERT INTO cost_allocation_items(cost_allocation_id,shipment_item_id,laptop_id,amount_vnd) VALUES(a.id,row_data.id,row_data.laptop_id,amount);allocated:=allocated+amount;END LOOP;
 ELSE
  FOR entry IN SELECT value FROM jsonb_array_elements(p_items) LOOP
   SELECT id,laptop_id INTO row_data FROM shipment_items WHERE id=(entry->>'shipment_item_id')::bigint AND shipment_id=s.id AND status='RECEIVED' AND laptop_id=(entry->>'laptop_id')::bigint;
   IF NOT FOUND OR coalesce((entry->>'amount_vnd')::numeric,-1)<0 THEN RAISE EXCEPTION 'Allocation item không hợp lệ';END IF;
   amount:=(entry->>'amount_vnd')::numeric;INSERT INTO cost_allocation_items(cost_allocation_id,shipment_item_id,laptop_id,amount_vnd) VALUES(a.id,row_data.id,row_data.laptop_id,amount);allocated:=allocated+amount;
  END LOOP;
 END IF;
 IF allocated<>source_vnd THEN RAISE EXCEPTION 'Tổng phân bổ (%) phải bằng source cost (%)',allocated,source_vnd;END IF;
 UPDATE cost_allocations SET status='FINALIZED',finalized_by=p_actor,finalized_at=timezone('utc',now()) WHERE id=a.id RETURNING * INTO a;
 INSERT INTO laptop_cost_components(laptop_id,cost_type,amount_vnd,source_type,source_id,allocation_batch_id,description,occurred_at,created_by) SELECT laptop_id,a.cost_type,amount_vnd,'COST_ALLOCATION',a.id::text,a.id,'Phân bổ shipment '||s.shipment_code,coalesce(s.received_at,timezone('utc',now())),p_actor FROM cost_allocation_items WHERE cost_allocation_id=a.id;
 INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('COST_ALLOCATION',a.id::text,'CREATE',jsonb_build_object('event','COST_ALLOCATION_FINALIZED','shipment_id',s.id,'method',a.method,'amount_vnd',source_vnd),p_actor);RETURN to_jsonb(a);
EXCEPTION WHEN unique_violation THEN SELECT * INTO a FROM cost_allocations WHERE idempotency_key=p_idempotency_key;IF FOUND THEN RETURN to_jsonb(a);END IF;RAISE;
END $$;

CREATE VIEW public.laptop_landed_costs AS
WITH sums AS(SELECT laptop_id,
 sum(amount_vnd) FILTER(WHERE cost_type='PURCHASE') purchase_cost_vnd,sum(amount_vnd) FILTER(WHERE cost_type='CN_SHIPPING') cn_shipping_vnd,
 sum(amount_vnd) FILTER(WHERE cost_type='VN_SHIPPING') vn_shipping_vnd,sum(amount_vnd) FILTER(WHERE cost_type='REPAIR') repair_cost_vnd,
 sum(amount_vnd) FILTER(WHERE cost_type IN('RAM_UPGRADE','SSD_UPGRADE')) upgrade_cost_vnd,sum(amount_vnd) FILTER(WHERE cost_type='ACCESSORY') accessory_cost_vnd,
 sum(amount_vnd) FILTER(WHERE cost_type IN('CLEANING','OTHER','PAYMENT_FEE')) other_cost_vnd,sum(amount_vnd) FILTER(WHERE cost_type='REFUND_CREDIT') refund_credit_vnd
 FROM laptop_cost_components WHERE voided_at IS NULL GROUP BY laptop_id), completeness AS(
 SELECT l.id,
 CASE WHEN l.purchase_item_id IS NULL THEN 'LEGACY' WHEN pb.exchange_rate IS NULL OR pb.exchange_rate<=0 THEN 'INCOMPLETE' WHEN EXISTS(SELECT 1 FROM shipment_items si JOIN shipments sh ON sh.id=si.shipment_id WHERE si.purchase_item_id=l.purchase_item_id AND si.status='RECEIVED' AND (sh.shipping_cost_vnd>0 OR sh.shipping_cost_rmb>0) AND NOT EXISTS(SELECT 1 FROM cost_allocations ca WHERE ca.shipment_id=sh.id AND ca.status='FINALIZED')) OR EXISTS(SELECT 1 FROM repair_jobs r WHERE r.laptop_id=l.id AND r.status NOT IN('COMPLETED','CANCELLED')) THEN 'INCOMPLETE' ELSE 'COMPLETE' END cost_status,
 array_remove(ARRAY[CASE WHEN l.purchase_item_id IS NULL THEN 'LEGACY_NO_PURCHASE_LINEAGE' END,CASE WHEN l.purchase_item_id IS NOT NULL AND (pb.exchange_rate IS NULL OR pb.exchange_rate<=0) THEN 'MISSING_EXCHANGE_RATE' END,CASE WHEN EXISTS(SELECT 1 FROM shipment_items si JOIN shipments sh ON sh.id=si.shipment_id WHERE si.purchase_item_id=l.purchase_item_id AND si.status='RECEIVED' AND (sh.shipping_cost_vnd>0 OR sh.shipping_cost_rmb>0) AND NOT EXISTS(SELECT 1 FROM cost_allocations ca WHERE ca.shipment_id=sh.id AND ca.status='FINALIZED')) THEN 'UNALLOCATED_SHIPPING' END,CASE WHEN EXISTS(SELECT 1 FROM repair_jobs r WHERE r.laptop_id=l.id AND r.status NOT IN('COMPLETED','CANCELLED')) THEN 'ACTIVE_REPAIR_COST_PENDING' END],NULL) reasons
 FROM laptops l LEFT JOIN purchase_items pi ON pi.id=l.purchase_item_id LEFT JOIN purchase_batches pb ON pb.id=pi.purchase_batch_id)
SELECT l.id laptop_id,coalesce(s.purchase_cost_vnd,0)::numeric(18,2) purchase_cost_vnd,coalesce(s.cn_shipping_vnd,0)::numeric(18,2) cn_shipping_vnd,coalesce(s.vn_shipping_vnd,0)::numeric(18,2) vn_shipping_vnd,coalesce(s.repair_cost_vnd,0)::numeric(18,2) repair_cost_vnd,coalesce(s.upgrade_cost_vnd,0)::numeric(18,2) upgrade_cost_vnd,coalesce(s.accessory_cost_vnd,0)::numeric(18,2) accessory_cost_vnd,coalesce(s.other_cost_vnd,0)::numeric(18,2) other_cost_vnd,coalesce(s.refund_credit_vnd,0)::numeric(18,2) refund_credit_vnd,greatest(coalesce(s.purchase_cost_vnd,0)+coalesce(s.cn_shipping_vnd,0)+coalesce(s.vn_shipping_vnd,0)+coalesce(s.repair_cost_vnd,0)+coalesce(s.upgrade_cost_vnd,0)+coalesce(s.accessory_cost_vnd,0)+coalesce(s.other_cost_vnd,0)-coalesce(s.refund_credit_vnd,0),0)::numeric(18,2) landed_cost_vnd,c.cost_status,c.reasons
FROM laptops l LEFT JOIN sums s ON s.laptop_id=l.id JOIN completeness c ON c.id=l.id;

CREATE OR REPLACE FUNCTION public.snapshot_order_cost()
RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$ DECLARE cost laptop_landed_costs%ROWTYPE;direct_cost numeric;sale_vnd numeric;
BEGIN
 IF NEW.order_status IN('prepared','shipping','done') AND NEW.cost_snapshotted_at IS NULL AND NEW.laptop_id IS NOT NULL THEN
  PERFORM sync_laptop_cost_components(NEW.laptop_id,'SYSTEM');SELECT * INTO cost FROM laptop_landed_costs WHERE laptop_id=NEW.laptop_id;
  sale_vnd:=coalesce(NEW.sale_price,0)*1000000;direct_cost:=coalesce(NEW.credit_card_fee,0)*1000000;
  NEW.cost_snapshot_vnd:=cost.landed_cost_vnd;NEW.gross_profit_snapshot_vnd:=sale_vnd-cost.landed_cost_vnd;NEW.direct_cost_snapshot_vnd:=direct_cost;NEW.net_contribution_snapshot_vnd:=sale_vnd-cost.landed_cost_vnd-direct_cost;NEW.cost_snapshot_status:=cost.cost_status;NEW.cost_snapshot_reasons:=to_jsonb(cost.reasons);NEW.cost_snapshotted_at:=timezone('utc',now());NEW.profit_vnd:=round((sale_vnd-cost.landed_cost_vnd)/1000000,4);
  INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('ORDER',coalesce(NEW.id::text,'pending'),'UPDATE',jsonb_build_object('event','COST_SNAPSHOT_CREATED','laptop_id',NEW.laptop_id,'cost_snapshot_vnd',NEW.cost_snapshot_vnd,'cost_status',NEW.cost_snapshot_status),'SYSTEM');
 END IF;RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS orders_snapshot_landed_cost ON orders;CREATE TRIGGER orders_snapshot_landed_cost BEFORE INSERT OR UPDATE OF order_status,laptop_id,sale_price,credit_card_fee ON orders FOR EACH ROW EXECUTE FUNCTION public.snapshot_order_cost();

CREATE OR REPLACE FUNCTION public.guard_order_cost_snapshot() RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
BEGIN RAISE EXCEPTION 'Snapshot giá vốn của đơn hàng chỉ được tạo tự động khi chốt bán';END $$;
DROP TRIGGER IF EXISTS orders_cost_snapshot_immutable ON orders;CREATE TRIGGER orders_cost_snapshot_immutable BEFORE UPDATE OF cost_snapshot_vnd,gross_profit_snapshot_vnd,direct_cost_snapshot_vnd,net_contribution_snapshot_vnd,cost_snapshot_status,cost_snapshot_reasons,cost_snapshotted_at ON orders FOR EACH ROW EXECUTE FUNCTION public.guard_order_cost_snapshot();

CREATE OR REPLACE FUNCTION public.sync_repair_cost_trigger() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ BEGIN IF NEW.status='COMPLETED' AND OLD.status IS DISTINCT FROM NEW.status THEN PERFORM sync_laptop_cost_components(NEW.laptop_id,coalesce(NEW.completed_by,NEW.created_by));END IF;RETURN NEW;END $$;
DROP TRIGGER IF EXISTS repair_sync_landed_cost ON repair_jobs;CREATE TRIGGER repair_sync_landed_cost AFTER UPDATE OF status ON repair_jobs FOR EACH ROW EXECUTE FUNCTION public.sync_repair_cost_trigger();

CREATE OR REPLACE FUNCTION public.guard_finalized_cost_history() RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$ DECLARE s text;BEGIN IF TG_TABLE_NAME='cost_allocations' THEN IF TG_OP='DELETE' OR OLD.status IN('FINALIZED','VOIDED') THEN RAISE EXCEPTION 'Allocation đã finalized là bất biến';END IF;ELSE SELECT status INTO s FROM cost_allocations WHERE id=coalesce(NEW.cost_allocation_id,OLD.cost_allocation_id);IF TG_OP='DELETE' OR s IN('FINALIZED','VOIDED') THEN RAISE EXCEPTION 'Allocation item đã finalized là bất biến';END IF;END IF;RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;END $$;
CREATE TRIGGER cost_allocations_immutable BEFORE UPDATE OR DELETE ON cost_allocations FOR EACH ROW EXECUTE FUNCTION guard_finalized_cost_history();CREATE TRIGGER cost_allocation_items_immutable BEFORE UPDATE OR DELETE ON cost_allocation_items FOR EACH ROW EXECUTE FUNCTION guard_finalized_cost_history();CREATE TRIGGER cost_allocations_updated BEFORE UPDATE ON cost_allocations FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE OR REPLACE FUNCTION public.guard_laptop_cost_component_history() RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Lịch sử cấu phần giá vốn là bất biến';END IF;
 IF OLD.source_type<>'MANUAL' AND current_setting('app.cost_component_sync',true) IS DISTINCT FROM 'on' THEN RAISE EXCEPTION 'Cấu phần giá vốn hệ thống là bất biến';END IF;
 IF OLD.source_type<>'MANUAL' THEN RETURN NEW;END IF;
 IF current_setting('app.cost_component_void',true) IS DISTINCT FROM 'on' OR NEW.laptop_id IS DISTINCT FROM OLD.laptop_id OR NEW.cost_type IS DISTINCT FROM OLD.cost_type OR NEW.amount_vnd IS DISTINCT FROM OLD.amount_vnd OR NEW.source_type IS DISTINCT FROM OLD.source_type OR NEW.source_id IS DISTINCT FROM OLD.source_id OR NEW.description IS DISTINCT FROM OLD.description OR NEW.occurred_at IS DISTINCT FROM OLD.occurred_at OR NEW.created_by IS DISTINCT FROM OLD.created_by THEN RAISE EXCEPTION 'Chi phí thủ công chỉ được void qua workflow giá vốn';END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS laptop_cost_components_immutable ON laptop_cost_components;CREATE TRIGGER laptop_cost_components_immutable BEFORE UPDATE OR DELETE ON laptop_cost_components FOR EACH ROW EXECUTE FUNCTION public.guard_laptop_cost_component_history();

ALTER TABLE laptop_cost_components ENABLE ROW LEVEL SECURITY;ALTER TABLE cost_allocations ENABLE ROW LEVEL SECURITY;ALTER TABLE cost_allocation_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON laptop_cost_components,cost_allocations,cost_allocation_items,laptop_landed_costs FROM PUBLIC,anon,authenticated;GRANT ALL ON laptop_cost_components,cost_allocations,cost_allocation_items TO service_role;GRANT SELECT ON laptop_landed_costs TO service_role;GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
REVOKE ALL ON FUNCTION sync_laptop_cost_components(bigint,text),add_manual_laptop_cost(bigint,text,numeric,text,timestamptz,text,text),void_manual_laptop_cost(uuid,text,text),create_cost_allocation(bigint,text,text,numeric,jsonb,text,text),snapshot_order_cost(),guard_order_cost_snapshot(),sync_repair_cost_trigger(),guard_finalized_cost_history(),guard_laptop_cost_component_history() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION sync_laptop_cost_components(bigint,text),add_manual_laptop_cost(bigint,text,numeric,text,timestamptz,text,text),void_manual_laptop_cost(uuid,text,text),create_cost_allocation(bigint,text,text,numeric,jsonb,text,text) TO service_role;
COMMIT;
