-- Run after the existing migrations. Money retains the app's million-VND unit.
BEGIN;
CREATE SEQUENCE IF NOT EXISTS public.laptop_sku_seq;
ALTER TABLE public.laptops ADD COLUMN IF NOT EXISTS sku text;
ALTER TABLE public.laptops ALTER COLUMN sku SET DEFAULT ('LT-' || lpad(nextval('public.laptop_sku_seq')::text, 7, '0'));
UPDATE public.laptops SET sku = 'LT-' || lpad(nextval('public.laptop_sku_seq')::text, 7, '0') WHERE sku IS NULL;
ALTER TABLE public.laptops ALTER COLUMN sku SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS laptops_sku_unique ON public.laptops(sku);

CREATE TABLE IF NOT EXISTS public.branches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 160),
  address text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true
);
CREATE TABLE IF NOT EXISTS public.accessories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku text NOT NULL UNIQUE CHECK (length(btrim(sku)) BETWEEN 1 AND 80),
  name text NOT NULL CHECK (length(btrim(name)) BETWEEN 1 AND 240),
  kind text NOT NULL DEFAULT 'other' CHECK (kind IN ('mouse','backpack','mousepad','sleeve','other')),
  price numeric NOT NULL DEFAULT 0 CHECK (price >= 0),
  note text NOT NULL DEFAULT '',
  active boolean NOT NULL DEFAULT true
);
INSERT INTO public.accessories(sku,name,kind) VALUES
 ('PK-MOUSE','Chuột không dây','mouse'), ('PK-BAG','Balo laptop','backpack'),
 ('PK-PAD','Lót chuột','mousepad'), ('PK-SLEEVE','Túi chống sốc','sleeve')
ON CONFLICT(sku) DO NOTHING;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES public.branches(id);
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS gift_accessory_ids jsonb NOT NULL DEFAULT '[]';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS gift_preset text NOT NULL DEFAULT '';

-- COD is the amount assigned for collection, not an amount already paid.
-- It may therefore equal the full sale price even when legacy deposit fields
-- still contain a value. Keep it bounded by the sale price only.
ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_cod_amount_lte_debt_amount_chk,
  DROP CONSTRAINT IF EXISTS orders_cod_amount_lte_sale_price_chk;
ALTER TABLE public.orders
  ADD CONSTRAINT orders_cod_amount_lte_sale_price_chk
  CHECK (COALESCE(cod_amount, 0) >= 0 AND COALESCE(cod_amount, 0) <= COALESCE(sale_price, 0));

CREATE OR REPLACE FUNCTION public.normalize_order_financials(p_order orders)
RETURNS orders LANGUAGE plpgsql STABLE SET search_path = public, pg_temp AS $$
DECLARE v_order orders := p_order;
BEGIN
  v_order.is_active := COALESCE(v_order.is_active, true);
  v_order.sale_price := GREATEST(COALESCE(v_order.sale_price, 0), 0);
  v_order.deposit_amount := LEAST(v_order.sale_price, GREATEST(COALESCE(v_order.deposit_amount, 0), 0));
  v_order.amount_paid := LEAST(v_order.sale_price, GREATEST(COALESCE(v_order.amount_paid, 0), v_order.deposit_amount));
  v_order.debt_amount := GREATEST(v_order.sale_price - v_order.amount_paid, 0);
  v_order.cod_amount := LEAST(v_order.sale_price, GREATEST(COALESCE(v_order.cod_amount, 0), 0));
  v_order.credit_card_fee := GREATEST(COALESCE(v_order.credit_card_fee, 0), 0);
  v_order.profit_vnd := COALESCE(v_order.profit_vnd, 0);
  v_order.payment_status := lower(btrim(COALESCE(v_order.payment_status, '')));
  IF v_order.payment_status NOT IN ('unpaid','deposited','cod','paid','refunded') THEN v_order.payment_status := 'unpaid'; END IF;
  IF v_order.laptop_id IS NOT NULL AND v_order.is_active IS TRUE
     AND v_order.reservation_expires_at IS NULL
     AND (v_order.order_status='deposited' OR v_order.payment_status='deposited') THEN
    v_order.reservation_expires_at := timezone('utc'::text,now()) + interval '48 hours';
  END IF;
  v_order.laptop_locked := public.order_uses_laptop(v_order.laptop_id,v_order.is_active,v_order.order_status,v_order.payment_status,v_order.reservation_expires_at);
  RETURN v_order;
END $$;

CREATE TABLE IF NOT EXISTS public.invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL UNIQUE REFERENCES public.orders(id) ON DELETE RESTRICT,
  laptop_id bigint REFERENCES public.laptops(id) ON DELETE RESTRICT,
  customer_id bigint REFERENCES public.customers(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL,
  snapshot jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS invoices_customer_idx ON public.invoices(customer_id);
CREATE INDEX IF NOT EXISTS invoices_laptop_idx ON public.invoices(laptop_id);
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.accessories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.invoices, public.accessories, public.branches FROM anon, authenticated;
GRANT ALL ON public.invoices, public.accessories, public.branches TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- Wrap existing business RPCs so order metadata saves in the same transaction.
DO $$ BEGIN
 IF to_regprocedure('public.create_order_before_invoice(jsonb,text)') IS NULL THEN
   ALTER FUNCTION public.create_order_with_inventory(jsonb,text) RENAME TO create_order_before_invoice;
 END IF;
 IF to_regprocedure('public.update_order_before_invoice(jsonb,text)') IS NULL THEN
   ALTER FUNCTION public.update_order_with_inventory(jsonb,text) RENAME TO update_order_before_invoice;
 END IF;
END $$;
CREATE OR REPLACE FUNCTION public.save_order_invoice_fields(p_order jsonb, p_result jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE v_id bigint := (p_result->'order'->>'id')::bigint; v_row orders%ROWTYPE;
BEGIN
 IF p_order ? 'gift_accessory_ids' AND (jsonb_typeof(p_order->'gift_accessory_ids') <> 'array' OR jsonb_array_length(p_order->'gift_accessory_ids') > 30) THEN
   RAISE EXCEPTION 'Danh sách quà tặng không hợp lệ';
 END IF;
 IF p_order ? 'gift_accessory_ids' AND EXISTS (
   SELECT 1 FROM jsonb_array_elements_text(p_order->'gift_accessory_ids') x(id)
   WHERE NOT EXISTS (SELECT 1 FROM accessories a WHERE a.id::text = x.id AND a.active)
 ) THEN RAISE EXCEPTION 'Phụ kiện không tồn tại hoặc đã ngừng sử dụng'; END IF;
 UPDATE orders SET
   branch_id = CASE WHEN p_order ? 'branch_id' THEN (p_order->>'branch_id')::bigint ELSE branch_id END,
   gift_accessory_ids = CASE WHEN p_order ? 'gift_accessory_ids' THEN p_order->'gift_accessory_ids' ELSE gift_accessory_ids END,
   gift_preset = CASE WHEN p_order ? 'gift_preset' THEN coalesce(p_order->>'gift_preset','') ELSE gift_preset END
 WHERE id = v_id RETURNING * INTO v_row;
 RETURN jsonb_set(p_result,'{order}',to_jsonb(v_row));
END $$;
CREATE OR REPLACE FUNCTION public.create_order_with_inventory(p_order jsonb,p_recorded_by text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN RETURN save_order_invoice_fields(p_order,create_order_before_invoice(p_order,p_recorded_by)); END $$;
CREATE OR REPLACE FUNCTION public.update_order_with_inventory(p_order jsonb,p_recorded_by text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN RETURN save_order_invoice_fields(p_order,update_order_before_invoice(p_order,p_recorded_by)); END $$;

CREATE OR REPLACE FUNCTION public.issue_invoice(p_order_id bigint,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE o orders%ROWTYPE; l laptops%ROWTYPE; c customers%ROWTYPE; b branches%ROWTYPE;
 i invoices%ROWTYPE; items jsonb; receipts jsonb; finance jsonb; ledger_total numeric; effective_paid numeric; deposit_total numeric; a accessories%ROWTYPE;
BEGIN
 SELECT * INTO o FROM orders WHERE id=p_order_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy đơn hàng'; END IF;
 SELECT * INTO i FROM invoices WHERE order_id=p_order_id;
 IF FOUND THEN RETURN to_jsonb(i); END IF;
 IF o.is_active IS NOT TRUE OR o.order_status NOT IN ('shipping','done') THEN
   RAISE EXCEPTION 'Chỉ xuất hóa đơn khi đơn đang giao hàng hoặc đã hoàn thành';
 END IF;
 IF coalesce(o.sale_price,0) <= 0 THEN
   RAISE EXCEPTION 'Đơn hàng chưa có giá bán hợp lệ';
 END IF;
 SELECT * INTO b FROM branches WHERE id=o.branch_id;
 IF NOT FOUND THEN RAISE EXCEPTION 'Vui lòng chọn chi nhánh bán hàng trong đơn'; END IF;
 SELECT * INTO l FROM laptops WHERE id=o.laptop_id FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Đơn chưa có laptop'; END IF;
 SELECT * INTO c FROM customers WHERE id=o.customer_id;
 IF NOT FOUND THEN RAISE EXCEPTION 'Vui lòng chọn khách hàng có tên, SĐT và địa chỉ'; END IF;
 IF coalesce(btrim(c.name),'')='' OR coalesce(btrim(c.phone),'')='' THEN RAISE EXCEPTION 'Khách hàng thiếu tên hoặc số điện thoại'; END IF;
 SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.payment_date,p.id),'[]'),
 coalesce(sum(CASE WHEN p.payment_type='refund' THEN -p.amount ELSE p.amount END),0),
 coalesce(sum(CASE WHEN p.payment_type='deposit' THEN p.amount ELSE 0 END),0)
 INTO receipts,ledger_total,deposit_total FROM payments p WHERE p.order_id=o.id;
 effective_paid := greatest(ledger_total,coalesce(o.amount_paid,0));
 IF (deposit_total <= 0 AND coalesce(o.deposit_amount,0) <= 0
     AND NOT (o.payment_status='paid' AND coalesce(o.amount_paid,0) > 0))
    OR effective_paid <= 0 THEN
   RAISE EXCEPTION 'Cần ghi nhận ít nhất một khoản đặt cọc trước khi xuất hóa đơn';
 END IF;
 SELECT coalesce(jsonb_agg(to_jsonb(f) ORDER BY f.occurred_on,f.id),'[]') INTO finance FROM financial_records f WHERE f.order_id=o.id;
 items := jsonb_build_array(jsonb_build_object('kind','laptop','id',l.id,'sku',l.sku,'name',l.name,'quantity',1,'price',o.sale_price,'total',o.sale_price,'serial',l.serial,'note',concat_ws(' · ',l.condition_note,o.warranty,o.setup_note)));
 FOR a IN SELECT * FROM accessories WHERE id IN (SELECT value::bigint FROM jsonb_array_elements_text(o.gift_accessory_ids)) ORDER BY id LOOP
   items := items || jsonb_build_array(jsonb_build_object('kind','gift','id',a.id,'sku',a.sku,'name',a.name,'quantity',1,'price',0,'total',0,'serial','','note',a.note));
 END LOOP;
 INSERT INTO invoices(order_id,laptop_id,customer_id,created_by,snapshot) VALUES
 (o.id,l.id,c.id,p_actor,jsonb_build_object('order',to_jsonb(o),'customer',to_jsonb(c),'branch',to_jsonb(b),'items',items,'payments',receipts,'financial_records',finance,'total',o.sale_price,'paid',effective_paid,'currency','VND','unit_multiplier',1000000)) RETURNING * INTO i;
 RETURN to_jsonb(i);
END $$;

-- Chỉ khối thanh toán được đồng bộ sau khi phát hành. Thông tin khách hàng,
-- sản phẩm, giá bán và quà tặng vẫn là snapshot bất biến.
CREATE OR REPLACE FUNCTION public.sync_invoice_payment_snapshot(p_order_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
DECLARE receipts jsonb; finance jsonb; ledger_total numeric; effective_paid numeric; payment_count bigint; current_order orders%ROWTYPE;
BEGIN
 SELECT * INTO current_order FROM orders WHERE id=p_order_id;
 IF NOT FOUND OR NOT EXISTS (SELECT 1 FROM invoices WHERE order_id=p_order_id) THEN RETURN; END IF;
 SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.payment_date,p.id),'[]'),
        coalesce(sum(CASE WHEN p.payment_type='refund' THEN -p.amount ELSE p.amount END),0),
        count(*)
 INTO receipts,ledger_total,payment_count FROM payments p WHERE p.order_id=p_order_id;
 -- Orders created before the payment ledger retain their trustworthy aggregate.
 -- Once ledger rows exist, the ledger becomes the single source of truth.
 effective_paid := CASE WHEN payment_count > 0 THEN ledger_total ELSE coalesce(current_order.amount_paid,0) END;
 SELECT coalesce(jsonb_agg(to_jsonb(f) ORDER BY f.occurred_on,f.id),'[]')
 INTO finance FROM financial_records f WHERE f.order_id=p_order_id;
 UPDATE invoices SET snapshot = jsonb_set(
   jsonb_set(
     jsonb_set(
       jsonb_set(
         jsonb_set(
           jsonb_set(snapshot,'{payments}',receipts,true),
           '{financial_records}',finance,true),
         '{paid}',to_jsonb(effective_paid),true),
       '{order,payment_status}',to_jsonb(current_order.payment_status),true),
     '{order,amount_paid}',to_jsonb(coalesce(current_order.amount_paid,ledger_total)),true),
   '{order,debt_amount}',to_jsonb(greatest(coalesce(current_order.sale_price,0)-effective_paid,0)),true)
 WHERE order_id=p_order_id;
END $$;

CREATE OR REPLACE FUNCTION public.sync_invoice_payment_trigger()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN
 IF TG_OP = 'DELETE' THEN
   PERFORM sync_invoice_payment_snapshot(OLD.order_id);
   RETURN OLD;
 END IF;
 PERFORM sync_invoice_payment_snapshot(NEW.order_id);
 RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS invoices_sync_from_payments ON public.payments;
CREATE TRIGGER invoices_sync_from_payments AFTER INSERT OR UPDATE OR DELETE ON public.payments
FOR EACH ROW EXECUTE FUNCTION public.sync_invoice_payment_trigger();

DROP TRIGGER IF EXISTS invoices_sync_from_financial_records ON public.financial_records;
CREATE TRIGGER invoices_sync_from_financial_records AFTER INSERT OR UPDATE OR DELETE ON public.financial_records
FOR EACH ROW EXECUTE FUNCTION public.sync_invoice_payment_trigger();

CREATE OR REPLACE FUNCTION public.sync_invoice_order_payment_trigger()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS $$
BEGIN PERFORM sync_invoice_payment_snapshot(NEW.id); RETURN NEW; END $$;

DROP TRIGGER IF EXISTS invoices_sync_from_order_payment ON public.orders;
CREATE TRIGGER invoices_sync_from_order_payment
AFTER UPDATE OF payment_status,amount_paid,debt_amount ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.sync_invoice_order_payment_trigger();

DO $$ DECLARE invoice_order_id bigint;
BEGIN
 FOR invoice_order_id IN SELECT order_id FROM public.invoices LOOP
   PERFORM public.sync_invoice_payment_snapshot(invoice_order_id);
 END LOOP;
END $$;

REVOKE ALL ON FUNCTION public.issue_invoice(bigint,text), public.sync_invoice_payment_snapshot(bigint), public.sync_invoice_payment_trigger(), public.sync_invoice_order_payment_trigger(), public.save_order_invoice_fields(jsonb,jsonb), public.create_order_before_invoice(jsonb,text), public.update_order_before_invoice(jsonb,text), public.create_order_with_inventory(jsonb,text), public.update_order_with_inventory(jsonb,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.issue_invoice(bigint,text), public.create_order_with_inventory(jsonb,text), public.update_order_with_inventory(jsonb,text) TO service_role;
COMMIT;
