-- Direct procurement and receiving. Historical shipment rows remain untouched.
BEGIN;

ALTER TABLE public.purchase_batches
  ADD COLUMN IF NOT EXISTS procurement_flow text NOT NULL DEFAULT 'LEGACY';
ALTER TABLE public.purchase_batches DROP CONSTRAINT IF EXISTS purchase_batches_procurement_flow_check;
ALTER TABLE public.purchase_batches ADD CONSTRAINT purchase_batches_procurement_flow_check
  CHECK(procurement_flow IN ('LEGACY','DIRECT'));

ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS configuration text NOT NULL DEFAULT '';
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS tracking_code_cn text NOT NULL DEFAULT '';
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS shipping_rmb numeric(14,2) NOT NULL DEFAULT 0 CHECK(shipping_rmb>=0);
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS received_at timestamptz;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS ignored_at timestamptz;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS ignored_by text;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS ignore_reason text;
ALTER TABLE public.laptops ADD COLUMN IF NOT EXISTS source_unresolved boolean NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS purchase_items_tracking_cn_idx ON public.purchase_items(lower(tracking_code_cn));
CREATE INDEX IF NOT EXISTS purchase_items_direct_pending_idx
  ON public.purchase_items(purchase_batch_id,id) WHERE received_at IS NULL AND ignored_at IS NULL;

CREATE TABLE IF NOT EXISTS public.intake_receipts(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 idempotency_key text NOT NULL UNIQUE CHECK(length(btrim(idempotency_key)) BETWEEN 8 AND 100),
 received_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
 received_by text NOT NULL, notes text NOT NULL DEFAULT '', items jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS public.unmatched_received_items(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 laptop_id bigint NOT NULL UNIQUE REFERENCES public.laptops(id) ON DELETE RESTRICT,
 intake_receipt_id bigint NOT NULL REFERENCES public.intake_receipts(id) ON DELETE RESTRICT,
 tracking_code_cn text NOT NULL DEFAULT '', serial text, name text NOT NULL,
 configuration text NOT NULL DEFAULT '', notes text NOT NULL DEFAULT '',
 status text NOT NULL DEFAULT 'OPEN' CHECK(status IN('OPEN','MATCHED')),
 matched_purchase_item_id bigint UNIQUE REFERENCES public.purchase_items(id) ON DELETE RESTRICT,
 matched_by text, matched_at timestamptz, created_at timestamptz NOT NULL DEFAULT timezone('utc',now())
);
CREATE INDEX IF NOT EXISTS unmatched_received_tracking_idx ON public.unmatched_received_items(lower(tracking_code_cn)) WHERE status='OPEN';
ALTER TABLE public.intake_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unmatched_received_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.intake_receipts,public.unmatched_received_items FROM PUBLIC,anon,authenticated;
GRANT ALL ON public.intake_receipts,public.unmatched_received_items TO service_role;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

CREATE OR REPLACE FUNCTION public.next_direct_purchase_code(p_date date)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE prefix text:='PO-'||to_char(p_date,'YYYYMMDD')||'-'; n integer;
BEGIN
 PERFORM pg_advisory_xact_lock(hashtext(prefix));
 SELECT coalesce(max(right(batch_code,3)::integer),0)+1 INTO n
 FROM purchase_batches WHERE batch_code LIKE prefix||'%';
 RETURN prefix||lpad(n::text,3,'0');
END $$;

CREATE OR REPLACE FUNCTION public.refresh_direct_batch_status(p_batch_id bigint,p_actor text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE total_count integer; received_count integer; ignored_count integer;
BEGIN
 SELECT count(*),count(*) FILTER(WHERE received_at IS NOT NULL),count(*) FILTER(WHERE ignored_at IS NOT NULL)
 INTO total_count,received_count,ignored_count FROM purchase_items WHERE purchase_batch_id=p_batch_id;
 UPDATE purchase_batches SET
   status=CASE WHEN received_count+ignored_count>=total_count THEN 'RECEIVED'
     WHEN received_count>0 THEN 'PARTIALLY_RECEIVED' ELSE 'CONFIRMED' END,
   updated_by=p_actor
 WHERE id=p_batch_id AND procurement_flow='DIRECT' AND status<>'CANCELLED';
END $$;

CREATE OR REPLACE FUNCTION public.create_direct_purchase(p_batch jsonb,p_items jsonb,p_actor text,p_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE b purchase_batches%ROWTYPE; entry jsonb; subtotal numeric;
BEGIN
 SELECT * INTO b FROM purchase_batches WHERE idempotency_key=p_key;
 IF FOUND THEN RETURN to_jsonb(b); END IF;
 IF length(btrim(coalesce(p_key,''))) NOT BETWEEN 8 AND 100
   OR jsonb_typeof(p_items) IS DISTINCT FROM 'array'
   OR jsonb_array_length(p_items) NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION 'Lô mua không hợp lệ'; END IF;
 IF NOT EXISTS(SELECT 1 FROM suppliers WHERE id=(p_batch->>'supplier_id')::uuid AND active) THEN RAISE EXCEPTION 'Nhà cung cấp không hợp lệ'; END IF;
 IF coalesce((p_batch->>'exchange_rate')::numeric,0)<=0 THEN RAISE EXCEPTION 'Tỷ giá không hợp lệ'; END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_items) x WHERE
   length(btrim(coalesce(x->>'name',x->>'model',''))) NOT BETWEEN 1 AND 240
   OR length(coalesce(x->>'configuration',x->>'cpu',''))>1000
   OR coalesce((x->>'purchase_price_rmb')::numeric,-1)<0
   OR coalesce((x->>'shipping_rmb')::numeric,-1)<0
   OR length(coalesce(x->>'tracking_code_cn',x->>'china_tracking_code',''))>200) THEN
   RAISE EXCEPTION 'Thông tin máy không hợp lệ';
 END IF;
 SELECT coalesce(sum((x->>'purchase_price_rmb')::numeric),0) INTO subtotal FROM jsonb_array_elements(p_items) x;
 INSERT INTO purchase_batches(batch_code,supplier_id,purchase_date,exchange_rate,subtotal_rmb,
   domestic_shipping_rmb,other_cost_rmb,destination,status,notes,active,created_by,updated_by,idempotency_key,procurement_flow)
 VALUES(next_direct_purchase_code((p_batch->>'purchase_date')::date),(p_batch->>'supplier_id')::uuid,
   (p_batch->>'purchase_date')::date,(p_batch->>'exchange_rate')::numeric,subtotal,0,0,'OTHER','CONFIRMED',
   left(coalesce(p_batch->>'notes',''),3000),true,p_actor,p_actor,p_key,'DIRECT') RETURNING * INTO b;
 FOR entry IN SELECT value FROM jsonb_array_elements(p_items) LOOP
  INSERT INTO purchase_items(purchase_batch_id,brand,model,configuration,cpu,serial,purchase_price_rmb,
    tracking_code_cn,shipping_rmb,notes,status)
  VALUES(b.id,left(coalesce(entry->>'brand',''),100),btrim(coalesce(entry->>'name',entry->>'model')),
    left(coalesce(entry->>'configuration',entry->>'cpu',''),1000),'',
    nullif(left(btrim(coalesce(entry->>'serial','')),100),''),
    (entry->>'purchase_price_rmb')::numeric,
    left(btrim(coalesce(entry->>'tracking_code_cn',entry->>'china_tracking_code','')),200),
    coalesce((entry->>'shipping_rmb')::numeric,0),left(coalesce(entry->>'notes',''),3000),'CONFIRMED');
 END LOOP;
 INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name)
 VALUES('PURCHASE_BATCH',b.id::text,'CREATE',jsonb_build_object('flow','DIRECT','item_count',jsonb_array_length(p_items)),p_actor);
 RETURN to_jsonb(b);
EXCEPTION WHEN unique_violation THEN
 SELECT * INTO b FROM purchase_batches WHERE idempotency_key=p_key;
 IF FOUND THEN RETURN to_jsonb(b); END IF; RAISE;
END $$;

CREATE OR REPLACE FUNCTION public.receive_direct_items(p_items jsonb,p_notes text,p_actor text,p_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE receipt intake_receipts%ROWTYPE; entry jsonb; pi purchase_items%ROWTYPE;
 b purchase_batches%ROWTYPE; l laptops%ROWTYPE; u unmatched_received_items%ROWTYPE; rows jsonb:='[]'; serial_value text;
BEGIN
 SELECT * INTO receipt FROM intake_receipts WHERE idempotency_key=p_key;
 IF FOUND THEN RETURN to_jsonb(receipt); END IF;
 IF length(btrim(coalesce(p_key,''))) NOT BETWEEN 8 AND 100 OR jsonb_typeof(p_items) IS DISTINCT FROM 'array'
   OR jsonb_array_length(p_items) NOT BETWEEN 1 AND 200 THEN RAISE EXCEPTION 'Đợt nhận không hợp lệ'; END IF;
 INSERT INTO intake_receipts(idempotency_key,received_by,notes,items)
 VALUES(p_key,p_actor,left(coalesce(p_notes,''),3000),'[]') RETURNING * INTO receipt;
 FOR entry IN SELECT value FROM jsonb_array_elements(p_items) LOOP
  IF nullif(entry->>'purchase_item_id','') IS NOT NULL THEN
   SELECT * INTO pi FROM purchase_items WHERE id=(entry->>'purchase_item_id')::bigint FOR UPDATE;
   IF NOT FOUND OR pi.received_at IS NOT NULL OR pi.ignored_at IS NOT NULL OR pi.status='CANCELLED' THEN RAISE EXCEPTION 'Máy đã nhận, đã bỏ qua hoặc không tồn tại'; END IF;
   SELECT * INTO b FROM purchase_batches WHERE id=pi.purchase_batch_id AND procurement_flow='DIRECT' FOR UPDATE;
   IF NOT FOUND OR b.status='CANCELLED' THEN RAISE EXCEPTION 'Lô mua không hợp lệ'; END IF;
   IF EXISTS(SELECT 1 FROM shipment_items WHERE purchase_item_id=pi.id AND status<>'CANCELLED') THEN RAISE EXCEPTION 'Máy thuộc shipment lịch sử'; END IF;
   serial_value:=coalesce(nullif(btrim(entry->>'serial'),''),pi.serial);
   INSERT INTO laptops(name,serial,status,location,charger_status,is_locked,is_active,purchase_item_id,
     price_rmb,shipping_rmb,exchange_rate,import_price_vnd,tracking_code,condition_note,import_date,warehouse_date,month_key)
   VALUES(concat_ws(' ',nullif(pi.brand,''),pi.model),serial_value,'waiting_qc','store','unchecked',true,true,pi.id,
     pi.purchase_price_rmb,pi.shipping_rmb,b.exchange_rate,
     round((pi.purchase_price_rmb+pi.shipping_rmb)*b.exchange_rate/1000000,6),pi.tracking_code_cn,pi.notes,
     current_date,current_date,to_char(current_date,'MM/YYYY')) RETURNING * INTO l;
   UPDATE purchase_items SET laptop_id=l.id,serial=coalesce(serial_value,serial),received_at=timezone('utc',now()),status='RECEIVED' WHERE id=pi.id;
   PERFORM sync_laptop_cost_components(l.id,p_actor);
   IF pi.shipping_rmb>0 AND NOT EXISTS(SELECT 1 FROM laptop_cost_components WHERE laptop_id=l.id AND source_type='PURCHASE_ITEM' AND source_id=pi.id::text AND cost_type='CN_SHIPPING') THEN
    INSERT INTO laptop_cost_components(laptop_id,cost_type,amount_vnd,amount_rmb,exchange_rate,source_type,source_id,description,created_by)
    VALUES(l.id,'CN_SHIPPING',round(pi.shipping_rmb*b.exchange_rate,0),pi.shipping_rmb,b.exchange_rate,'PURCHASE_ITEM',pi.id::text,'Vận chuyển riêng của máy',p_actor);
   END IF;
   PERFORM refresh_direct_batch_status(b.id,p_actor);
  ELSE
   IF length(btrim(coalesce(entry->>'name',''))) NOT BETWEEN 1 AND 240 THEN RAISE EXCEPTION 'Nhập tên máy chưa rõ nguồn'; END IF;
   INSERT INTO laptops(name,serial,tracking_code,condition_note,status,location,charger_status,is_active,is_locked,
     source_unresolved,import_date,warehouse_date,month_key)
   VALUES(btrim(entry->>'name'),nullif(left(btrim(coalesce(entry->>'serial','')),100),''),
     left(btrim(coalesce(entry->>'tracking_code_cn',entry->>'tracking_code','')),200),left(coalesce(entry->>'notes',''),2000),
     'waiting_qc','store','unchecked',true,true,true,current_date,current_date,to_char(current_date,'MM/YYYY')) RETURNING * INTO l;
   INSERT INTO unmatched_received_items(laptop_id,intake_receipt_id,tracking_code_cn,serial,name,configuration,notes)
   VALUES(l.id,receipt.id,l.tracking_code,l.serial,l.name,left(coalesce(entry->>'configuration',''),1000),left(coalesce(entry->>'notes',''),3000)) RETURNING * INTO u;
  END IF;
  INSERT INTO stock_movements(laptop_id,movement_type,to_location,note,performed_by,reference_type,reference_id)
  VALUES(l.id,'PURCHASE_RECEIVE','store','Nhận hàng trực tiếp',p_actor,'INTAKE_RECEIPT',receipt.id::text);
  rows:=rows||jsonb_build_array(jsonb_build_object('laptop_id',l.id,'purchase_item_id',l.purchase_item_id,'unmatched_id',u.id,'name',l.name,'serial',l.serial));
 END LOOP;
 UPDATE intake_receipts SET items=rows WHERE id=receipt.id RETURNING * INTO receipt;
 INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name)
 VALUES('RECEIVING_SESSION',receipt.id::text,'CREATE',jsonb_build_object('flow','DIRECT','items',rows),p_actor);
 RETURN to_jsonb(receipt);
EXCEPTION WHEN unique_violation THEN
 SELECT * INTO receipt FROM intake_receipts WHERE idempotency_key=p_key;
 IF FOUND THEN RETURN to_jsonb(receipt); END IF; RAISE;
END $$;

CREATE OR REPLACE FUNCTION public.match_unmatched_intake(p_unmatched_id bigint,p_item_id bigint,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE u unmatched_received_items%ROWTYPE; l laptops%ROWTYPE; pi purchase_items%ROWTYPE; b purchase_batches%ROWTYPE;
BEGIN
 PERFORM pg_advisory_xact_lock(hashtext('match-intake-'||least(p_unmatched_id,p_item_id)::text));
 SELECT * INTO u FROM unmatched_received_items WHERE id=p_unmatched_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy máy chưa rõ nguồn'; END IF;
 IF u.status='MATCHED' AND u.matched_purchase_item_id=p_item_id THEN SELECT * INTO l FROM laptops WHERE id=u.laptop_id; RETURN to_jsonb(l); END IF;
 IF u.status<>'OPEN' THEN RAISE EXCEPTION 'Máy đã được ghép nguồn'; END IF;
 SELECT * INTO pi FROM purchase_items WHERE id=p_item_id FOR UPDATE;
 IF NOT FOUND OR pi.received_at IS NOT NULL OR pi.ignored_at IS NOT NULL OR pi.status='CANCELLED' OR pi.laptop_id IS NOT NULL THEN RAISE EXCEPTION 'Máy trong lô không còn chờ nhận'; END IF;
 SELECT * INTO b FROM purchase_batches WHERE id=pi.purchase_batch_id AND procurement_flow='DIRECT' FOR UPDATE;
 IF NOT FOUND OR b.status='CANCELLED' THEN RAISE EXCEPTION 'Lô mua không hợp lệ'; END IF;
 SELECT * INTO l FROM laptops WHERE id=u.laptop_id FOR UPDATE;
 IF NOT FOUND OR l.source_unresolved IS NOT TRUE OR l.purchase_item_id IS NOT NULL THEN RAISE EXCEPTION 'Laptop không còn chờ đối chiếu nguồn'; END IF;
 UPDATE laptops SET purchase_item_id=pi.id,source_unresolved=false,price_rmb=pi.purchase_price_rmb,
   shipping_rmb=pi.shipping_rmb,exchange_rate=b.exchange_rate,
   import_price_vnd=round((pi.purchase_price_rmb+pi.shipping_rmb)*b.exchange_rate/1000000,6),
   tracking_code=coalesce(nullif(pi.tracking_code_cn,''),tracking_code),
   serial=coalesce(serial,pi.serial) WHERE id=l.id RETURNING * INTO l;
 UPDATE purchase_items SET laptop_id=l.id,serial=coalesce(serial,l.serial),received_at=coalesce(received_at,timezone('utc',now())),status='RECEIVED' WHERE id=pi.id;
 UPDATE unmatched_received_items SET status='MATCHED',matched_purchase_item_id=pi.id,matched_by=p_actor,matched_at=timezone('utc',now()) WHERE id=u.id;
 PERFORM sync_laptop_cost_components(l.id,p_actor);
 IF pi.shipping_rmb>0 AND NOT EXISTS(SELECT 1 FROM laptop_cost_components WHERE laptop_id=l.id AND source_type='PURCHASE_ITEM' AND source_id=pi.id::text AND cost_type='CN_SHIPPING') THEN
  INSERT INTO laptop_cost_components(laptop_id,cost_type,amount_vnd,amount_rmb,exchange_rate,source_type,source_id,description,created_by)
  VALUES(l.id,'CN_SHIPPING',round(pi.shipping_rmb*b.exchange_rate,0),pi.shipping_rmb,b.exchange_rate,'PURCHASE_ITEM',pi.id::text,'Vận chuyển riêng của máy',p_actor);
 END IF;
 PERFORM refresh_direct_batch_status(b.id,p_actor);
 INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name)
 VALUES('LAPTOP',l.id::text,'UPDATE',jsonb_build_object('source_resolved',true,'purchase_item_id',pi.id,'unmatched_id',u.id),p_actor);
 RETURN to_jsonb(l);
END $$;

CREATE OR REPLACE FUNCTION public.update_incoming_tracking(p_item_id bigint,p_tracking text,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE pi purchase_items%ROWTYPE;
BEGIN
 UPDATE purchase_items SET tracking_code_cn=left(btrim(coalesce(p_tracking,'')),200)
 WHERE id=p_item_id AND received_at IS NULL AND ignored_at IS NULL AND status<>'CANCELLED' RETURNING * INTO pi;
 IF NOT FOUND THEN RAISE EXCEPTION 'Chỉ cập nhật mã cho máy chưa nhận'; END IF;
 INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name)
 VALUES('PURCHASE_ITEM',pi.id::text,'UPDATE',jsonb_build_object('tracking_code_cn',pi.tracking_code_cn),p_actor);
 RETURN to_jsonb(pi);
END $$;

CREATE OR REPLACE FUNCTION public.ignore_direct_purchase_item(p_item_id bigint,p_reason text,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE pi purchase_items%ROWTYPE;
BEGIN
 UPDATE purchase_items SET ignored_at=timezone('utc',now()),ignored_by=p_actor,ignore_reason=left(btrim(coalesce(p_reason,'')),1000),status='CANCELLED'
 WHERE id=p_item_id AND received_at IS NULL AND ignored_at IS NULL AND laptop_id IS NULL RETURNING * INTO pi;
 IF NOT FOUND THEN RAISE EXCEPTION 'Máy không còn có thể bỏ qua'; END IF;
 PERFORM refresh_direct_batch_status(pi.purchase_batch_id,p_actor);
 INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name)
 VALUES('PURCHASE_ITEM',pi.id::text,'UPDATE',jsonb_build_object('ignored',true,'reason',pi.ignore_reason),p_actor);
 RETURN to_jsonb(pi);
END $$;

CREATE OR REPLACE FUNCTION public.inventory_display_status(p_laptop_id bigint,p_backend_status text,p_is_active boolean,p_is_locked boolean)
RETURNS text LANGUAGE sql STABLE SET search_path=public,pg_temp AS $$
 SELECT CASE
  WHEN p_is_active IS NOT TRUE OR p_backend_status='skipped' THEN 'skipped'
  WHEN p_backend_status='sold' OR EXISTS(SELECT 1 FROM orders o WHERE o.laptop_id=p_laptop_id AND o.is_active AND o.order_status='done') THEN 'sold'
  WHEN p_backend_status='returned_cn' OR EXISTS(SELECT 1 FROM supplier_return_items r WHERE r.laptop_id=p_laptop_id AND r.status NOT IN('CANCELLED','REJECTED','REFUNDED','REPLACED')) THEN 'returned_cn'
  WHEN p_backend_status IN('repair','repairing') OR EXISTS(SELECT 1 FROM repair_jobs r WHERE r.laptop_id=p_laptop_id AND r.status NOT IN('COMPLETED','CANCELLED')) THEN 'repairing'
  WHEN p_backend_status IN('waiting_qc','qc_in_progress','qc_failed') THEN 'waiting_qc'
  WHEN p_backend_status='deposited' OR EXISTS(SELECT 1 FROM orders o WHERE (o.laptop_id=p_laptop_id OR o.requested_laptop_id=p_laptop_id) AND o.is_active AND (o.order_status='deposited' OR o.payment_status='deposited')) THEN 'deposited'
  ELSE 'available' END
$$;

CREATE OR REPLACE VIEW public.unified_inventory AS
 SELECT 'PURCHASE_ITEM'::text entity_type,'purchase:'||pi.id entity_key,pi.id entity_id,NULL::bigint laptop_id,
  concat_ws(' ',nullif(pi.brand,''),pi.model) name,pi.configuration,pi.serial,pi.tracking_code_cn,
  'not_imported'::text display_status,'not_imported'::text backend_status,s.name supplier_name,b.batch_code,
  NULL::timestamptz received_at,NULL::timestamptz available_for_sale_at,b.purchase_date,
  to_char(b.purchase_date,'MM/YYYY') month_key,pi.purchase_price_rmb,pi.shipping_rmb,b.exchange_rate,
  round((pi.purchase_price_rmb+pi.shipping_rmb)*b.exchange_rate,2) landed_cost_vnd,false source_unresolved,pi.notes
 FROM purchase_items pi JOIN purchase_batches b ON b.id=pi.purchase_batch_id JOIN suppliers s ON s.id=b.supplier_id
 WHERE b.procurement_flow='DIRECT' AND b.status<>'CANCELLED' AND pi.received_at IS NULL AND pi.ignored_at IS NULL AND pi.status<>'CANCELLED'
 UNION ALL
 SELECT 'LAPTOP','laptop:'||l.id,l.id,l.id,l.name,''::text,l.serial,l.tracking_code,
  public.inventory_display_status(l.id,l.status,l.is_active,l.is_locked),l.status,s.name,b.batch_code,
  coalesce(pi.received_at,l.warehouse_date::timestamptz),l.available_for_sale_at,coalesce(b.purchase_date,l.import_date),
  l.month_key,l.price_rmb,l.shipping_rmb,l.exchange_rate,coalesce(c.landed_cost_vnd,l.import_price_vnd*1000000),
  l.source_unresolved,l.condition_note
 FROM laptops l LEFT JOIN purchase_items pi ON pi.id=l.purchase_item_id
 LEFT JOIN purchase_batches b ON b.id=pi.purchase_batch_id LEFT JOIN suppliers s ON s.id=b.supplier_id
 LEFT JOIN laptop_landed_costs c ON c.laptop_id=l.id WHERE l.is_active;

DROP VIEW IF EXISTS public.purchase_batch_summaries;
CREATE VIEW public.purchase_batch_summaries AS
SELECT b.*,(CASE WHEN b.procurement_flow='DIRECT' THEN coalesce(i.purchase_total_rmb,b.subtotal_rmb)
 ELSE b.subtotal_rmb+b.domestic_shipping_rmb+b.other_cost_rmb END)::numeric(14,2) total_rmb,
 coalesce(p.paid_rmb,0)::numeric(14,2) paid_rmb,
 greatest(CASE WHEN b.procurement_flow='DIRECT' THEN coalesce(i.purchase_total_rmb,b.subtotal_rmb)
 ELSE b.subtotal_rmb+b.domestic_shipping_rmb+b.other_cost_rmb END-coalesce(p.paid_rmb,0),0)::numeric(14,2) debt_rmb,
 coalesce(i.item_count,0)::bigint item_count,coalesce(i.received_count,0)::bigint received_count,
 coalesce(i.pending_count,0)::bigint pending_count,coalesce(i.ignored_count,0)::bigint ignored_count,
 coalesce(i.purchase_total_rmb,0)::numeric(14,2) purchase_total_rmb,
 coalesce(i.shipping_total_rmb,0)::numeric(14,2) shipping_total_rmb,s.code supplier_code,s.name supplier_name
FROM purchase_batches b JOIN suppliers s ON s.id=b.supplier_id
LEFT JOIN (SELECT purchase_batch_id,sum(amount_rmb) paid_rmb FROM supplier_payments GROUP BY purchase_batch_id) p ON p.purchase_batch_id=b.id
LEFT JOIN (SELECT purchase_batch_id,count(*) FILTER(WHERE status<>'CANCELLED' OR ignored_at IS NOT NULL) item_count,
 count(*) FILTER(WHERE received_at IS NOT NULL) received_count,
 count(*) FILTER(WHERE received_at IS NULL AND ignored_at IS NULL AND status<>'CANCELLED') pending_count,
 count(*) FILTER(WHERE ignored_at IS NOT NULL) ignored_count,sum(purchase_price_rmb) FILTER(WHERE ignored_at IS NULL) purchase_total_rmb,
 sum(shipping_rmb) FILTER(WHERE ignored_at IS NULL) shipping_total_rmb FROM purchase_items GROUP BY purchase_batch_id) i ON i.purchase_batch_id=b.id;

INSERT INTO app_options(group_key,option_key,label,sort_order) VALUES
 ('laptopStatus','not_imported','Chưa về hàng',0),('laptopStatus','waiting_qc','Chờ QC',1),
 ('laptopStatus','available','Sẵn hàng',2),('laptopStatus','deposited','Đã cọc',3),
 ('laptopStatus','sold','Đã bán',4),('laptopStatus','returned_cn','Back lại NCC',5),
 ('laptopStatus','repairing','Đang sửa chữa',6),('laptopStatus','skipped','Bỏ qua',7)
ON CONFLICT(group_key,option_key) DO UPDATE SET label=excluded.label,sort_order=excluded.sort_order,is_active=true;

REVOKE ALL ON public.unified_inventory,public.purchase_batch_summaries FROM PUBLIC,anon,authenticated;
GRANT SELECT ON public.unified_inventory,public.purchase_batch_summaries TO service_role;
REVOKE ALL ON FUNCTION public.next_direct_purchase_code(date),public.refresh_direct_batch_status(bigint,text),
 public.create_direct_purchase(jsonb,jsonb,text,text),public.receive_direct_items(jsonb,text,text,text),
 public.match_unmatched_intake(bigint,bigint,text),public.update_incoming_tracking(bigint,text,text),
 public.ignore_direct_purchase_item(bigint,text,text),public.inventory_display_status(bigint,text,boolean,boolean)
 FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_direct_purchase(jsonb,jsonb,text,text),public.receive_direct_items(jsonb,text,text,text),
 public.match_unmatched_intake(bigint,bigint,text),public.update_incoming_tracking(bigint,text,text),
 public.ignore_direct_purchase_item(bigint,text,text) TO service_role;
NOTIFY pgrst,'reload schema';
COMMIT;
