-- CitiLap: payment and finance ledger. Run after 20260907_security_and_schema.sql.
-- This migration does not delete existing business data.

BEGIN;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS amount_paid NUMERIC DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS debt_amount NUMERIC DEFAULT 0;

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
  payment_type TEXT NOT NULL CHECK (payment_type IN ('deposit', 'balance', 'cod', 'refund', 'other')),
  amount NUMERIC NOT NULL CHECK (amount > 0),
  payment_method TEXT NOT NULL DEFAULT 'transfer_cash',
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  reference_code TEXT,
  note TEXT,
  recorded_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS payments_order_date_idx
  ON payments (order_id, payment_date DESC, id DESC);

CREATE TABLE IF NOT EXISTS financial_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_type TEXT NOT NULL CHECK (record_type IN ('income', 'expense', 'refund', 'adjustment')),
  category TEXT NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  payment_id BIGINT REFERENCES payments(id) ON DELETE SET NULL,
  laptop_id BIGINT REFERENCES laptops(id) ON DELETE SET NULL,
  occurred_on DATE NOT NULL DEFAULT CURRENT_DATE,
  payment_method TEXT,
  note TEXT,
  recorded_by TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS financial_records_date_idx
  ON financial_records (occurred_on DESC, id DESC);
CREATE INDEX IF NOT EXISTS financial_records_order_idx
  ON financial_records (order_id, occurred_on DESC);

UPDATE orders
SET amount_paid = CASE
      WHEN payment_status = 'paid' THEN GREATEST(COALESCE(sale_price, 0), 0)
      WHEN payment_status IN ('deposited', 'cod') THEN GREATEST(COALESCE(deposit_amount, 0), 0)
      ELSE GREATEST(COALESCE(amount_paid, 0), 0)
    END,
    debt_amount = GREATEST(
      COALESCE(sale_price, 0) - CASE
        WHEN payment_status = 'paid' THEN GREATEST(COALESCE(sale_price, 0), 0)
        WHEN payment_status IN ('deposited', 'cod') THEN GREATEST(COALESCE(deposit_amount, 0), 0)
        ELSE GREATEST(COALESCE(amount_paid, 0), 0)
      END,
      0
    )
WHERE amount_paid IS NULL OR amount_paid = 0 OR debt_amount IS NULL;

ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE financial_records ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.record_order_payment(
  p_order_id BIGINT,
  p_amount NUMERIC,
  p_payment_type TEXT,
  p_payment_method TEXT DEFAULT 'transfer_cash',
  p_payment_date DATE DEFAULT CURRENT_DATE,
  p_reference_code TEXT DEFAULT NULL,
  p_note TEXT DEFAULT NULL,
  p_recorded_by TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order orders%ROWTYPE;
  v_payment payments%ROWTYPE;
  v_financial financial_records%ROWTYPE;
  v_amount_paid NUMERIC;
  v_deposit_amount NUMERIC;
  v_debt_amount NUMERIC;
  v_payment_status TEXT;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Payment amount must be greater than zero';
  END IF;
  IF p_payment_type NOT IN ('deposit', 'balance', 'cod', 'refund', 'other') THEN
    RAISE EXCEPTION 'Unsupported payment type';
  END IF;

  SELECT * INTO v_order FROM orders WHERE id = p_order_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Order % does not exist', p_order_id;
  END IF;
  IF v_order.is_active IS NOT TRUE THEN
    RAISE EXCEPTION 'Cannot record payment for an inactive order';
  END IF;

  IF p_payment_type = 'refund' THEN
    IF p_amount > COALESCE(v_order.amount_paid, 0) THEN
      RAISE EXCEPTION 'Refund cannot exceed amount already paid';
    END IF;
    v_amount_paid := GREATEST(COALESCE(v_order.amount_paid, 0) - p_amount, 0);
    v_deposit_amount := COALESCE(v_order.deposit_amount, 0);
  ELSE
    IF COALESCE(v_order.amount_paid, 0) + p_amount > COALESCE(v_order.sale_price, 0) THEN
      RAISE EXCEPTION 'Payment exceeds order sale price';
    END IF;
    v_amount_paid := COALESCE(v_order.amount_paid, 0) + p_amount;
    v_deposit_amount := COALESCE(v_order.deposit_amount, 0)
      + CASE WHEN p_payment_type = 'deposit' THEN p_amount ELSE 0 END;
  END IF;

  v_debt_amount := GREATEST(COALESCE(v_order.sale_price, 0) - v_amount_paid, 0);
  v_payment_status := CASE
    WHEN p_payment_type = 'refund' THEN 'refunded'
    WHEN v_debt_amount = 0 AND COALESCE(v_order.sale_price, 0) > 0 THEN 'paid'
    WHEN p_payment_type = 'cod' THEN 'cod'
    WHEN v_amount_paid > 0 THEN 'deposited'
    ELSE 'unpaid'
  END;

  INSERT INTO payments (
    order_id, payment_type, amount, payment_method, payment_date,
    reference_code, note, recorded_by
  ) VALUES (
    p_order_id, p_payment_type, p_amount, COALESCE(NULLIF(p_payment_method, ''), 'transfer_cash'),
    COALESCE(p_payment_date, CURRENT_DATE), p_reference_code, p_note, p_recorded_by
  ) RETURNING * INTO v_payment;

  INSERT INTO financial_records (
    record_type, category, amount, order_id, payment_id, occurred_on,
    payment_method, note, recorded_by
  ) VALUES (
    CASE WHEN p_payment_type = 'refund' THEN 'refund' ELSE 'income' END,
    p_payment_type,
    p_amount,
    p_order_id,
    v_payment.id,
    COALESCE(p_payment_date, CURRENT_DATE),
    COALESCE(NULLIF(p_payment_method, ''), 'transfer_cash'),
    p_note,
    p_recorded_by
  ) RETURNING * INTO v_financial;

  UPDATE orders
  SET amount_paid = v_amount_paid,
      deposit_amount = v_deposit_amount,
      debt_amount = v_debt_amount,
      payment_status = v_payment_status,
      updated_at = timezone('utc'::text, now())
  WHERE id = p_order_id
  RETURNING * INTO v_order;

  RETURN jsonb_build_object(
    'payment', to_jsonb(v_payment),
    'financial_record', to_jsonb(v_financial),
    'order', to_jsonb(v_order)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.record_order_payment(BIGINT, NUMERIC, TEXT, TEXT, DATE, TEXT, TEXT, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_order_payment(BIGINT, NUMERIC, TEXT, TEXT, DATE, TEXT, TEXT, TEXT)
  TO service_role;

CREATE OR REPLACE FUNCTION public.create_order_with_inventory(
  p_order JSONB,
  p_recorded_by TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_order orders%ROWTYPE;
  v_laptop laptops%ROWTYPE;
BEGIN
  INSERT INTO orders (
    created_date, sale_online, sale_offline, note, order_type, order_status,
    payment_status, payment_method, delivery_status, shipping_method, laptop_id,
    sale_price, deposit_amount, deposit_note, cod_amount, amount_paid, debt_amount,
    credit_card_fee, profit_vnd, trade_in_laptop_id, customer_id, customer_info,
    customer_address, tracking_code, ship_date, setup_note, warranty, gifts,
    laptop_locked, reservation_expires_at, cancel_reason, cancelled_at, is_active,
    created_at, updated_at
  )
  SELECT
    x.created_date, x.sale_online, x.sale_offline, x.note, x.order_type, x.order_status,
    x.payment_status, x.payment_method, x.delivery_status, x.shipping_method, x.laptop_id,
    COALESCE(x.sale_price, 0), COALESCE(x.deposit_amount, 0), x.deposit_note, COALESCE(x.cod_amount, 0),
    COALESCE(x.amount_paid, 0), COALESCE(x.debt_amount, 0), COALESCE(x.credit_card_fee, 0),
    COALESCE(x.profit_vnd, 0), x.trade_in_laptop_id, x.customer_id, x.customer_info,
    x.customer_address, x.tracking_code, x.ship_date, x.setup_note, x.warranty, x.gifts,
    COALESCE(x.laptop_locked, false), x.reservation_expires_at, x.cancel_reason, x.cancelled_at,
    COALESCE(x.is_active, true), COALESCE(x.created_at, timezone('utc'::text, now())),
    COALESCE(x.updated_at, timezone('utc'::text, now()))
  FROM jsonb_to_record(p_order) AS x(
    created_date DATE,
    sale_online VARCHAR(100),
    sale_offline VARCHAR(100),
    note TEXT,
    order_type VARCHAR(100),
    order_status VARCHAR(100),
    payment_status VARCHAR(100),
    payment_method VARCHAR(100),
    delivery_status VARCHAR(100),
    shipping_method VARCHAR(100),
    laptop_id BIGINT,
    sale_price NUMERIC,
    deposit_amount NUMERIC,
    deposit_note TEXT,
    cod_amount NUMERIC,
    amount_paid NUMERIC,
    debt_amount NUMERIC,
    credit_card_fee NUMERIC,
    profit_vnd NUMERIC,
    trade_in_laptop_id BIGINT,
    customer_id BIGINT,
    customer_info TEXT,
    customer_address TEXT,
    tracking_code TEXT,
    ship_date DATE,
    setup_note TEXT,
    warranty TEXT,
    gifts VARCHAR(100),
    laptop_locked BOOLEAN,
    reservation_expires_at TIMESTAMP WITH TIME ZONE,
    cancel_reason TEXT,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN,
    created_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE
  )
  RETURNING * INTO v_order;

  IF v_order.laptop_id IS NOT NULL
     AND v_order.is_active IS TRUE
     AND (
       v_order.order_status IN ('deposited', 'prepared', 'shipping', 'done')
       OR v_order.payment_status = 'deposited'
     ) THEN
    SELECT * INTO v_laptop FROM laptops WHERE id = v_order.laptop_id FOR UPDATE;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'Laptop % does not exist', v_order.laptop_id;
    END IF;

    UPDATE laptops
    SET is_locked = true,
        status = CASE WHEN v_order.order_status = 'done' THEN 'sold' ELSE 'deposited' END,
        updated_at = timezone('utc'::text, now())
    WHERE id = v_order.laptop_id
    RETURNING * INTO v_laptop;

    UPDATE orders
    SET laptop_locked = true,
        updated_at = timezone('utc'::text, now())
    WHERE id = v_order.id
    RETURNING * INTO v_order;

    INSERT INTO stock_movements (laptop_id, order_id, movement_type, note, performed_by)
    VALUES (
      v_order.laptop_id,
      v_order.id,
      CASE WHEN v_order.order_status = 'done' THEN 'SOLD' ELSE 'RESERVED' END,
      'Inventory updated by order transaction',
      p_recorded_by
    );
  END IF;

  RETURN jsonb_build_object(
    'order', to_jsonb(v_order),
    'laptop', CASE WHEN v_laptop.id IS NULL THEN NULL ELSE to_jsonb(v_laptop) END,
    'inventory_applied', true
  );
END;
$$;

REVOKE ALL ON FUNCTION public.create_order_with_inventory(JSONB, TEXT)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_order_with_inventory(JSONB, TEXT)
  TO service_role;

REVOKE ALL ON TABLE payments, financial_records FROM anon, authenticated;
GRANT ALL ON TABLE payments, financial_records TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;

COMMIT;
