-- Phase 3 — QC & Technical Inspection only. No repair jobs or supplier returns.
BEGIN;

CREATE TABLE IF NOT EXISTS public.qc_inspections (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  inspection_code text NOT NULL UNIQUE,
  laptop_id bigint NOT NULL REFERENCES public.laptops(id) ON DELETE RESTRICT,
  status text NOT NULL DEFAULT 'IN_PROGRESS' CHECK(status IN('IN_PROGRESS','COMPLETED','CANCELLED')),
  result text CHECK(result IN('PASS','FAIL')),
  started_by text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
  completed_by text,
  completed_at timestamptz,
  overall_notes text NOT NULL DEFAULT '',
  mainboard_status text NOT NULL DEFAULT 'UNKNOWN' CHECK(mainboard_status IN('ORIGINAL','OFFICIAL_REPLACED','REPAIRED','UNKNOWN')),
  charger_status text NOT NULL DEFAULT 'UNKNOWN' CHECK(charger_status IN('ORIGINAL','ORIGINAL_US','COMPATIBLE','MISSING','UNKNOWN')),
  cosmetic_grade text CHECK(cosmetic_grade IS NULL OR cosmetic_grade IN('A','B','C','D')),
  idempotency_key text NOT NULL UNIQUE CHECK(length(btrim(idempotency_key)) BETWEEN 8 AND 100),
  created_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
  CHECK((status='IN_PROGRESS' AND result IS NULL AND completed_at IS NULL) OR (status='COMPLETED' AND result IS NOT NULL AND completed_at IS NOT NULL) OR status='CANCELLED')
);
CREATE UNIQUE INDEX IF NOT EXISTS qc_inspections_one_active_per_laptop ON public.qc_inspections(laptop_id) WHERE status='IN_PROGRESS';
CREATE INDEX IF NOT EXISTS qc_inspections_laptop_history_idx ON public.qc_inspections(laptop_id,started_at DESC);

CREATE TABLE IF NOT EXISTS public.qc_check_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qc_inspection_id uuid NOT NULL REFERENCES public.qc_inspections(id) ON DELETE CASCADE,
  check_key text NOT NULL CHECK(check_key ~ '^[a-z0-9_]{2,60}$'),
  label text NOT NULL CHECK(length(btrim(label)) BETWEEN 1 AND 120),
  result text NOT NULL CHECK(result IN('PASS','FAIL','WARNING','NOT_TESTED','NOT_APPLICABLE')),
  note text NOT NULL DEFAULT '',
  checked_by text NOT NULL,
  checked_at timestamptz NOT NULL DEFAULT timezone('utc',now()),
  UNIQUE(qc_inspection_id,check_key)
);

CREATE OR REPLACE FUNCTION public.next_qc_inspection_code()
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE prefix text:='QC-'||to_char(current_date,'YYYYMMDD')||'-'; n integer;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(prefix));
  SELECT coalesce(max(right(inspection_code,3)::integer),0)+1 INTO n FROM qc_inspections WHERE inspection_code LIKE prefix||'%';
  RETURN prefix||lpad(n::text,3,'0');
END $$;

CREATE OR REPLACE FUNCTION public.start_qc_inspection(p_laptop_id bigint,p_actor text,p_idempotency_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE l laptops%ROWTYPE; q qc_inspections%ROWTYPE;
BEGIN
  SELECT * INTO q FROM qc_inspections WHERE idempotency_key=p_idempotency_key;
  IF FOUND THEN RETURN to_jsonb(q); END IF;
  IF length(btrim(coalesce(p_idempotency_key,''))) NOT BETWEEN 8 AND 100 THEN RAISE EXCEPTION 'Idempotency key không hợp lệ'; END IF;
  SELECT * INTO l FROM laptops WHERE id=p_laptop_id AND is_active IS TRUE FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy laptop'; END IF;
  IF l.status NOT IN('waiting_qc','qc_failed') THEN RAISE EXCEPTION 'Laptop không ở trạng thái có thể bắt đầu QC (%)',l.status; END IF;
  INSERT INTO qc_inspections(inspection_code,laptop_id,started_by,idempotency_key) VALUES(next_qc_inspection_code(),l.id,p_actor,p_idempotency_key) RETURNING * INTO q;
  PERFORM set_config('app.qc_transition','on',true);
  UPDATE laptops SET status='qc_in_progress',is_locked=true WHERE id=l.id;
  INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('QC_INSPECTION',q.id::text,'CREATE',jsonb_build_object('inspection_code',q.inspection_code,'laptop_id',l.id),p_actor);
  RETURN to_jsonb(q);
EXCEPTION WHEN unique_violation THEN
  SELECT * INTO q FROM qc_inspections WHERE idempotency_key=p_idempotency_key;
  IF FOUND THEN RETURN to_jsonb(q); END IF; RAISE;
END $$;

CREATE OR REPLACE FUNCTION public.complete_qc_inspection(p_inspection_id uuid,p_result text,p_mainboard_status text,p_charger_status text,p_cosmetic_grade text,p_notes text,p_items jsonb,p_actor text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE q qc_inspections%ROWTYPE; l laptops%ROWTYPE; item jsonb; item_count integer; failed_count integer; untested_count integer;
BEGIN
  IF p_result NOT IN('PASS','FAIL') OR p_mainboard_status NOT IN('ORIGINAL','OFFICIAL_REPLACED','REPAIRED','UNKNOWN') OR p_charger_status NOT IN('ORIGINAL','ORIGINAL_US','COMPATIBLE','MISSING','UNKNOWN') THEN RAISE EXCEPTION 'Kết quả QC không hợp lệ'; END IF;
  IF p_cosmetic_grade IS NOT NULL AND p_cosmetic_grade NOT IN('A','B','C','D') THEN RAISE EXCEPTION 'Phân hạng ngoại hình không hợp lệ'; END IF;
  IF jsonb_typeof(p_items)<>'array' OR jsonb_array_length(p_items)=0 OR jsonb_array_length(p_items)>60 THEN RAISE EXCEPTION 'Checklist QC không hợp lệ'; END IF;
  SELECT count(*),count(*) FILTER(WHERE value->>'result'='FAIL'),count(*) FILTER(WHERE value->>'result'='NOT_TESTED') INTO item_count,failed_count,untested_count FROM jsonb_array_elements(p_items);
  IF item_count<>(SELECT count(DISTINCT value->>'check_key') FROM jsonb_array_elements(p_items)) THEN RAISE EXCEPTION 'Checklist QC bị trùng'; END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_items) WHERE coalesce(value->>'check_key','')!~'^[a-z0-9_]{2,60}$' OR coalesce(value->>'result','') NOT IN('PASS','FAIL','WARNING','NOT_TESTED','NOT_APPLICABLE')) THEN RAISE EXCEPTION 'Checklist QC chứa dữ liệu không hợp lệ'; END IF;
  SELECT * INTO q FROM qc_inspections WHERE id=p_inspection_id FOR UPDATE;
  IF NOT FOUND OR q.status<>'IN_PROGRESS' THEN RAISE EXCEPTION 'Phiên QC không tồn tại hoặc đã kết thúc'; END IF;
  SELECT * INTO l FROM laptops WHERE id=q.laptop_id FOR UPDATE;
  IF l.status<>'qc_in_progress' THEN RAISE EXCEPTION 'Trạng thái laptop không khớp phiên QC'; END IF;
  IF p_result='PASS' AND (failed_count>0 OR untested_count>0 OR p_mainboard_status='REPAIRED' OR p_charger_status='MISSING') THEN RAISE EXCEPTION 'Không thể PASS khi còn mục FAIL/chưa test, mainboard đã sửa hoặc thiếu sạc'; END IF;
  FOR item IN SELECT value FROM jsonb_array_elements(p_items) LOOP
    INSERT INTO qc_check_items(qc_inspection_id,check_key,label,result,note,checked_by) VALUES(q.id,item->>'check_key',left(item->>'label',120),item->>'result',left(coalesce(item->>'note',''),1000),p_actor);
  END LOOP;
  UPDATE qc_inspections SET status='COMPLETED',result=p_result,completed_by=p_actor,completed_at=timezone('utc',now()),overall_notes=left(coalesce(p_notes,''),5000),mainboard_status=p_mainboard_status,charger_status=p_charger_status,cosmetic_grade=p_cosmetic_grade WHERE id=q.id RETURNING * INTO q;
  PERFORM set_config('app.qc_transition','on',true);
  UPDATE laptops SET status=CASE WHEN p_result='PASS' THEN 'available' ELSE 'qc_failed' END,is_locked=CASE WHEN p_result='PASS' THEN false ELSE true END,condition_note=CASE WHEN btrim(coalesce(p_notes,''))<>'' THEN left(p_notes,2000) ELSE condition_note END WHERE id=l.id;
  INSERT INTO activity_logs(entity_type,entity_id,action,changes,user_name) VALUES('QC_INSPECTION',q.id::text,'UPDATE',jsonb_build_object('result',p_result,'laptop_id',l.id,'mainboard_status',p_mainboard_status,'check_count',item_count),p_actor);
  RETURN to_jsonb(q);
END $$;

CREATE OR REPLACE FUNCTION public.guard_laptop_qc_transition()
RETURNS trigger LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status AND (OLD.status IN('waiting_qc','qc_in_progress','qc_failed') OR NEW.status IN('qc_in_progress','qc_failed')) AND current_setting('app.qc_transition',true) IS DISTINCT FROM 'on' THEN
    RAISE EXCEPTION 'Trạng thái QC chỉ được thay đổi qua quy trình kiểm tra kỹ thuật';
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS guard_laptop_qc_transition_trigger ON public.laptops;
CREATE TRIGGER guard_laptop_qc_transition_trigger BEFORE UPDATE OF status ON public.laptops FOR EACH ROW EXECUTE FUNCTION public.guard_laptop_qc_transition();

DROP TRIGGER IF EXISTS qc_inspections_set_updated_at_trigger ON public.qc_inspections;
CREATE TRIGGER qc_inspections_set_updated_at_trigger BEFORE UPDATE ON public.qc_inspections FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
ALTER TABLE public.qc_inspections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qc_check_items ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.qc_inspections,public.qc_check_items FROM PUBLIC,anon,authenticated;
GRANT ALL ON public.qc_inspections,public.qc_check_items TO service_role;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
REVOKE ALL ON FUNCTION public.next_qc_inspection_code(),public.start_qc_inspection(bigint,text,text),public.complete_qc_inspection(uuid,text,text,text,text,text,jsonb,text),public.guard_laptop_qc_transition() FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.start_qc_inspection(bigint,text,text),public.complete_qc_inspection(uuid,text,text,text,text,text,jsonb,text) TO service_role;
COMMIT;
