import { readFile, readdir, writeFile } from 'node:fs/promises';

// Keep migration bodies unchanged. Only their outer transaction wrappers are
// removed so a failed rebuild rolls back the entire schema replacement.
const body = text => text.replace(/^\uFEFF/, '').replace(/^\s*(BEGIN|COMMIT);\s*$/gm, '');
const files = (await readdir('db/migrations')).filter(f => f.endsWith('.sql')).sort();
const restore = `
INSERT INTO public.user_profiles(id,name,role,is_active,created_at,updated_at)
SELECT (data->>'id')::uuid,data->>'name',data->>'role',
       (data->>'is_active')::boolean,(data->>'created_at')::timestamptz,(data->>'updated_at')::timestamptz
FROM saved_profiles;
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
NOTIFY pgrst, 'reload schema';
COMMIT;
`;
let sql = `-- GENERATED by node qa/build-db-init.mjs. Do not edit this output directly.
-- DESTRUCTIVE: replaces public schema and ALL business data. Auth users and
-- existing user_profiles are preserved. Run reseed_data.sql after this file.
-- Run as postgres in Supabase SQL Editor. Entire rebuild is transactional.
BEGIN;
DROP TABLE IF EXISTS saved_profiles;
-- Keep rows if a SQL editor splits the script at a migration transaction
-- boundary; the generated script still commits only after restoration.
CREATE TEMP TABLE saved_profiles(data jsonb) ON COMMIT PRESERVE ROWS;
DO $backup$ BEGIN
  IF to_regclass('public.user_profiles') IS NOT NULL THEN
    INSERT INTO saved_profiles SELECT to_jsonb(p) FROM public.user_profiles p;
  END IF;
END $backup$;
`;
sql += body(await readFile('db/bootstrap/legacy_core.sql','utf8'));
for (const file of files) sql += `\n-- MIGRATION: ${file}\n${body(await readFile(`db/migrations/${file}`,'utf8'))}\n`;
sql += restore;
await writeFile('init_full_db.sql',sql);
console.log(`Built init_full_db.sql with ${files.length} migrations.`);
